### ISSUE TITLE
Rule/RuleGroup id + level in DOM?

### ISSUE THREAD

**Issue by zaphide** [react-querybuilder/react-querybuilder#101]
Hi,

Is it possible to add the id and level for a group/rule in the DOM output?

Resulting in something like:
`
...<div class="rule" data-rule-id="01234567890">
   ...
...</div>
`
`
...<div class="ruleGroup" data-level="0" data-group-id="01234567891">
   ...
...</div>
`

Use case is for UI testing automation.

Cheers

**Comment by srinivasdamam** [comment]
Seems to be a fair ask to make this component testing friendly.
@jakeboone02 shall I create a PR for this ?

**Comment by jakeboone02** [comment]
@srinivasdamam go for it

**Comment by zaphide** [comment]
Thanks guys :)

**Comment by jakeboone02** [comment]
@zaphide welcome!  This feature was just released in v2.3.0.
