### ISSUE TITLE
Making formatQuery handle string operators like "contains" and "begins with"

### ISSUE THREAD

**Issue by oumar-sh** [react-querybuilder/react-querybuilder#110]
Hello everyone,
I am using react-querybuilder and I noticed that the formatQuery function does not handle some operators like "contains" or "begins with".
I want to format the query in sql. I read in the documentation that I can use the valueProcessor argument to process the value but for the operators mentioned above, the corresponding operator in sql is the same (like). I want to add a fix in the formatQuery function by adding cases in processRule.
Can I open a PR ?
Thanks in advance for your reply.

**Comment by jakeboone02** [comment]
@oumar-sh absolutely feel free to open a PR if you have a fix or enhancement in mind.

**Comment by oumar-sh** [comment]
Thank you. I opened the PR #111

**Comment by oumar-sh** [comment]
Hello @jakeboone02 , could you please make a quick review of my pull request ?
Thank you.
