### ISSUE TITLE
Querybuilder Bi-directional

### ISSUE THREAD

**Issue by snsheth55** [react-querybuilder/react-querybuilder#114]
Hello,

I am looking for a query builder that can build a query based on input of JSON or SQL, not only build a query from scratch. I was wondering if this library supports that functionality? If so please provide example.

Thank you

**Comment by spade555** [comment]
Hello @snsheth55,

I was facing the same problem/requirement today, but finally figured out, that this library is bi-directional, so You can pass an existing initial query to the QueryBuilder and it will graphically show it up. Of course You can edit forward this query. To do this, You have to use the 'query' props on QueryBuilder. See the example in the demo folder!
[https://github.com/sapientglobalmarkets/react-querybuilder/tree/master/demo](url)

Cheers.

**Comment by spade555** [comment]
And yes, the documentation does not mention this feature right now... :)

**Comment by jakeboone02** [comment]
Wow, you're right, @spade555, the documentation doesn't mention the `query` prop at all.  What an oversight.  I'll fix it shortly!

**Comment by jakeboone02** [comment]
OK I've updated the [README](https://github.com/sapientglobalmarkets/react-querybuilder) to include the `query` prop.  @snsheth55, as @spade555 said, if you're looking for examples check out the [demo source code](https://github.com/sapientglobalmarkets/react-querybuilder/blob/master/demo/main.js).
