### ISSUE TITLE
Request new callback event

### ISSUE THREAD

**Issue by BabakYaghoobi** [react-querybuilder/react-querybuilder#118]
Hi,

Can you add a search icon inside input value and give us onClick event with owner input element ref ?
For this tools we can add some lookup fields that need fetch from server and show it to user for select one item to add input field !
.
.
lookupGridOnSelectItem = (inpEl, selectedValue)=>{
inpEl.val(selectedValue);
}
...
onSearchClick = (inputElement) =>{
  Axios.get(...).then((response) => {
  this.setState({ showLookupGrid: true, showLookupGridData: response.data, inpEl: inputElement});
  ...

})
}

Best Regards

**Comment by jakeboone02** [comment]
I'm not sure I understand your question, but it sounds like you just need to use a custom `ValueEditor` component.  That way you can style it any way you like and handle any data fetching in a `useEffect` hook (for function components) or lifecycle event (for classes).

**Comment by BabakYaghoobi** [comment]
Yes, exactly I need a custom ValueEditor, Can you make a simple custom ValueEditor width onClick event handler for using in QueryBuilder ?

Thank you for your response

**Comment by jakeboone02** [comment]
The simplest custom `ValueEditor` just takes the `value` and the `handleOnChange` callback, like this:
```jsx
const ValueEditor = ({ handleOnChange, value }) => (
  <input
    type="text"
    onChange={e => handleOnChange(e.target.value)}
    value={value}
  />
);
```
To use it, just add it to the `controlElements` prop like this:
```jsx
<QueryBuilder
  fields={/*...*/}
  controlElements={{ valueEditor: ValueEditor }}
/>
```

**Comment by BabakYaghoobi** [comment]
Thank you very much for your helping, your sample helped me to make what I need 

Best regards
