### ISSUE TITLE
Need a feature to remove all rules or change operator when data source changes

### ISSUE THREAD

**Issue by travisfalls** [react-querybuilder/react-querybuilder#120]
The app I am working on has a dropdown menu of different data sources and selecting one sets the fields that are passed into the query builder. Everything works great as long as you stick on the same data source. If you change the data source the fields will update but the rules stay and have to be cleared out manually. Is there a way to clear out all of the rules or reset the operator? The field is currently changing when I change the data source but the operator and value stay the same. Every data source has "id" as the first field so even resetting the operator to "not null" would solve my issue.

**Comment by jakeboone02** [comment]
Could you use a `key` prop to reset everything when the data source changes?  Like this:

```js
<QueryBuilder key={datasource} fields={...} />
```

**Comment by travisfalls** [comment]
I'm a rather new React developer so I guess I'm not entirely sure how that works.

**Comment by jakeboone02** [comment]
Then I hope I'm explaining this right:  when the `key` prop changes on an element, it forces a rerender of the entire subtree for that element (the [docs](https://reactjs.org/docs/lists-and-keys.html) on the `key` prop focus on list items, but the concept works for non-list items as well).  Basically you start fresh when you change the `key`.  So if you make the unique identifier for your data source the key for the `<QueryBuilder />` component, then everything will reset when the data source changes.  Does that make sense?

**Comment by travisfalls** [comment]
Yep! That seems pretty clear and exactly what I'm looking for. I'll give it a shot.

**Comment by travisfalls** [comment]
Holy cow! That did it! Thank you so much for your help. I've been struggling with this all morning.

**Comment by jakeboone02** [comment]
Glad I could help!  👍
