### ISSUE TITLE
Does react querybuilder have a method to parse SQL into JSON for initial query?

### ISSUE THREAD

**Issue by snsheth55** [react-querybuilder/react-querybuilder#123]
I need to use the querybuilder bi directional and to load the initial query I only have the SQL, I wanted to know if this query builder has a built in method to parse the SQL into the required JSON format the query builder requires.

Thank you

**Comment by jakeboone02** [comment]
No, it does not.  A quick [search](https://www.google.com/search?q=javascript+sql+parser) comes up with a few options you might want to try.  Let us know what works best!

**Comment by jakeboone02** [comment]
FYI, I've started working on this feature. Nothing to show just yet, but there will eventually be an exported `parseSQL` function that should be able to handle just about anything that `formatQuery(query, format)` outputs (where `format` is "sql", "parameterized", or "parameterized_named"), i.e. plain field vs. value comparisons and `between`/`in` expressions. It will _not_ be able to handle function calls, `CASE` expressions, `IN (SELECT ...`, etc.
