### ISSUE TITLE
Problem with removing the ids from the JSON format?

### ISSUE THREAD

**Issue by fabioespinosa** [react-querybuilder/react-querybuilder#124]
I am doing a webpage for filtering and I would like to provide bookmarkability.

However the ids in the JSON rules take too much space and the urls end up being a bit messy.

I am recursively stripping the ids from the JSON object, but I wonder what are the consequences of doing so. 

I guess they are just used to re-render on 'key' when they change?

Would you consider a PR to formatQuery to export JSON without 'ids'?

**Comment by miphe** [comment]
Currently, `nanoid` is used to generate IDs, but you could request a PR that let's a developer supply their own ID generation package. In your case you might want to supply a more URL friendly ID generator.

**Comment by jakeboone02** [comment]
I would be open to having both.  I can see the value in exporting an `id`-free JSON object, and I think @miphe's idea of providing one's own ID generation method could be useful as well.

**Comment by jakeboone02** [comment]
Closed by #125
