### ISSUE TITLE
Allow customization of "Rule" component

### ISSUE THREAD

**Issue by artenator** [react-querybuilder/react-querybuilder#133]
I have found that in some cases, customizing a Rule can be quite limiting while only using CSS. 

An idea I have is to allow a `Rule` component to be passed into `controlElements`, so that users can have more control over the structure of a rule. 

Please let me know if this is something that would be welcome in `react-querybuilder`; I would be happy to make this feature and create a PR.

**Comment by jakeboone02** [comment]
Sorry for taking so long to reply to this.  Yes, we would consider a PR that implemented a customizable `Rule` component.
