### ISSUE TITLE
How can we give placeholder or other options to value editor

### ISSUE THREAD

**Issue by bhupesh-sf** [react-querybuilder/react-querybuilder#134]
Is there any option to pass placeholder or other HTML options like required or type=date to the valueEditor of control element?

Also if I want to add one more value editor like custom date time picker while keeping the default as it is. Is there any option. I know I can use overwrite the existing one but can I extend that one?

**Comment by jakeboone02** [comment]
Unfortunately there is no way to extend the `ValueEditor` component as you describe.  The easiest thing would be to copy the code for the default component, modify it as you wish, and use that as your custom component.  Nor is there a way to pass HTML attributes to the component.  However, we would consider a PR that implemented that functionality.

**Comment by jakeboone02** [comment]
I wanted to update this issue with some more recent information for anyone that finds the page through a search engine. Almost everything that @bhupesh-sf asked for two years ago is now supported with the default components and standard configurations:

> Is there any option to pass placeholder [...]

Yes, `placeholder` is now an optional property of the [field object](https://react-querybuilder.js.org/docs/typescript#fields).

> or other HTML options like required [...]

Not `required`, no. May be added in the future.

> or type=date to the valueEditor of control element?

Yes, you can set `inputType: "date"` on the field object or have the `getInputType` function prop return `"date"` (or `"time"`, `"datetime-local"`, or any other input type--unsupported types fall back to `"text"`).

> Also if I want to add one more value editor like custom date time picker while keeping the default as it is. Is there any option. I know I can use overwrite the existing one but can I extend that one?

Yes! There is a page on the [documentation site](https://react-querybuilder.js.org/) called ["Custom components with fallbacks"](https://react-querybuilder.js.org/docs/tips/custom-with-fallback) that demonstrates how to do exactly what you're describing.

**Comment by fxylee** [comment]
may be added current rule instance to ValueEditor like `fieldData`.

so, developers can get any custom attribute, and render with custom attributes
@jakeboone02 
```json
{
  "field": "field_name",
  "operator": ">",
  "value": 3,
  "fieldData": {
    "name": "field_name",
    "label": "field_label",
    "custom_attr": "any thing"
  },
  "rule": {
    "field": "field_name",
    "operator": ">",
    "value": 3,
    "custom_attr_1": "$",
    "custom_attr_2": 2,
    "custom_attr_other": "attr_value"
  }
}
```

**Comment by jakeboone02** [comment]
@fxylee you could get the rule with a combination of `context`, `path`, and the `findPath` utility function.

Pass the query down through the `context` prop like `context={{ query }}`, then read that from your custom value editor and get the current rule like this: `const rule = findPath(props.path, props.context.query)`.

**Comment by fxylee** [comment]
Yes, I have got this solution, it works. Thank you for your reply and your contribution to this project!
