### ISSUE TITLE
Checking for IE11 Support

### ISSUE THREAD

**Issue by vitorhsb** [react-querybuilder/react-querybuilder#143]
Hi,

I am a maintainer of a project which must have support for IE11 browser.
I'm wondering what is your browser support list since this project has been flagged as not ES5 safe.

Checking ES5 support for node_modules on my project with [are-you-es5](https://github.com/obahareth/are-you-es5) shows:

```
> npx are-you-es5 check . -rv

...
✅ react-... is ES5
❌ react-querybuilder is not ES5
✅ react-... is ES5
...
```

If you try are-you-es5 on your project folder you would get the result:

```
> npx are-you-es5 check . -r -v

npx: installed 10 in 5.236s
✅ lodash is ES5
❌ nanoid is not ES5
✅ prop-types is ES5

Babel-loader exclude regex:
/[\\/]node_modules[\\/](?!(nanoid)[\\/])/
Non-ES5 dependencies detected.
```

So, to provide support you would have to transpile the offending `nanoid` package as mentioned on their README file in 
https://github.com/ai/nanoid#ie

**Comment by jakeboone02** [comment]
@vitorhsb I've opened PR #144 to resolve this issue.  Can you take a look and see if I've covered everything before I merge it?

**Comment by vitorhsb** [comment]
Looks good.

Thanks for your super quick response.

**Comment by jakeboone02** [comment]
@vitorhsb v3.5.0 should be fully compatible with IE11.  Please let me know if it's not.

**Comment by vitorhsb** [comment]
> @vitorhsb v3.5.0 should be fully compatible with IE11. Please let me know if it's not.

Yeah, it works. Thanks.

**Comment by jakeboone02** [comment]
For anyone coming to this page via a search engine, we now have an [IE11-compatible demo page](https://react-querybuilder.js.org/react-querybuilder/ie11.html).
