### ISSUE TITLE
Leaking global lodash

### ISSUE THREAD

**Issue by vitorhsb** [react-querybuilder/react-querybuilder#146]
Starting on v3.5.0 the lodash package is leaking to global window object.

Please fix, since it is inadvertently corrupting the window._ variable when requiring the react-querybuilder package.

**Comment by vitorhsb** [comment]
Screenshot showing console log with window._ variable in repository demo (local install). 

![Screen Shot 2020-06-22 at 16 42 20](https://user-images.githubusercontent.com/86801/85308048-a2f9b280-b4a8-11ea-9531-74f47bdb18da.png)

**Comment by jakeboone02** [comment]
@vitorhsb this issue was resolved in [v3.5.1](https://github.com/sapientglobalmarkets/react-querybuilder/releases/tag/v3.5.1).  Thanks for the report.
