### ISSUE TITLE
How to change list of operators based on previousely selected option.

### ISSUE THREAD

**Issue by bharatsewani1993** [react-querybuilder/react-querybuilder#150]
I am creating an application where I need to show the list of the operator based on previous selection.
For example: 
If the user choose NUMBER then I want to show him only three operators 1. Equals, 2. Greater Than or Equals, 3. Smaller Than or Equals.
If the user chooses Name then I want to show him only two operators 1. Begins with or 2. Ends With.
.
.
Is that supported currently?
If yes please let me know how can I do it?
Thanks in Advance
Bharat

**Comment by karenscheng** [comment]
Hi @bharatsewani1993, did you find a solution for this?

**Comment by bharatsewani1993** [comment]
yes, I found its solution in past.

**Comment by jakeboone02** [comment]
@karenscheng [this codesandbox](https://codesandbox.io/s/floral-cookies-6xvgj?file=/src/App.tsx) demonstrates one way to accomplish the behavior OP described.
