### ISSUE TITLE
on rule add its selecting first value

### ISSUE THREAD

**Issue by saurabhnemade** [react-querybuilder/react-querybuilder#156]
When we add a new rule first element in list is already selected.
You can see the behaviour on official doc example: https://sapientglobalmarkets.github.io/react-querybuilder/
Is there any way to disable that?
I want to disable that behaviour since I am showing a nested list with labels and I don't want label to be selected.

**Comment by saurabhnemade** [comment]
Update: While trying to figure out why left hand operand's value is selected, stumbled upon following code in `QueryBuilder.tsx`.

```
const createRule = (): RuleType => {
    const field = fields[0].name;

    return {
      id: `r-${nanoid()}`,
      field,
      value: '',
      operator: getOperatorsMain(field)[0].name
    };
  };
```

The field is always `fields[0].name` while creating new rule, which is causing the issue of first value being selected on left hand side operand.

@jakeboone02 I think this should be configurable. What do you think?

**Comment by jakeboone02** [comment]
That code is actually why it chooses the first field, not why it chooses the first value.  The value code is a little farther down, see https://github.com/sapientglobalmarkets/react-querybuilder/blob/master/src/QueryBuilder.tsx#L201-L234.

How would you model the configuration?  What should the options be and what would the behavior of each option be?

**Comment by jakeboone02** [comment]
Oh, I think I misunderstood.  I thought you were talking about the value being selected, not the field.  Same question though:  what should the configuration look like and how should each option behave?

**Comment by saurabhnemade** [comment]
I think it make sense to provide configuration param functions to provide `field`'s default and `value`'s default data only in case of new rule creation.

From code I can see in case of `value` we are only handling if array has length then set [0].value else if type is `checkbox` then false. But that's a limited set. Someone may want to specify their own set of defaults for different types based on values selected for field.
for e.g.
```
for number it can be 0
for floatingnumber it can be 0.0
for date it can be an epoch / today's date in user defined format
for email it can be empty or default support email address value of end user's choice 
```

I am thinking we should add `defaultField` and `defaultValue` function which will return string values. This will give user an opportunity to either not set `field` and `value` on new rule or specify program specific defaults.

```
controlElements={
  ...
  defaultField?: (fields: any) => string
  defaultValue?: (fieldData: any, values: any) => string
  ...
}
```

We can take out the logic of existing function's default selection part in new functions and use them as fallback functions if user does not wish to override them.


The behaviour:
If user passes `defaultField` then user function's returned value will be used. It needs to be string, if its empty then we can run existing logic to set it to [0].name and empty string if it's not an array.

If user passes `defaultValue` then user function's returned value will be used. It also need to be string, if its empty then we can run existing logic to set it to [0].value and empty string if it's not an array and false if it is eligible for that based of type which is currently happening.

I believe this will not impact any existing users since they are not passing these controlElement options.

**Comment by jakeboone02** [comment]
@saurabhnemade thanks for the detailed explanation.  I implemented the `defaultField` and `defaultValue` props mostly as you suggested, with a few changes, in PR #157.  The props are at the top level rather than within the `controlElements` object, and the function parameters are a little different (they match the internal default functions).  Let me know if that satisfies your needs.

**Comment by saurabhnemade** [comment]
Yup. It totally does the job 💯 
Thanks @jakeboone02 !!

**Comment by jakeboone02** [comment]
This feature is in [v3.7.0](https://github.com/sapientglobalmarkets/react-querybuilder/releases/tag/v3.7.0).
