### ISSUE TITLE
Empty field value by default when using select

### ISSUE THREAD

**Issue by ryukano** [react-querybuilder/react-querybuilder#163]
Hi! When I add rule with 'select' valueEditorType, value is empty even if I open selector and click on the first selector value. Also its reproduced on you demo page (query №2 - when add rule 'Instrument'). Added defaultValue in field object, but nothing changed

![image](https://user-images.githubusercontent.com/53697357/98032823-3fe83700-1e1d-11eb-8440-864462bfd720.png)
field:
![image](https://user-images.githubusercontent.com/53697357/98032877-53939d80-1e1d-11eb-969a-0e586c68b5a3.png)

**Comment by jakeboone02** [comment]
Hi, @ryukano.  I have published [version 3.8.2](https://github.com/sapientglobalmarkets/react-querybuilder/releases/tag/v3.8.2) which resolves this issue.
