### ISSUE TITLE
[question] Could I disable one of combinatorSelector, fieldSelector, operatorSelector ?

### ISSUE THREAD

**Issue by nvlong198** [react-querybuilder/react-querybuilder#165]
I want to disable operatorSelector to become like the first rule. How can I do that?
![image](https://user-images.githubusercontent.com/23328191/98761991-36f0fa00-2409-11eb-8f10-14da05f22146.png)
Thank you.

**Comment by jakeboone02** [comment]
Just replace the default operatorSelector with a custom version that renders null under the right conditions, like below.  You can see it in action in [this codesandbox](https://codesandbox.io/s/affectionate-chatterjee-g5y1h?file=/src/App.tsx).

```ts
import * as React from 'react';
import QueryBuilder, { OperatorSelectorProps } from 'react-querybuilder';
import 'react-querybuilder/dist/query-builder.scss';

const OperatorSelector = ({
  field,
  className,
  handleOnChange,
  options,
  title,
  value,
}: OperatorSelectorProps) => {
  if (field === 'gender') {
    return null;
  }
  return (
    <select
      className={className}
      value={value}
      title={title}
      onChange={(e) => handleOnChange(e.target.value)}
    >
      {options.map((option) => {
        return (
          <option key={option.name} value={option.name}>
            {option.label}
          </option>
        );
      })}
    </select>
  );
};

export default function App() {
  return (
    <div>
      <QueryBuilder
        fields={[
          {
            name: 'gender',
            label: 'Gender',
            operators: [{ name: '=', label: 'is' }],
            valueEditorType: 'select',
            values: [
              { name: 'm', label: 'Male' },
              { name: 'f', label: 'Female' },
            ],
          },
          {
            name: 'other',
            label: 'Other field',
          },
        ]}
        onQueryChange={(q) => console.log(q)}
        controlElements={{
          operatorSelector: OperatorSelector,
        }}
      />
    </div>
  );
}
```

**Comment by nvlong198** [comment]
@jakeboone02 
Can I change the operatorSelector at the last position? 
![image](https://user-images.githubusercontent.com/23328191/99060343-7ae32b00-25d2-11eb-8df8-213fb898e661.png)

**Comment by nvlong198** [comment]
I think I have to modify Rule Component :smiley:

**Comment by jakeboone02** [comment]
Right, to change the position order of any of the components within the rule, you would need to provide a custom Rule component.

**Comment by jakeboone02** [comment]
### Update

As of v4.0.0, `react-querybuilder` uses `display: flex` to manage rule and rule group layouts. Individual components can be re-ordered using the CSS `order` property based on their class ([see a list and diagram of classes here](https://react-querybuilder.js.org/docs/api/classnames)). There is no longer any need for a custom `<Rule />` component just to re-order the elements.
