### ISSUE TITLE
TypeError: QueryBuilder.formatQuery is not a function

### ISSUE THREAD

**Issue by saravanakj** [react-querybuilder/react-querybuilder#169]
Hi,

Need your help in resolving this.

Have used this component in a library. But its giving this error at runtime. After build, it emits the code as attached image.

formatQuery - exported as default function.

//in library
import QueryBuilder, { Controls, formatQuery } from 'react-querybuilder'

![image](https://user-images.githubusercontent.com/8859952/100278275-9cf18b80-2f8a-11eb-8a32-ffabbd48d3d0.png)

Thanks.

**Comment by jakeboone02** [comment]
Hi @saravanakj, can you reproduce this in a codesandbox or a simplified GitHub repo?

**Comment by jakeboone02** [comment]
Closing due to lack of response.
