### ISSUE TITLE
Can you please export "defaultOperators" and "defaultValueProcessor"?

### ISSUE THREAD

**Issue by geo-systems** [react-querybuilder/react-querybuilder#177]
Hi there,

I want to add an extra value processor for a new operator - e.g. `{ name: 'isEmpty', label: 'is Empty' }`. I need to keep the rest of the value processors (`not null`, `>=` etc.) the same.

Is it possible to export the `defaultValueProcessor` function and `defaultOperators` constant, so I can import them in my code and use? Otherwise, I'll need to copy-paste them.

**Comment by jakeboone02** [comment]
This has been addressed in [v3.9.2](https://github.com/sapientglobalmarkets/react-querybuilder/releases/tag/v3.9.2).  Thanks for the suggestion!
