### ISSUE TITLE
Is there support for multi select dropdown?

### ISSUE THREAD

**Issue by Ashishgollamudy** [react-querybuilder/react-querybuilder#184]
Hi guys I am checking to see if there is support for multi select dropdown like something i can pass to ```valueEditorType``` prop to make it multiselect?

Thanks

**Comment by jakeboone02** [comment]
There's not currently a way to do that without using a custom `ValueEditor` component and something like [`react-select`](https://react-select.com/).  Do you need some example code?

**Comment by Ashishgollamudy** [comment]
@jakeboone02  Yeah could you please provide that code, Thanks!

**Comment by jakeboone02** [comment]
I didn't do a lot of testing, but it should probably look something like this:

```js
// ValueEditor.js
import Select from "react-select";

const ValueEditor = ({ handleOnChange, value, values }) => (
  <Select onChange={handleOnChange} value={value} options={values} isMulti />
);

export default ValueEditor;
```

```js
// App.js
import QueryBuilder from "react-querybuilder";
import ValueEditor from "./ValueEditor";

const App = () => (
  <QueryBuilder
    fields={[
      {
        name: "test",
        label: "Test",
        values: [
          { value: "TEST1", label: "Test 1" },
          { value: "TEST2", label: "Test 2" },
        ],
      },
    ]}
    controlElements={{ valueEditor: ValueEditor }}
    operators={[{ name: "=", label: "is" }]}
  />
);

export default App;
```

**Comment by MohammedAlasaad** [comment]
Nice example, but I want to apply that only for one field. is that possible? thx

**Comment by jakeboone02** [comment]
@Mohammedalasaad sure, just switch the `ValueEditor` based on the field `name` or some other identifiable property. Something like this:

```jsx
// ValueEditor.js
import { ValueEditor as DefaultValueEditor } from "react-querybuilder";
import Select from "react-select";

const ValueEditor = props => {
  const { field, handleOnChange, value, values } = props;

  if (field === "test") {
    return <Select onChange={handleOnChange} value={value} options={values} isMulti />;
  }

  return <DefaultValueEditor {...props} />
};

export default ValueEditor;
```

**Comment by MohammedAlasaad** [comment]
Thank you @jakeboone02 👍

**Comment by MohammedAlasaad** [comment]
Is it possible to use react-select for fields and operators too ? @jakeboone02 
Thanks

**Comment by jakeboone02** [comment]
@Mohammedalasaad - yes it is.  Just set the `controlElements.fieldSelector` and `controlElements.operatorSelector` options in your `<QueryBuilder>` props to a custom component.
