### ISSUE TITLE
Input type multi select 

### ISSUE THREAD

**Issue by Ashishgollamudy** [react-querybuilder/react-querybuilder#185]
Hi, as I previously mentioned in issue #184 .... I have implemented the multi select in same way. However, I only wanted few inputs as multi select dropdown but i am getting all inputs as multi selects. Here is my sandbox  Could you please guide me in fixing this issue. Thanks again.

**Comment by jakeboone02** [comment]
I guessed by the `multiple` attribute in one of your fields that that's the field you wanted to make a multi-select.  I added the following code to the default `ValueEditor` component from the `react-querybuilder` source code.

```js
  if (fieldData && fieldData.multiple) {
    return (
      <Select
        onChange={handleOnChange}
        value={value}
        options={values}
        isMulti
      />
    );
  }
```

I think it's working as intended now.

**Comment by Ashishgollamudy** [comment]
That worked, Thank you so much.
