### ISSUE TITLE
Adding HAVING fields in sql query

### ISSUE THREAD

**Issue by almarrr** [react-querybuilder/react-querybuilder#191]
Is it possible to specify some fields as an HAVING clausule? I'm working with some joining of data from other tables and all of my WHERE clausules are working good, but I have have fields like "revenue" which are dynamically calculated.

Current generated sql query:

```
SELECT
	c.email,
	(p.price * count(o.order_id)) as revenue,
	count(p.id) as number_of_products
FROM
	customers c,
	orders o,
	products p
WHERE
	c.email = o.email
AND
	o.id = p.id
AND
	revenue < 5000
GROUP BY
	c.email
```

What I would like

```
SELECT
	c.email,
	(p.price * count(o.order_id)) as revenue,
	count(p.id) as number_of_products
FROM
	customers c,
	orders o,
	products p
WHERE
	c.email = o.email
AND
	o.id = p.id
GROUP BY
	c.email
HAVING
	revenue < 5000
```

Is this possible without a "hacky" solution?

**Comment by jakeboone02** [comment]
@almarrr this library only generates the `WHERE` clause of the statement, so I'm not sure where you're getting the `SELECT`, `FROM`, and `GROUP BY` clauses unless they're just hard-coded or you have some other component generating those.

You could have a separate query builder instance that handled the `HAVING` clause.  So the first instance would have fields like `email` (whatever you're grouping by), and the second would have fields like `revenue` and `number_of_products`.  Then you could use `formatQuery` to produce the `WHERE` and `HAVING` clauses respectively.

**Comment by almarrr** [comment]
Yes, I'm inserting the generated WHERE statement from the builder into my own query which is generated in my back-end itself.

This is working perfect except the "dynamic" columns. Thanks for a solution, I will try that one with the extra builder component. Hopefully in the future an option for this is added. Don't know if this is possible, but I is there a way to extend it?

**Comment by jakeboone02** [comment]
I'm having trouble picturing the API for such an extension.  What would you expect it to look like?
