### ISSUE TITLE
Build Query without Operators

### ISSUE THREAD

**Issue by allthingsbeta** [react-querybuilder/react-querybuilder#193]
Hello, 
Is it possible to use this library this way ?

![image](https://user-images.githubusercontent.com/30382382/112743154-7e3fe780-8fb2-11eb-8d2a-965397b74a2e.png)

I'm trying to build a logical conditioning statement without the need to provide a matching condition ( equal to something, greater than something etc)

The output I'm looking for is like this
(FirstName and LastName)

At the same time, to be able to generate output in both JSON and Sql formats.
Thank You

**Comment by jakeboone02** [comment]
You can remove the UI elements by using the `controlElements` prop.  Just set the `operatorSelector` and `valueEditor` properties to functions that return `null` (`() => null`).

```tsx
<QueryBuilder
  fields={fields}
  onQueryChange={(q) => setQuery(q)}
  query={query}
  showCombinatorsBetweenRules
  controlElements={{
    operatorSelector: () => null,
    valueEditor: () => null
  }}
/>
```

The SQL format can be generated using the `formatQuery` function.  You'll need to set the `valueProcessor` to return an empty string (`""`) and replace the default operator (`=`) with an empty string as well.

```ts
(formatQuery(query, { format: "sql", valueProcessor: () => "" }) as string).replace(/ =/g, "")
```

For the JSON format, assuming you don't want the operators and values represented, you can use the second parameter of the `JSON.stringify` function to whitelist the `rules`, `field`, and `combinator` properties.

```ts
JSON.stringify(query, ["rules", "field", "combinator"], 2)
```

I've done everything I just described in [this codesandbox](https://codesandbox.io/s/billowing-bird-h95ol?file=/src/App.tsx).

**Comment by allthingsbeta** [comment]
Appreciate the response. Will check this out !
Thanks and Have a gr8 day ahead.
