### ISSUE TITLE
Number type is enclosed within quotes

### ISSUE THREAD

**Issue by nobodyme** [react-querybuilder/react-querybuilder#194]
All types are enclosed within quotes, including Number.
I see that even the json tree generated has it that way and consequently the formatter that parses it produces it the same way. Can you guide me around correcting this one? Will be happy to fix it, if it's a bug.

**Comment by jakeboone02** [comment]
This is a consequence of HTML `<input>`s setting the value to a string, regardless of `type`.  You could use a custom `ValueEditor` and call the `onHandleChange` function with an actual number when `inputType` is `number`.  Something like [this codesandbox](https://codesandbox.io/s/stoic-goodall-7ynud?file=/src/ValueEditor.tsx).

**Comment by nobodyme** [comment]
Awesome thanks!
