### ISSUE TITLE
Operator "&" instead of "and"

### ISSUE THREAD

**Issue by allthingsbeta** [react-querybuilder/react-querybuilder#195]
Hello Wonderful Team,

Is there a way to get the output as:

Desired Output
1. (firstName = 'Steve' & lastName = 'Vai')
2. (firstName = 'Steve' | lastName = 'Vai')

Instead of the out of the box output:
(firstName = 'Steve' and lastName = 'Vai')
(firstName = 'Steve' or lastName = 'Vai')

I could do a string replacement however:

1. At the moment, I am not sure if that is the best way to do it.
2. So, Would like to understand if there is some prop to play around with to get the desired output.

PS: I should be able to construct both JSON and SQL objects from the desired output.

Many thanks and stay safe..

**Comment by jakeboone02** [comment]
This can be accomplished by replacing the default combinators.  See below or see it in action in [this codesandbox](https://codesandbox.io/s/elegant-nightingale-kv7sr?file=/src/App.tsx:0-941).  Use the `combinators` prop.

```tsx
import { useState } from "react";
import QueryBuilder, { formatQuery, RuleGroupType } from "react-querybuilder";
import "react-querybuilder/dist/query-builder.css";

export default function App() {
  const [query, setQuery] = useState<RuleGroupType>({
    id: "root",
    combinator: "&",
    rules: [
      {
        id: "rule1",
        field: "field1",
        operator: "=",
        value: "Value 1"
      },
      {
        id: "rule2",
        field: "field2",
        operator: "=",
        value: "Value 2"
      }
    ]
  });
  return (
    <>
      <QueryBuilder
        fields={[
          { name: "field1", label: "Field 1" },
          { name: "field2", label: "Field 2" }
        ]}
        onQueryChange={(q) => setQuery(q)}
        combinators={[
          { name: "&", label: "AND" },
          { name: "|", label: "OR" }
        ]}
        query={query}
      />
      <pre>{formatQuery(query, "sql")}</pre>
    </>
  );
}
```
