### ISSUE TITLE
Query rows should have 'display: flex'

### ISSUE THREAD

**Issue by Luifr** [react-querybuilder/react-querybuilder#199]
I'm using a custom component for the `valueEditor` (a autocomplete from material ui)

![image](https://user-images.githubusercontent.com/29644302/116563617-928d4200-a8da-11eb-88b9-bf2c056cbdc5.png)

And its causing a line break
The row component should be flex 

![image](https://user-images.githubusercontent.com/29644302/116563531-7d181800-a8da-11eb-9867-e7579dbc07df.png)

Simply by changing to `display: flex` in the page i get this result

![image](https://user-images.githubusercontent.com/29644302/116563830-c8cac180-a8da-11eb-9cc8-c42915624b23.png)

**Comment by jakeboone02** [comment]
@Luifr have you tried using the code in the demo for Material UI components?  The components are [here](https://github.com/react-querybuilder/react-querybuilder/tree/master/demo/components) and you can see how they're used in the [main.tsx file](https://github.com/react-querybuilder/react-querybuilder/blob/master/demo/main.tsx).  The [demo](https://react-querybuilder.github.io/react-querybuilder/) doesn't have the line wrapping problem so it should be a good example.
