### ISSUE TITLE
Uncaught ReferenceError: react is not defined

### ISSUE THREAD

**Issue by quickshiftin** [react-querybuilder/react-querybuilder#20]
I'm not sure where I'm going wrong, but it seems I can't get the component to load in a browser. I get this error `Uncaught ReferenceError: react is not defined` in the console.

To reproduce try creating a boilerplate app with [`react-create-app`](https://github.com/facebookincubator/create-react-app). Then modify the _src/App.js_ file minimally to include the QueryBuilder component. Here is mine

```javascript
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import QueryBuilder from 'react-querybuilder';

class App extends Component {
  render() {

    const fields = [ 
        {name: 'firstName', label: 'First Name'},
        {name: 'lastName', label: 'Last Name'},
        {name: 'age', label: 'Age'},
        {name: 'address', label: 'Address'},
        {name: 'phone', label: 'Phone'},
        {name: 'email', label: 'Email'},
        {name: 'twitter', label: 'Twitter'},
        {name: 'isDev', label: 'Is a Developer?', value: false},
    ];  

    function logQuery(query) {
        console.log(query);
    }   

    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <div>
            <QueryBuilder fields={fields} onQueryChange={logQuery}/>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );  
  }
}

export default App;
```

On [Stackoverflow](http://stackoverflow.com/questions/41726924/reactjs-cant-import-querybuilder) someone thinks you need to include react via script tag because react-querybuilder expects a global `react` variable; is that assessment correct?

I've tried adding a script tag atop my index.html file before loading the app bundle like this
```html
   <body>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.min.js"></script>
      <div id="root"></div>
   </body>
```
yet the error persists.

**Comment by pavanpodila** [comment]
This [PR](https://github.com/sapientglobalmarkets/react-querybuilder/pull/19) should be fixing it. @mrvicadai is on it. The problem arises because the lib did not make `react` as an external. The PR fixes that.

**Comment by quickshiftin** [comment]
Thank you, I will keep an eye on the PR!

**Comment by mreishus** [comment]
Is there any workaround available to use this library or do I just have to wait?

**Comment by pavanpodila** [comment]
This should be fixed now. Most of the work was done by @mrvicadai. I fixed a few imports and did some package updates. Version should now be `1.3.4`

**Comment by mreishus** [comment]
Thanks - I upgraded and I'm able to use the library now :)

**Comment by pavanpodila** [comment]
@mreishus Awesome. Closing

**Comment by quickshiftin** [comment]
Verified on my end as well; thanks guys!
