### ISSUE TITLE
Can I add extra key in fieldoptions of context? 

### ISSUE THREAD

**Issue by salmanbukhari37** [react-querybuilder/react-querybuilder#200]
Hello Jake Boon, I have another question I am getting the field options from DB. So in that case, we are getting `type` for recognizing optGroup has the following type. So my question is can we get `type` in ValueEditor?
```javascript
const context = {
    fieldOptions: [{
        name: 'Swedish Cars',
        options: [{
            name: 'volvo',
            valueEditorType: 'category-select',
            label: 'Volvo',
        }, {
            type: "vehicle",
            name: 'saab',
            valueEditorType: 'select',
            label: 'Saab',
            values: [
                { name: "saab", label: "saab 3" },
                { name: "saab", label: "saab 1" },
                { name: "saab", label: "saab 2" }
            ]
        }]
    }, {
        name: 'German Cars',
        options: [{
            name: 'mercedes',
            label: 'Mercedes',
        }, {
            name: 'audi',
            label: 'Audi',
        }]
    }]
}
```

**Comment by jakeboone02** [comment]
The way to get extra properties in the `ValueEditor` component for each field is to add them to the `fields` list, not `context`.  They will come to the `ValueEditor` component as part of the `fieldData`.

**Comment by salmanbukhari37** [comment]
But I am unable to get type value `onQueryChange` `event`. I tried passing value so I can get type there but unable to get that value.

```javascript
const logQuery = (query) => {
      console.log(query) 
  }

// output
{
  "id": "g-0.18307850714966278",
  "rules": [
    {
      "id": "r-0.06739310692537614",
      "field": "volvo",
      "value": "",
      "operator": "="
    }
  ],
  "combinator": "or",
  "not": false
}
```

**Comment by jakeboone02** [comment]
I think I would suggest storing your `fields` array somewhere you can import it from (a separate file, maybe), so it doesn't have to be passed as an argument to `onQueryChange`.
