### ISSUE TITLE
Chakra UI support

### ISSUE THREAD

**Issue by olezhek85** [react-querybuilder/react-querybuilder#206]
Hi @jakeboone02, you are going to support Chakra UI?

**Comment by jakeboone02** [comment]
Hey @olezhek85, sorry it took me a while to get to this. I was on vacation for a couple of weeks.

I haven't worked with Chakra UI yet, but I'll take a look at it and see about maybe adding it to the demo.

**Comment by jakeboone02** [comment]
@olezhek85 - the Chakra UI demo is now available.  [Demo](https://react-querybuilder.github.io/react-querybuilder/) / [Source code](https://github.com/react-querybuilder/react-querybuilder/tree/master/demo)
