### ISSUE TITLE
How apply bootstrap css?

### ISSUE THREAD

**Issue by mehul-accrete** [react-querybuilder/react-querybuilder#207]
I installed using npm command. But react querybuilder shows default CSS, I want to enabled the bootstrap css for querybuilder. How I can enabled the bootstrap css for this querybuilder.?

**Comment by mehul-accrete** [comment]
Resolved! I found from demo example.
https://github.com/react-querybuilder/react-querybuilder/blob/master/demo/main.tsx

Thanks.

**Comment by IamJeffG** [comment]
Here's a persistent link, the one above is broken: https://github.com/react-querybuilder/react-querybuilder/blob/v3.9.9/demo/main.tsx

In short: you need to pass bootstrap class names via the `controlClassnames` props to QueryBuilder.  There also seems to be a use for a couple custom `controlElements`.

**Comment by jakeboone02** [comment]
Thanks for posting the persistent link, @IamJeffG. FYI, v4 of `react-querybuilder` (to be released soon) will correspond to the release of several custom component libraries under the [`@react-querybuilder`](https://www.npmjs.com/org/react-querybuilder) org on npm. [`@react-querybuilder/bootstrap`](https://www.npmjs.com/package/@react-querybuilder/bootstrap) may be useful in this situation. You can download `v4.0.0-beta.7` of both that and the main package and try them out.
