### ISSUE TITLE
Sql Like Input to Query Builder

### ISSUE THREAD

**Issue by allthingsbeta** [react-querybuilder/react-querybuilder#211]
Hello, 

I have my Input queries in the below two formats (Sql like strings).

1. "(firstName != ' ' AND age >= '18')"
2. "( firstName & ( age & ( male | female ) ) )",

Is there a way to input these Sql Like strings to the `QueryBuilder` Component and convert it into the JSON Structure needed for the component to display the graphical query builder. Thank You.

Also, shoutout to all the maintainers for this amazing library.

**Comment by jakeboone02** [comment]
Hi @allthingsbeta, thanks for the shoutout!  We appreciate it.

This library doesn't have any utilities for converting SQL to the required JSON format, but I answered a similar question in #123 (which I didn't get any feedback on).  I just checked the link in that answer again and it still seems to bring up several options for what you want to do.

Let me know what approach you end up taking.

**Comment by krisgoks** [comment]
Check this out, I made a solution using JSEP  https://codesandbox.io/s/sql-to-react-querybuilder-json-nifw6?file=/src/App.js

**Comment by jakeboone02** [comment]
FYI, I've started working on this feature. Nothing to show just yet, but there will eventually be an exported `parseSQL` function that should be able to handle just about anything that `formatQuery(query, format)` outputs (where `format` is "sql", "parameterized", or "parameterized_named"), i.e. plain field vs. value comparisons and `between`/`in` expressions. It will _not_ be able to handle function calls, `CASE` expressions, `IN (SELECT ...`, etc.
