### ISSUE TITLE
on add rule its auto populating 0th index field with value in selected box

### ISSUE THREAD

**Issue by nageshwari17** [react-querybuilder/react-querybuilder#213]
Hi Team , 

I am using query builder to generate SQL query . I have notice that as I clicked on add rule . all three fields are auto populating of 0th index of fields and if its select  valueEditorType 0th index of value .  this will not meet my requirement . Is there any option that first popup valueSelect element then the other two field base on the field. Please help me with this.

**Comment by jakeboone02** [comment]
There is currently no way to accomplish what you're asking, but let me confirm what you want in case we move forward with adding the option:

1. User clicks Add Rule
2. New row appears with a single drop down list for Field selection, with no field selected (empty option or invalid selection?)
3. User selects a Field from the list
4. Operator and Value selectors appear next to the Field selector. Value selector has no initial selection (same question as before: empty option or invalid selection?)

Does that sound right?

**Comment by jakeboone02** [comment]
I will add that the reason the QueryBuilder component automatically selects the first option for Field, Operator, and Value (if `valueEditorType = 'select'`) is that it's trying to keep the query valid at all times.  If it didn't do that, you'd get situations where the SQL generated wouldn't be valid.

**Comment by nageshwari17** [comment]
> There is currently no way to accomplish what you're asking, but let me confirm what you want in case we move forward with adding the option:
> 
> 1. User clicks Add Rule
> 2. New row appears with a single drop down list for Field selection, with no field selected (empty option or invalid selection?)
> 3. User selects a Field from the list
> 4. Operator and Value selectors appear next to the Field selector. Value selector has no initial selection (same question as before: empty option or invalid selection?)
> 
> Does that sound right?

Yes your right . 
2)New row appears with a single drop down list for Field selection, with no field selected with empty option. 
4) Operator and Value selectors appear next to the Field selector. Value selector has with initial selection will work

**Comment by nageshwari17** [comment]
> I will add that the reason the QueryBuilder component automatically selects the first option for Field, Operator, and Value (if `valueEditorType = 'select'`) is that it's trying to keep the query valid at all times. If it didn't do that, you'd get situations where the SQL generated wouldn't be valid.

Yes in the current version it will give invalid SQL . Is there any way add validation on SQL generator that check whether all field contain value if yes then generate SQL query . like [jQuey querybuilder](https://querybuilder.js.org/demo.html)

**Comment by nageshwari17** [comment]
@jakeboone02  Is any update on this?

**Comment by jakeboone02** [comment]
Yeah, I'm working on a solution. I'll link the PR to this ticket once I get it ready.

**Comment by jakeboone02** [comment]
@nageshwari17 - this feature has been deployed in [v3.11.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v3.11.0).
