### ISSUE TITLE
Update the live demo to use the new version

### ISSUE THREAD

**Issue by pavanpodila** [react-querybuilder/react-querybuilder#22]
Current demo is hosted here: http://www.webpackbin.com/41LfnfeBb

We need to update it so it uses the latest version. Also update the Readme to point to the new URL.

**Comment by mreishus** [comment]
I did enough to make it run here, but didn't add any new features or anything like that.

  http://www.webpackbin.com/410SaYgPG

**Comment by pavanpodila** [comment]
You should switch the version of `react` and `react-dom` to the latest (15.x). Looks good otherwise!

**Comment by pavanpodila** [comment]
Once you have it, you can change the link in README. Thanks for doing it!

**Comment by mreishus** [comment]
I messed up the CSS a bit.  Do you have any ideas?  Old is on top, new is below

http://i.imgur.com/JJU3CaN.png

**Comment by mreishus** [comment]
nevermind, got it.  will update the README

**Comment by pavanpodila** [comment]
Thanks @mreishus for the [PR](https://github.com/sapientglobalmarkets/react-querybuilder/pull/24)
