### ISSUE TITLE
Clone / duplicate existing rule or group

### ISSUE THREAD

**Issue by vijayky** [react-querybuilder/react-querybuilder#222]
When building complex queries many times similar rule or group is required to add additional criteria. I was thinking if a clone button is available at rule and group level.

I understand that a button could be added by customizing Rule or Group component at UI level but not sure how to iterate and duplicate rules/groups. Hopefully this feature may help other community members.

**Comment by jakeboone02** [comment]
Yeah, I could see adding a prop that exposes "Clone Rule" and "Clone Group" buttons.  Would a `showCloneButtons={true}` prop be sufficient? (Of course you could do the same thing with custom `Rule`/`RuleGroup` components, but it would be simpler if the `QueryBuilder` component just did it for you.)

**Comment by vijayky** [comment]
> Yeah, I could see adding a prop that exposes "Clone Rule" and "Clone Group" buttons. Would a `showCloneButtons={true}` prop be sufficient? (Of course you could do the same thing with custom `Rule`/`RuleGroup` components, but it would be simpler if the `QueryBuilder` component just did it for you.)

Yes, it would be awesome, thanks for your prompt response.

**Comment by jakeboone02** [comment]
@vijayky - this feature will be available in the next release, which I'll publish after I review and act on your other comments from earlier today.

**Comment by vijayky** [comment]
Thank you @jakeboone02
