### ISSUE TITLE
Calling add rule or group action programmatically

### ISSUE THREAD

**Issue by zukilover** [react-querybuilder/react-querybuilder#243]
Hi, Team.

Thanks for the very useful library. 

I want to have a custom control element of add rule and group action, where both of them will be part of a single dropdown (next to combinator selector, there will be a dropdown trigger that will show Add Rule and Add Group actions).

How can I call each of the action callback programmatically?

**Comment by jakeboone02** [comment]
There is no imperative API for this library (although I might think about adding one now that you mention it...).  But I may have something like what you want here:  https://codesandbox.io/s/combined-add-rule-group-button-x67mp

It's using the `controlClassnames` and `controlElements` props to sort of combine the "+Rule" and "+Group" buttons into one. The dropdown is part of a custom element that just updates a state variable. The classes then determine which button is visible (even though they have the same label so the user is none the wiser).

**Comment by zukilover** [comment]
Thank you for the prompt response! 

I can live with the workaround now. Having the API exposed (maybe via hooks), would be a great addition in the future roadmap.
