### ISSUE TITLE
Expose imperative API

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#244]
Expose an imperative API for manipulating queries from outside the component.

There are several options for API design:

1. **Hooks** (`useQueryBuilder`?). Not sure how that would connect with a specific `<QueryBuilder />` instance, in case there were multiple being rendered.
2. **Refs**. Might have to wrap the main component with `forwardRef()`, but maybe not. See `react-select` [implementation](https://react-select.com/advanced#accessing-internals) of `focus()` and `blur()` methods.
3. **Callback** that provides an `api` parameter, _a la_ [AG Grid](https://ag-grid.com/react-data-grid/grid-events/#reference-miscellaneous-gridReady). This would probably be the easiest to implement.

@zukilover, since you gave me the [idea](/react-querybuilder/react-querybuilder/issues/243), do you have any preference among the API design choices?

**Comment by zukilover** [comment]
While **callback** is the easiest one, the original purpose of the request was really to enhance `controlElements`, so that we could rearrange the interfaces as much as we like. With that in mind, I think **refs** is the most elegant way of doing it.

**Comment by jakeboone02** [comment]
Thanks for the feedback, @zukilover. I've been looking at this and I can't wrap my head around a `ref`-based solution. It seems like it would be fairly trivial if `QueryBuilder` was a class component, but it's a function component. I don't really want to convert it (back) to a class component, and other methods using refs (`forwardRef`, using a custom `ref`-type prop, etc.) don't seem to accomplish the goal.

So, considering all that, I'm leaning toward the callback solution. It would be fairly simple to implement, and it's an acceptable solution in other libraries (e.g. AG Grid which I mentioned above). Should end up working something like this:

```tsx
const App = () => {
  const [api, setApi] = useState();

  return (
    <>
      <div>
        <button onClick={() => api?.addRule({ field: 'f1', operator: '=', value: 'val' }, [])}>
          Add rule
        </button>
      </div>
      <QueryBuilder onLoad={e => setApi(e.api)} />
    </>
  )
}
```

Thoughts?

**Comment by jakeboone02** [comment]
@zukilover - After working on the callback solution for a while, I realized that's not going to work either. Without a class instance to hang on to, it's really hard to keep the object references updated.

The best I could come up with is a set of utility functions (`add`, `remove`, `update`, `move`, and `clone`) that perform modifications to a provided query object and return a new query object. Would that even be useful?

**Comment by zukilover** [comment]
@jakeboone02 I really appreciate your effort on this enhancement. Although, utility functions will not really add that much of an improvement because we can actually do that per implementation basis without having to expose those abilities from within the library.

I would really like to help with the `ref` approach, that in my scenario will not only add enhancement to the library but also solve another new problem that I have, related to multiple instances of react-dnd HTML5 backends error. I could not provide details to the problem nor contributing with the enhancement at the moment. If this sounds alright with you, we could close this now and revisit later when we have more effective solutions.

**Comment by jakeboone02** [comment]
Yeah, it's probably better to wait to address this until after 4.0 is released, anyway. Lots of churn in the codebase at the moment.
