### ISSUE TITLE
Rule path

### ISSUE THREAD

**Issue by PauloStanize-NHT** [react-querybuilder/react-querybuilder#245]
Thanks for this incredible library guys!

Is it possible to receive the current rule path on `fieldSelector` and `valueEditor` props? It would be useful to create more concise `data-testids` and to change the query depending on user input for field and value...

**Comment by jakeboone02** [comment]
Definitely! I'll include the `path` prop on all rule & group sub-components in the final 4.0 release. Still trying to get drag-and-drop working with independent combinators, but once we're over that hurdle then 4.0 should be good to go.

**Comment by PauloStanize-NHT** [comment]
Awesome! Thanks for your fast reply!
