### ISSUE TITLE
Providing more context to controlElements

### ISSUE THREAD

**Issue by SamLoy** [react-querybuilder/react-querybuilder#26]
I am using the react-querybuilder for a project i'm working on. I have used the 'controlElements' param as a way of restyling and slightly adjusting the behavior of the query builder. This worked well and I was able to complete 90% of what i wanted. 

**The 10%**
- Prevent the user from making the query more than 3 levels deep
- Only show the combinator for a group when more than one appeared in a group.

Although both of these features could probably be built into the component, I was able to achieve this by forking the repo [here](https://github.com/SamLoy/react-querybuilder) and exposing the rules for the  group, and level which each controlElement appears.

An approach like this might open up the component for more custom behaviors. If you are interested take a look at my forked repo and maybe we can incorporate it into this.

Sam

**Comment by pavanpodila** [comment]
Hi @SamLoy, it looks like a useful thing to have. Would you mind sending a PR with some tests?

**Comment by SamLoy** [comment]
@pavanpodila  Done: 
https://github.com/sapientglobalmarkets/react-querybuilder/pull/27/files
