### ISSUE TITLE
Breaking change in data structure

### ISSUE THREAD

**Issue by alexandernst** [react-querybuilder/react-querybuilder#267]
I just had the chance to test the 4.0 and everything looks amazing! I'm sorry I couldn't test the beta 7 and 8 and keep providing feedback.

Anyways, as I mentioned [here](https://github.com/react-querybuilder/react-querybuilder/issues/204#issuecomment-1008448385) I have one small complaint about the 4.0: the (imho unnecessary) breaking change in the data structure of the rules. (now `rules` is an array of objects and strings (`["and" | "or"]`), instead of being an array of (nested) objects and having a `combinator` field for each "level")

I understand why the change was introduced (in order to implement what I asked in #204), but I think there might have been another way. Since #204 was all about refactoring the UI and since the precedence or the logical operators can be inferred no matter how the UI is represented, I thought that the change wouldn't affect the actual data structure of the library.

My bad for not noticing that the actual data structure changed and for not providing feedback in #204. I beg a pardon for that.

That said, since the 4.0 was already released (although only 12 days ago) and the breaking change was already done, I don't think it would be a good idea to do yet another breaking change and revert back to the old export format.

But what could be a good idea is to add another export format (next to `sql`, `json`, etc... maybe call it `v3` or `legacy`?) that would export the rules with the old data structure format. I think it shouldn't be too hard to accomplish, since there is already a `mongodb` format, which looks quite like the old format.

Not having introduced the BC in the data structure in the first place would have helped reduce the upgrade friction by 100%, but since that ship already sailed, next best thing is to add a "compatibility layer" in the export format. That will probably reduce the amount of work to be done by the users when they upgrade to 4.0.

All things considered, with or without this "compatibility layer", the 4.0 is looking amazing! Absolutely great job!

**Comment by jakeboone02** [comment]
Hi, @alexandernst. Thanks for the compliment! It was a lot of work to get 4.0 ready for release and I appreciate your feedback.

Much of the work, however, was done to _ensure_ backwards compatibility and actually leave the "legacy" behavior as the default. The new data structure is completely optional. As long as the `independentCombinators` prop is missing or `false`, and the `query` prop (or `defaultQuery` for uncontrolled components), if provided, has a `combinator` member, then the `<QueryBuilder />` component will act pretty much the same as it did in v3.12.1. Ditto for `formatQuery`: if the first argument is an object with `combinator` and `rules` members, then the output should be basically the same as in v3.12.1.

The only way to trigger the new behavior is to provide a query without a `combinator` member and set `independentCombinators` to `true`. That goes for `<QueryBuilder />` props as well as `formatQuery` options and the new `parseSQL` options as well.

The [demo](https://react-querybuilder.js.org/react-querybuilder/) exhibits the "legacy" behavior by default, but if I'm missing something, please let me know.

**Comment by alexandernst** [comment]
Oh, I didn't express myself properly, sorry for that. I was talking about the data structure when used in conjunction with the `independentCombinators` prop set to `true`.

When said parameter is set to `true` the data structure changes to what I described in my previous comment. This could have been avoided as the visual representation of the rules shouldn't affect the data structure.

Let me use some visual aid to make my point:

Let's start with a set of conditions such as: `(a > '4' or (b > '4' and c = '9'))`

![Nebulant_Builder](https://user-images.githubusercontent.com/89727/148748376-708a55ee-9b36-40ff-88b4-0753d24dba76.png)

The UI (v3) is mimicking the exact data structure of the query. Visually, the `a > 4` is at level `1`, while the `b > 4 and c = 9` is placed at level `2`, which is exactly what the data structure looks like.

```
{
  "id": "root",
  "combinator": "and",
  "rules": [
    {
      "field": "a",
      "operator": ">",
      "value": "4"
    },
    {
      "rules": [
        {
          "field": "b",
          "value": "4",
          "operator": "="
        },
        {
          "field": "c",
          "value": "9",
          "operator": ">"
        }
      ],
      "combinator": "or",
      "not": false
    }
  ],
  "not": false
}
```

-------------

Let's create that same set of conditions with the new UI (v4):

`(a > '4' or b > '4' and c = '9')`

![Nebulant_Builder](https://user-images.githubusercontent.com/89727/148749313-5cdc7d6a-0a5e-4281-b986-2c2ac7160ced.png)

Once again, the UI is mimicking the data structure of the query. All conditions are placed on level `1`, and the raw query looks like this:

```
{
  "rules": [
    {
      "field": "a",
      "value": "4",
      "operator": ">"
    },
    "and",
    {
      "field": "b",
      "value": "4",
      "operator": ">"
    },
    "or",
    {
      "field": "c",
      "value": "9",
      "operator": ">"
    }
  ],
  "not": false
}
```

------

Because of the precedence of logical operators, `(a > '4' or b > '4' and c = '9')` is equal to `(a > '4' or (b > '4' and c = '9'))`. 

This means that, just by checking the `independentCombinators` flag, the library could render the old data structure with the new UI (if `independentCombinators` is set to `true`) or the old UI (if `independentCombinators` is set to `false`).

Basically, if `independentCombinators` is set to `true`, this data structure 

```
{
  "id": "root",
  "combinator": "and",
  "rules": [
    {
      "field": "a",
      "operator": ">",
      "value": "4"
    },
    {
      "rules": [
        {
          "field": "b",
          "value": "4",
          "operator": "="
        },
        {
          "field": "c",
          "value": "9",
          "operator": ">"
        }
      ],
      "combinator": "or",
      "not": false
    }
  ],
  "not": false
}
```

can be rendered like this:

![Nebulant_Builder](https://user-images.githubusercontent.com/89727/148749313-5cdc7d6a-0a5e-4281-b986-2c2ac7160ced.png)

In fact, the new and the old UI could have been dynamically switched without having to change the (old) data structure.

IMHO the data structure shouldn't have been changed because of the `independentCombinators` prop (as it's possible to infer the old data structure from the new UI), but since this breaking change was already introduced, the next best thing that can be done is to create a new export format for the `formatQuery` function that should be able to export the data structure of the new UI (v4) (when `independentCombinators` is `true`) to what the query would have looked like if it was exported by the v3. That new export format would help current users to upgrade from v3 to v4.

**Comment by alexandernst** [comment]
Updated the comment with some clarifications.

**Comment by jakeboone02** [comment]
Ah, OK. I see what you're saying now. Actually I should have gleaned what you were trying to say from your previous threads.

I think grouping the `and/or` chains like you suggest has a couple of problems. For one, it would be harder to manage internally, and may be harder in userland as well. For example, consider the following `WHERE` clause:

```
a = 1 and b = 2 or c = 3 and d = 4
```

In the legacy format, we would have to represent that like so:

```json
{
  "combinator": "or",
  "rules": [
    {
      "combinator": "and",
      "rules": [
        {
          "field": "a",
          "operator": "=",
          "value": "1"
        },
        {
          "field": "b",
          "operator": "=",
          "value": "2"
        }
      ]
    },
    {
      "combinator": "and",
      "rules": [
        {
          "field": "c",
          "operator": "=",
          "value": "3"
        },
        {
          "field": "d",
          "operator": "=",
          "value": "4"
        }
      ]
    }
  ]
}
```

If the user changed the "or" to "and", then instead of just changing one `string`-type array element, we would reshuffle the entire structure to this:

```json
{
  "combinator": "and",
  "rules": [
    {
      "field": "a",
      "operator": "=",
      "value": "1"
    },
    {
      "field": "b",
      "operator": "=",
      "value": "2"
    },
    {
      "field": "c",
      "operator": "=",
      "value": "3"
    },
    {
      "field": "d",
      "operator": "=",
      "value": "4"
    }
  ]
}
```

The subgroups go away because they're unnecessary since all the combinators are "and".

Which leads me to this point: I think your suggestion only works if you prevent the creation of subgroups. The reason is there would be no way for the query builder to tell the difference between the internal object representation of the following two queries:

<img width="448" alt="react-querybuilder-flat-structure" src="https://user-images.githubusercontent.com/366438/148798976-d7b47576-7957-422e-80df-6dd94f618fb0.png">

<img width="466" alt="react-querybuilder-nested-groups" src="https://user-images.githubusercontent.com/366438/148799016-f884a9d2-a47c-4840-befb-46425270a0cc.png">

They would both be represented like this:

```json
{
  "combinator": "or",
  "rules": [
    {
      "combinator": "and",
      "rules": [
        {
          "field": "firstName",
          "operator": "=",
          "value": "Steve"
        },
        {
          "field": "lastName",
          "operator": "=",
          "value": "Vai"
        }
      ]
    },
    {
      "combinator": "and",
      "rules": [
        {
          "field": "firstName",
          "operator": "=",
          "value": "Jake"
        },
        {
          "field": "lastName",
          "operator": "=",
          "value": "Boone"
        }
      ]
    }
  ]
}
```

If the user was allowed to create a subgroup, there would be no way to tell if the user wanted to keep that group as a visual or explanatory aid for some reason, or if we could get rid of the group in the next render/`onQueryChange` call.

Also, the `combinator` is `'and' | 'or'` by default, but in practice can be any string. A user might want to make `'xor'` an option, for example. That would require additional precedence rules that I don't think I want to manage within the library itself, and also the user may believe that making the groups explicit in the UI would be easier to understand for the _end_ user.

All that said, there may be a compromise available. I could write a two-way conversion function that either:

1. takes a legacy-style query and flattens it into the `independentCombinators` style, or
2. takes an `independentCombinators` query and migrates the `combinator`s to the group level (creating new groups from `'and'` chains where necessary).

You could wrap your legacy `query` prop with that function to flatten the `rules` array, and do the reverse in `formatQuery` and `onQueryChange` to produce the legacy structure. That way you'd only have to deal with the legacy structure in your own code, but the query builder UI would show a flat query structure as (I think) you intend.

**Comment by alexandernst** [comment]
Oh, now I see your point about keeping the "state" of the UI inside the data structure. Yes, that makes sense. There might be cases in which users might want to explicitly create a subgroup, even if the "logical" representation of the entire set of conditions would be the same without the group.

Yes, a two-way function would be the ideal way to go from here, imho. That way we get to pick the good things from both sides!

**Comment by jakeboone02** [comment]
Great! I'll get started on the converter function and let you know when you can test it out.

**Comment by jakeboone02** [comment]
@alexandernst I threw together PR #268 which exports a new utility function called `convertQuery`. You can see it in action in [this codesandbox](https://codesandbox.io/s/react-querybuilder-convertquery-7nk2f?file=/src/initialQuery.ts), where `initialQuery` is created as a legacy type (`RuleGroupType`), but `initialQueryIC` is created as `RuleGroupTypeIC` (the new type) by simply passing `initialQuery` through `convertQuery`.

Let me know if this will work for your purposes or if you have any other feedback. If you give a 👍 then I'll release it as v4.1.2.

**Comment by alexandernst** [comment]
wow!! That was fast! Ok, let me try it

**Comment by jakeboone02** [comment]
Yeah, I already had most of the logic down since the `parseSQL` function does pretty much the same thing, so I just adapted it from SQL strings to rule groups.

**Comment by alexandernst** [comment]
@jakeboone02 I finished testing the PR. Everything is working as expected. Only 3 small notes.

1. Maybe it would be a good idea to add a helper method that could detect if the passed query is "normal" or "IC". Basically, `return 'combinator' in query` hidden behind a method, just to make it easier for users.
2. `convertFromIC` puts the `combinator` key at the bottom of each rule object, instead of at the top. Technically it doesn't matter, as the object is still the same, but visually is a little bit more confusing if one is trying to "parse" the query visually.
3. Maybe also export `convertFromIC` and `convertToIC`? That way if `1` also gets implemented, users will be able to detect non-IC query and convert them to IC only when required (or maybe they'd like to export an existing query back to non-IC format, just in order to keep backwards compatibility). Personally I'm not a huge fan of overloaded methods that return different stuff depending on what the input was, but that's really just a personal taste. If all 3 functions get exported, everybody will be happy.

**Comment by jakeboone02** [comment]
OK, 1 and 3 are implemented. `convertFromIC` and `convertToIC` as well as `isRuleGroupType` and `isRuleGroupTypeIC` are all exported now.

As for 2, this is return statement for `convertFromIC`:

```ts
  return { ...processedRG, combinator, rules };
```

The `combinator` comes before the rules, so I think what you're seeing has something to do with the way `JSON.stringify` orders object properties. I've noticed in the past that the `combinator` and `not` properties appear below the `rules` when using `JSON.stringify`. I agree it's not as visually intuitive but I don't think there's anything we can do about it short of writing our own `stringify` method.

**Comment by alexandernst** [comment]
Great!! Then it all looks good to me :) 

Ready to 🚢

**Comment by alexandernst** [comment]
Btw, should I expect the 4.2.0 soon or do you have in mind adding more stuff?

**Comment by jakeboone02** [comment]
[v4.1.2](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.1.2) 🚀
