### ISSUE TITLE
queryString export is missing

### ISSUE THREAD

**Issue by amaleszewski** [react-querybuilder/react-querybuilder#273]
Hello! I have a question. Is there a possibility to add `queryString` export option? I need it at most, because I can OOTB make from it a query to SQL database using Entity Framework (.NET on backend). I don't want to pass SQL nor parametrized SQL, because it makes a vulnerability of passing a SQL injection attack.

Example of what I expect from similar library to yours: https://github.com/ukrbublik/react-awesome-query-builder#querystring-immutablevalue-config-isfordisplay--false---string

Kind regards,
Adrian

**Comment by jakeboone02** [comment]
Hi, @amaleszewski. I'm struggling to understand the "why" of the `queryString` output format. It doesn't seem to be any standard format I've ever come across. Some sort of pseudo-SQL, maybe? How does that help with either storage or execution of queries?

Can you describe your particular use case? The `formatQuery` function is fairly versatile, and we can add other export formats if there's demand for them.
