### ISSUE TITLE
The fieldSelector as a controlled component is not working

### ISSUE THREAD

**Issue by vidyashreen1991** [react-querybuilder/react-querybuilder#285]
On changing the field is not updating the value in the query

https://github.com/react-querybuilder/react-querybuilder/issues/285#issue-1149185085

**Comment by jakeboone02** [comment]
Hi @vidyashreen1991, can you provide a codesandbox or other reproduction of the issue? Feel free to use [this](https://codesandbox.io/s/react-query-builder-starter-template-1t0gnn?file=/src/App.tsx) as a starting point.

**Comment by vidyashreen1991** [comment]
Here is the exact issue what we are facing.
Once after adding 3 rules, if we remove the second one, third rule is getting removed

https://codesandbox.io/s/react-query-builder-starter-template-forked-ktdlvb?file=/src/FieldSelector.tsx

**Comment by jakeboone02** [comment]
There were two problems with your custom `FieldSelector` component: 1) there was no `key` prop defined for the looped `<option>` elements, and 2) there was no `value` prop on the `<select>` element.

Fixed version [here](https://codesandbox.io/s/react-query-builder-starter-template-forked-otz6hi?file=/src/FieldSelector.tsx).
