### ISSUE TITLE
'RuleGroupType' is not exported from 'react-querybuilder'

### ISSUE THREAD

**Issue by brianbattenfeld** [react-querybuilder/react-querybuilder#286]
Installed and followed Basic Usage, but getting 
`Attempted import error: 'RuleGroupType' is not exported from 'react-querybuilder'.`

Component contents below:

```
import React from "react";
import QueryBuilder, { RuleGroupType } from 'react-querybuilder';
import {
  bootstrapControlClassnames,
  bootstrapControlElements,
} from '@react-querybuilder/bootstrap';

const fields = [
  { name: 'firstName', label: 'First Name' },
  { name: 'lastName', label: 'Last Name' },
];

const Reporting = (props) => {
  const [query, setQuery] = useState < RuleGroupType > ({
    combinator: 'and',
    rules: [],
  });

  return <QueryBuilder fields={fields} query={query} onQueryChange={q => setQuery(q)} />;

}

export default Reporting;
```

**Comment by jakeboone02** [comment]
Hi, @brianbattenfeld. I copied your code into [this codesandbox](https://codesandbox.io/s/react-query-builder-286-rfozfk?file=/src/Reporting.tsx). To make it work, all I had to do was add `import { useState } from 'react'`. I also applied the Bootstrap `controlElements` and `controlClassnames` props.

If you can reproduce the exact error somewhere like codesandbox or stackblitz or where ever, that would be helpful.

**Comment by brianbattenfeld** [comment]
my project was is not using typescript, and that appears to have been the root of this problem.

**Comment by jakeboone02** [comment]
Ah, that makes sense.
