### ISSUE TITLE
export google common expression language

### ISSUE THREAD

**Issue by dzmitry-lahoda** [react-querybuilder/react-querybuilder#291]
nice to see this project allows me SQL and json (in various subforms). and it is clear that will not support all databases possible

But, it would be awesome to see performance and security-sensitive export into https://github.com/google/cel-spec  https://github.com/google/cel-go . it supports in/exists/has but is limited to being fast (probably its regex are also only linear forward to avoid perf attacks too) . 

Used by https://www.krakend.io/ 

Afaik people can edit it visually later https://github.com/hmarr/vscode-cel

If https://github.com/react-querybuilder/react-querybuilder should be limited to issue only supported by CEL, ok to have such limit (so interesting to see limits to be set on query builder).

alternative? parse json/sql export from builder and transpile it into CEL.

seems CEL because of pefromance and security can be used in feature gates, routing, a/b testing, proxies.

will donate for it 3 DOT.

**Comment by jakeboone02** [comment]
Hi, @dzmitry-lahoda. I'm not 100% sure what you're requesting here. Is it to provide a CEL-compatible export format? Or to limit the structure of rules to those allowed by CEL?

Also, looks like this is Go-centric for now? They [explicitly rule out a JavaScript implementation](https://github.com/google/cel-go#why-not-javascript-lua-or-wasm).

**Comment by dzmitry-lahoda** [comment]
1. target cel. cel is less powerfull than sql. that may require adding restriction to editor to make sure if user chooses cel, he does not click on incompatible buttons. 
2. they ruled out running wasm or js vm to be used as rule engine. wasm and js are turing complete and that is security risk for cel use cases. cel interpeters exist for go, java, rust. i think may be there is written lib in ts too. so it is not go centric but security and predictable  perfomance centric. sql also not that kind of.

so export cel is requested.

**Comment by dzmitry-lahoda** [comment]
they ruled out running js code as rule engine, but not that implementing runner in wasm or js.

**Comment by dzmitry-lahoda** [comment]
p

**Comment by jakeboone02** [comment]
So would there be two requests, one for a CEL export, and another for an option to limit the functionality of the query builder such that the rules don't violate the CEL spec? Maybe an `enforceCEL` boolean prop or something like that?

(Also, did you close this issue on purpose? Feel free to reopen it if that was an accident.)

**Comment by dzmitry-lahoda** [comment]
hh6

**Comment by dzmitry-lahoda** [comment]
oh. sorry. my pocket closed issue. yeah. export is best. restricting i less needed and more simpler to do.

**Comment by dzmitry-lahoda** [comment]
and yes. i researched several market products for feature gates. seems cel looks best to beat launchdarkly as market leader(it has no secure hiearchical and/or). it lacks query builder:) (they have some ugly flat rules not so composable)

**Comment by jakeboone02** [comment]
This looks like it wouldn't be too much work, as long as we only try to support a reasonable subset of the CEL spec. This library isn't great at handling things like functions (`f(x)`) and maps (`{ k: v }`) yet, but lists (`[a, b]`) are probably doable.

**Comment by dzmitry-lahoda** [comment]
the bare minimum is awesome I guess. it will be ♾️ better than nothing:) . function and maps are not so needed (or it can be commercial extensions for enterprise)

**Comment by jakeboone02** [comment]
I've been searching around for as many examples of CEL as I can find, and either my google-fu is failing me or there just aren't a lot of examples of CEL in the wild. The language spec is ok, but it doesn't really show CEL _in action_.

I think I can translate basic rules pretty easily, like these:

<table>
<thead><tr><th>react-querybuilder rule</th><th>CEL</th></tr></thead>
<tbody>
<tr><td><code>{ field: "f", operator: "=", value: "v" }</code></td><td><code>f == "v"</code></td></tr>
<tr><td><code>{ field: "f", operator: "beginsWith", value: "v" }</code></td><td><code>f.startsWith("v")</code></td></tr>
</tbody>
</table>

But I'm struggling to find examples of how to represent the inverse of the `contains`/`beginsWith`/`endsWith` operators (i.e. `doesNotContain`/`doesNotBeginWith`/`doesNotEndWith`) in CEL.

`in` and `notIn` operators would probably translate to the `list` type in CEL, but I can't figure out how to represent that as an expression like `f in ["a", "b", "c"]`. Maybe that's even correct, but I can't find a way to actively validate CEL or just a simple working example. (A fallback would be to create a new parenthetical group like `(f == "a" || f == "b" || f == "c")`, but that's a little weird if a `list`-based syntax works.)

`between` and `notBetween` seem to be unsupported natively, so I would have to split those into two rules like `(f >= x && f <= y)`.

Do you have any CEL examples I could look at?

**Comment by dzmitry-lahoda** [comment]
I saw some descriptions of the language in the go codebase, but not samples.

I found some examples in java tests
https://github.com/projectnessie/cel-java/blob/main/core/src/test/java/org/projectnessie/cel/parser/ParserTest.java


as per grammra, it seems that 


https://github.com/thesayyn/cel-js/blob/71b8280b57cac113930724d20c892ef8b349975f/src/parser/gen/CEL.g4#L49

```
f.startsWith("v")
```
is 
```
!f.startsWith("v")
```
for negation (see grammar)

<img width="673" alt="image" src="https://user-images.githubusercontent.com/757125/160353588-3e224ae7-d29b-48dd-b8ed-ed02982df56c.png">

**Comment by dzmitry-lahoda** [comment]
list example with in https://github.com/projectnessie/cel-java/blob/b64de4e41d66a07888c7d9262735bf909915ff8c/core/src/test/java/org/projectnessie/cel/parser/ParserTest.java#L1028

**Comment by dzmitry-lahoda** [comment]
between - yeah, seems >= <=

more tests https://github.com/google/cel-cpp/blob/master/parser/parser_test.cc (so these looks similar to java version)

**Comment by dzmitry-lahoda** [comment]
https://cloud.google.com/iam/docs/configuring-resource-based-access 

(just googled https://www.google.com/search?q=iam+OR+RBAC+OR+ABAC+cel&oq=iam+OR+RBAC+OR+ABAC+cel&aqs=chrome..69i57.13555j0j1&sourceid=chrome&ie=UTF-8)

**Comment by jakeboone02** [comment]
Awesome! Thanks so much for finding those. Looks like I was right with the `list` syntax after all. I'll use `!` for negation and break `between`/`notBetween` into two rules, and that should cover everything we currently support.

**Comment by jakeboone02** [comment]
This is now merged into the `main` branch. I'll publish v4.2.3 with the new functionality later today.

**Comment by jakeboone02** [comment]
[Published](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.2.3)!

**Comment by dzmitry-lahoda** [comment]
where i can send 3 DOT?:)

**Comment by jakeboone02** [comment]
You're very kind! First time I'm doing this...let's see if this works:

```
1N92QyTh8GWobMnJsCPec8aTxcyb1nMAxSwG8ym9JWDe8Y5
```

**Comment by dzmitry-lahoda** [comment]
found CEX to get DOT. in process :)

**Comment by dzmitry-lahoda** [comment]
should happend:
```
We have received a withdrawal request for 9.000000 DOT to the wallet
Address: 1N92QyTh8GWobMnJsCPec8aTxcyb1nMAxSwG8ym9JWDe8Y5 |
```

```
Withdrawal details:
Instrument: Crypto
Requested amount: DOT 9.000000
Commission: DOT 0.100000
```

**Comment by jakeboone02** [comment]
Confirmed receipt! Thanks again!
