### ISSUE TITLE
add rule-builder tag

### ISSUE THREAD

**Issue by dzmitry-lahoda** [react-querybuilder/react-querybuilder#292]
https://ui-patterns.com/patterns/rule-builder

**Comment by jakeboone02** [comment]
Are you asking that a `"rule-builder"` tag be added to the [npm package page](https://www.npmjs.com/package/react-querybuilder)? If so, you could open a PR to add that to the `keywords` field in [package.json](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/react-querybuilder/package.json).

**Comment by dzmitry-lahoda** [comment]
oh, on github page.

**Comment by dzmitry-lahoda** [comment]
but package could be too

**Comment by jakeboone02** [comment]
Added to the GitHub page. Thanks for the suggestion!
