### ISSUE TITLE
Unable to generate SQL query using between & not between operator

### ISSUE THREAD

**Issue by rvprasadreddy** [react-querybuilder/react-querybuilder#297]
I am not able to generate SQL query for all operator except "between" & "not between" operators.  As when we select between/not between   operators then query is not adding the operator and inputed value in text box.

Please guide me to use/configure rightly if i am missing someting.

**Comment by jakeboone02** [comment]
See [the "automatic validation" documentation](https://react-querybuilder.js.org/docs/api/export#automatic-validation).

When a rule uses the `"between"` or `"notBetween"` operator, the SQL-based export formats will skip the rule if it doesn't evaluate to two elements. This is done in an attempt to avoid generating invalid SQL.

The rule's `value` must either be an actual array with exactly two elements, or a string that, when `split` by a comma character, becomes an array with two non-empty strings.

For example, if the text box value is any of the following strings, the rule will be skipped:

- `""`
- `"1"`
- `"1,"`
- `",2"`

The following values, by contrast, *will* generate SQL `BETWEEN` clauses:

- `[1, 2]`
- `"1, 2"`
