### ISSUE TITLE
adding subfileds 

### ISSUE THREAD

**Issue by syama-aot** [react-querybuilder/react-querybuilder#299]
Recently i started working on react-querybuilder, we need sub filed inside one label . Is it possible

Like -- profileReview 
          Under this --- > I need 2 more labels like initial screening, etc

**Comment by jakeboone02** [comment]
Hi, @syama-aot. Can you elaborate a little? I'm not exactly sure what you're requesting.

The documentation site has a few [tips and tricks](https://react-querybuilder.js.org/docs/category/tips--tricks) that may help.

**Comment by syama-aot** [comment]
Thanks for your reply. I got it
