### ISSUE TITLE
Is there any support of adding multi range slider 

### ISSUE THREAD

**Issue by syama-aot** [react-querybuilder/react-querybuilder#307]
It was an immense pleasure to work with your library.

Is it possible to add a multi-range slider to the library? 

I have my custom multi-range slider component. But I am unable to add that to your library.

Can you provide me with a sandbox with a multi-range slider example?

**Comment by jakeboone02** [comment]
Multi-value sliders aren't available as native HTML5 inputs, so I wouldn't want to add it to the base library. Are you using one of the compatibility packages? I might consider adding it to those. 

Can you point me to an example implementation of the slider you would like to use?

**Comment by syama-aot** [comment]
I have used this sandbox for multi range slider

https://codesandbox.io/embed/multi-range-slider-react-js-ecwcr?fontsize=14&hidenavigation=1&theme=dark&view=preview

**Comment by jakeboone02** [comment]
You got that component from [this article](https://dev.to/sandra_lewis/building-a-multi-range-slider-in-react-from-scratch-4dl1), right? I think there are a few things wrong with it, like setting state inside a `useEffect` hook. I would recommend using a different component.

I found [react-ranger](https://github.com/tannerlinsley/react-ranger), which has hooks for making your own range slider. [Here is an example](https://codesandbox.io/s/react-query-builder-with-multi-range-slider-0jb0cp?file=/src/App.tsx) using `react-ranger` in a custom `ValueEditor`.
