### ISSUE TITLE
Issue with Search Params URL in multi select

### ISSUE THREAD

**Issue by AnwinShaji** [react-querybuilder/react-querybuilder#309]
Hi,

While I'm using multiselect, I cannot set rules.value[ ] in search params. I tried to get this values with map function also. But in URL I'm getting it as object+object.

**Comment by jakeboone02** [comment]
Can you provide a reproduction, perhaps on CodeSandbox? You can use [this template](https://codesandbox.io/s/1t0gnn) as a starting point.

**Comment by jakeboone02** [comment]
You might take a look at the [query-string package](https://www.npmjs.com/package/query-string).

**Comment by AnwinShaji** [comment]
Thank you for providing this
