### ISSUE TITLE
Is it possible to add all my filters in url search params 

### ISSUE THREAD

**Issue by syam5492009** [react-querybuilder/react-querybuilder#310]
Suppose if I add locations multi select , I want to use all values in search params like locations=india,sa,us,..etc&firstname=raj&exp=4 
When I refresh the page , I want to load the filter query with all search params values.

**Comment by jakeboone02** [comment]
We use the [query-string package](https://www.npmjs.com/package/query-string) to manage the hash values in the [demo](https://react-querybuilder.js.org/react-querybuilder/) ([code here](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/demo/src/main.tsx#L115)). I'm not sure how well it would handle a deeply nested JSON object like an RQB query, but that's where I would start if I were you.
