### ISSUE TITLE
how can I set the date picker format?

### ISSUE THREAD

**Issue by jeacott1** [react-querybuilder/react-querybuilder#314]
Hi,
 is it possible to set a custom date format in the date/time picker? I think all the pickers available have an option, but I'm not sure how to set it when using react querybuilder

thanks.

**Comment by jakeboone02** [comment]
Hi, @jeacott1. Are you looking to modify the date format for the `ValueEditor` component from one of the [compatibility packages](https://react-querybuilder.js.org/docs/compat), or the default `ValueEditor`?

The compatibility components have their own requirements and limitations, but if you're just using the default components with `inputType: "date"`/`"time"`/`"datetime-local"` on a field, that format is determined by the [HTML5 spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date). (You can see the actual values that are stored in the rule `value` property for the various value editor configurations on [this page](https://react-querybuilder.js.org/docs/api/valueeditor#showcase).)

You'd need to set up a custom value editor to use a different format. [This page has an example](https://react-querybuilder.js.org/docs/tips/custom-with-fallback) that uses `react-datepicker` which can accept custom date formats.

**Comment by jeacott1** [comment]
@jakeboone02 thank you! I'm just looking to handle different input formats for different regions so I think the default editor is plenty. thank you for the refs.

**Comment by jakeboone02** [comment]
Great! If you're set for now, want to close this issue?
