### ISSUE TITLE
Clear all button needed

### ISSUE THREAD

**Issue by anwin-aot** [react-querybuilder/react-querybuilder#322]
Hi @jakeboone02 ,

In my project I'm using react-querybuilder. I need a "clear all" button to remove all the filters I'm used. If I used 10 filter, I need to use close button for 10 times to clear all filters for now. Can you please update me on this?

**Comment by jakeboone02** [comment]
Does the button need to be on the query builder itself, or can it be outside? If the former, you could augment one of the standard components to show a "clear all" button in addition to the normal one. If the latter, you could render a button that resets the query to `{combinator:"and",rules:[]}` in its `onClick` handler.

**Comment by anwin-aot** [comment]
Thanks @jakeboone02 . I will check

**Comment by anwin-aot** [comment]
Thank you for your prompt response. @jakeboone02
