### ISSUE TITLE
MUI buttons are primary instead of secondary

### ISSUE THREAD

**Issue by mhuggins** [react-querybuilder/react-querybuilder#325]
The MUI theme buttons (+RULE, +GROUP) render using variant "contained", making them appear as the primary action on the page.  This style should be reserved for the main button on a given page or form (e.g.: the submit action for creating a query after interacting with QueryBuilder).  Could these buttons be rendered using variant "outlined" instead, which is in line with secondary actions on a page?

Alternatively, is there a way to override this today?

**Comment by jakeboone02** [comment]
Yes, you can override this today as of [v4.3.1](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.3.1). It would work something like this:

```tsx
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { MaterialActionElement, materialControlElements } from "@react-querybuilder/material";
import { ActionWithRulesProps, Controls, QueryBuilder } from "react-querybuilder";
import "react-querybuilder/dist/query-builder.css";

// Proxy for MaterialActionElement with `variant` override
const CustomActionElement = (props: ActionWithRulesProps) => (
  <MaterialActionElement {...props} variant="outlined" />
);

// All the Material* components, overriding with our proxy component where appropriate
const controlElements: Partial<Controls> = {
  ...materialControlElements,
  addGroupAction: CustomActionElement,
  addRuleAction: CustomActionElement,
  cloneGroupAction: CustomActionElement,
  cloneRuleAction: CustomActionElement,
  lockGroupAction: CustomActionElement,
  lockRuleAction: CustomActionElement,
  removeGroupAction: CustomActionElement,
  removeRuleAction: CustomActionElement,  
};

const muiTheme = createTheme();

export function App() {
  return (
    <ThemeProvider theme={muiTheme}>
      <QueryBuilder controlElements={controlElements} />
    </ThemeProvider>
  );
}
```

Do you think I should change the default variant to "outlined"? I certainly see the argument--none of those buttons are really the _primary_ button on a page. Even if they are, the user can override the variant as shown above. I guess let me know how strongly you feel about it.

By the way, another user raised #321 a few days ago which alerted us to the bug where a custom theme config doesn't get passed down to the RQB components (they always have the default theme). I've been trying to address it in #324, but so far haven't been able to get the theme to propagate down to the MUI components. Any help or direction would be appreciated!

**Comment by mhuggins** [comment]
Oh this is great, thanks so much @jakeboone02!  I haven't played much with themes at all in MUI, but as I get a bit more comfortable, I'll share whatever I can that might help.  Really appreciate all the work on this package/component, it's great!
