### ISSUE TITLE
Errors when Component Testing with Cypress v10.1.0

### ISSUE THREAD

**Issue by carlevans72** [react-querybuilder/react-querybuilder#326]
When running Cypress component tests we get the following error which causes the test suite to crash:

ERROR in ../../node_modules/react-querybuilder/dist/query-builder.css
No template for dependency: ModuleHotAcceptDependency

client (webpack 5.69.1) compiled with 1 error in 10334 ms
##[error]The operation was canceled.

**Comment by jakeboone02** [comment]
Hmm. I've run Cypress tests with RQB before, but it was a while ago. Could you link to a demo repo?

**Comment by carlevans72** [comment]
Hi,

I'll try pull something together and get it over to you.  Weird thing is it passes on my local machine with no issues and only fails when running in Azure pipeline.

This is using the latest version of Cypress (v10.1.0) and the component testing beta.  I presume you haven't tried running Cypress tests with RQB with the latest version that dropped a couple of weeks ago?

We have a monorepo consisting several Next.js apps and the Cypress tests I'm running are on an app that don't use react-querybuilder.  Your package is in a common components library that is bootstrapped into the app I'm trying to use Cypress on.

It'll take me a while to pull together an exact demo repo.

Thanks,
Carl.

**Comment by jakeboone02** [comment]
> This is using the latest version of Cypress (v10.1.0) and the component testing beta. I presume you haven't tried running Cypress tests with RQB with the latest version that dropped a couple of weeks ago?

No, it's actually been a couple of years since I touched the Cypress tests at my day job. So whatever version they were at back then, that's what we still use.

**Comment by jakeboone02** [comment]
@carlevans72 - I was going back through this and saw that you mentioned NextJS, so this issue may be the same as #340. Did you ever figure out a workaround?

**Comment by carlevans72** [comment]
Hey @jakeboone02 

So, this ended up being an issue with Next.js when using Cypress component testing.

Next.js only allowing importing of global styles in `pages/_app.js` - when component testing with Cypress you also need to import your styles in `cypress/support/component.ts`.

Using Cypress 10.5.0 and a package called `next-global-css` you can get around this issue.

We had RQB in our component library originally and it was being bootstrapped into the project I was working on (although not used by said project).  We removed RQB from the component library and then I started to get the same issue with our own stylesheets.

So, this was never related to RQB you'll be glad to hear.

**Comment by jakeboone02** [comment]
Thanks for following up!
