### ISSUE TITLE
Replacing filedselector with navbar 

### ISSUE THREAD

**Issue by syam5492009** [react-querybuilder/react-querybuilder#327]
I am very happy to use this library. I want a custom component for FieldSelector which supports menu kind of approach as follows
Schedules ---> when I  click on schedules I need to display sub items under that , in sub items I have a country selection also.
Is it possible to have nestable dropdown with expanding and collapse

**Comment by jakeboone02** [comment]
Hi @syam5492009, I'm glad you like the library. There are a few ways to go about this.

## Filtered field selector

I created [this codesandbox](https://codesandbox.io/s/react-querybuilder-enhanced-field-selector-xx97y?file=/src/App.tsx) in response to the question posed in #263. It adds a selection drop down list to the left of the rule components that filters the values available in the field selector. You could have it list the sub items, then have the field selector list the filtered countries (if I'm understanding you correctly).

## Option groups

The [`fields` prop](https://react-querybuilder.js.org/docs/api/querybuilder#fields) can accept `OptionGroup<Field>[]` instead of a flat `Field[]`. The option groups become `<optgroup>` elements within the field selector. So instead of this:

```tsx
<QueryBuilder fields={[{ name: "f1", label: "Field 1" }]} />
```

you would do this:

```tsx
<QueryBuilder fields={[{ label: "Group 1", options: [{ name: "f1", label: "Field 1" }] }]} />
```

The result is

![image](https://user-images.githubusercontent.com/366438/173641424-abfd347e-2f91-41ca-a6ce-c3bb19f554e2.png)

## React Select

If your use case is more complicated, I would suggest using something like [`react-select`](https://react-select.com/) to build a custom `fieldSelector` component. If (1) or (2) don't fit your requirement, try to elaborate on the specifications and I can provide some sample code. (Edit: #184 has some example code using `react-select`, see https://github.com/react-querybuilder/react-querybuilder/issues/184#issuecomment-872408667)

**Comment by syam5492009** [comment]
I need a component which similar to this sandbox. 
https://codesandbox.io/embed/2y1u5?codemirror=1
But its not working properly 
Can you provide me the updated solution (codesandbox) -if possible. 
because i need filed2 & name inside rule section.

**Comment by jakeboone02** [comment]
Are you asking for something similar to #332?

**Comment by syam5492009** [comment]
Thanks for your reply. But following is my requirement.

1. Important ---> under this group I have 2 items --> a. Bookmarked
b.rating
If I select rating item, it needs to show another select box  to select
various skills.
But for Bookmarked,  I have to show operator select box directly

**Comment by syam5492009** [comment]
I need the above requirement . is it possible

**Comment by jakeboone02** [comment]
In short, yes. I'm sure what you are describing is possible, but I have a few questions about your requirements before I can provide working code.

Is the skill selection attached to the operator or the field? If the field, then your `fields` array could look like this:

```ts
const fields: Field[] = [
  {
    name: "bookmarked",
    label: "Bookmarked",
  },
  {
    name: "rating-1",
    label: "Rating 1",
  },
  {
    name: "rating-2",
    label: "Rating 1",
  },
];
```

You could have a custom `fieldSelector` that rendered a single, hard-coded select with "Bookmarked" and "Rating" labels, but also showed another select when one of the "rating-_x_" fields was selected that allowed the user to choose _which_ rating. You would use the `onHandleChange` callback to set the value to "rating-1" or "rating-2" if the second select was visible, or set it to "bookmarked" if it wasn't.

Your requirement could also be interpreted as the standard operator select needing to disappear when "rating" was selected as the field. If that is the case, you can use the `operators` property of the "Rating" field like this:

```ts
const fields: Field[] = [
  {
    name: "rating",
    label: "Rating",
    operators: [
      { name: "rating-1", label: "Rating 1" },
      { name: "rating-2", label: "Rating 2" },
    ],
  },
];
```

If you need nested/dependent field or operator selection, keep in mind that you can actually use more complex data structures in the query. `field` and `operator` are encouraged to be strings (and somewhat forced by TypeScript), but there's nothing stopping you from storing an array or object type value in each rule. You just have to have a custom `fieldSelector`, `operatorSelector`, or `valueEditor` to handle the special case.

**Comment by syam5492009** [comment]
Thanks for quick response.

const fileds= [{
`label`: `bookmarked`,
`group`: `others`,
value:[],
},
{
`label`: `rating`,
`group`: `ratings`,
}]

once I select the rating label I need to show all rating skills like react,
Node, etc in another select box as a field , because I need to  show
minimum  100 skills .

Based on that, operator needs to select

**Comment by jakeboone02** [comment]
I'm sorry, I can't really see any new information in your last comment except for the "100 skills" bit which introduces yet another complexity.

> const fileds= [{ `label`: `bookmarked`, `group`: `others`, value:[], }, { `label`: `rating`, `group`: `ratings`, }]

If this is what you're using for the `fields` prop, it's missing the required `name` attribute for each field.

**Comment by syama-aot** [comment]
> I have provided you the sample , i have given name attribute also

I want to show  [{
          // id: "008",
          name: "ReviewStatus",
          label: "Profile Review Status",
          group: "Others",
          // value: false,
          valueEditorType: "select",
          values: [
            { label: "Pending", name: "pending" },
            { label: "In Progress", name: "in_progress" },
            { label: "Completed", name: "completed" },
            { label: "Failed", name: "failed" },
          ],
          operators: [
            { name: "=", label: "is" },
            // { name: "!=", label: "!=" },
          ],
        },
        {
          name: "Skill Rating",
          label: "Skill Rating",
          group: "Others",
          operators: [{ name: "in", label: "in" }],
        }],

When i select skill Rating , I need to show available skills(nodejs,reactjs, android. etc) -- select box 
after selection of required skill, I need to show the operator (=, > ,<)

**Comment by syam5492009** [comment]
> 

Please provide me codesandbox which supports the above functionality . Thanks

**Comment by syam5492009** [comment]
[](url)
I need as follows
![skillrating](https://user-images.githubusercontent.com/16044664/174645149-e78489cf-8838-4a75-856c-44f7ba3cb873.PNG)

**Comment by jakeboone02** [comment]
https://codesandbox.io/s/uzo4lv

**Comment by syama-aot** [comment]
Thanks a lot.

**Comment by syam5492009** [comment]
Thanks for providing the solution. when i try to use with react-select I am facing an issue . can you update the same sandbox with react-select.
Thanks in advance

**Comment by jakeboone02** [comment]
https://codesandbox.io/s/c6fcfx

**Comment by syam5492009** [comment]
> https://codesandbox.io/s/c6fcfx

Can you help me convert this code with AsyncSelect instead of normal select

**Comment by jakeboone02** [comment]
@syam5492009 I think a `react-select`-specific support channel (or StackOverflow, etc.) would be a better place for that question.

**Comment by syama-aot** [comment]
Thanks for your email. Let me give an example to retrieve *rating options
(nodejs,reactjs..etc)* when I select *skillRating* from the dropdown menu
instead of having it as* static content as we mentioned in fields array
(skillRating|nodejs). *

**Comment by jakeboone02** [comment]
> Thanks for your email. Let me give an example to retrieve *rating options (nodejs,reactjs..etc)* when I select *skillRating* from the dropdown menu instead of having it as* static content as we mentioned in fields array (skillRating|nodejs). *

@syama-aot I think a `react-select`-specific support channel (or StackOverflow, etc.) would be a better place for that question.
