### ISSUE TITLE
Fieldselector to multilevel dropdown

### ISSUE THREAD

**Issue by anwin-aot** [react-querybuilder/react-querybuilder#329]
Hi @jakeboone02 ,

I'm using react querybuilder in my project. It saves lot of my time. Is it possible to replace fieldselector with multilevel dropdown. 

Eg:
Location
Number-->1
                   2
Symbol  >

Inside filedselector, I needs to display group name and not grouped list. While clicking or hovering on a group name another level of dropdown needs to display with the list under that group.  Some what similar to screenshot below

![Screenshot 2022-06-14 103428](https://user-images.githubusercontent.com/96901218/173717220-979ee0e8-dd2d-47bf-9a79-9c3f59c17918.png)

**Comment by jakeboone02** [comment]
You would need to use a custom `fieldSelector` component. The only "select" library I'm really familiar with is react-select, which may or may not do what you want, but it can definitely be incorporated into a custom RQB component.

After googling for "react-select collapsible groups" I found [this article](https://www.chintanradia.com/blog/react-select-collapsible-group/).

If you need some sample code, let me know.

**Comment by anwin-aot** [comment]
Sure, thank you. Let me go through this article

**Comment by anwin-aot** [comment]
Hi @jakeboone02 ,

I was going through  https://codesandbox.io/embed/2y1u5?codemirror=1 After selecting "field 2"  from first select box, and select a value from second select box, library is not returning second select box seleted value.

![image](https://user-images.githubusercontent.com/96901218/173814650-8fc56874-1625-46fd-a0d2-75ce3d2b4910.png)
