### ISSUE TITLE
Custom component for FieldSelector

### ISSUE THREAD

**Issue by anwin-aot** [react-querybuilder/react-querybuilder#332]
Is it possible to create fieldSelector as follows

![image](https://user-images.githubusercontent.com/96901218/174070624-f4b731dc-0c41-4756-8e9e-ddc00f1e0fc9.png)

**Comment by jakeboone02** [comment]
I found [`@szhsin/react-menu`](https://www.npmjs.com/package/@szhsin/react-menu) which does submenus. (I thought `react-select` did, but it looks like you may have to use a custom Option component.)

Implementation here: https://codesandbox.io/s/react-querybuilder-field-selector-nested-menus-rl3mif?file=/src/index.tsx.

**Comment by anwin-aot** [comment]
Hi @jakeboone02 ,

Thanks a lot for providing this. This is helping me a lot and saving my time.
