### ISSUE TITLE
Properly support "between" operator for `valueSource: "field"` in default `ValueEditor`

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#333]
> > The reason it doesn't support that is because RQB would need to become more opinionated, and I don't really want to go down that path
>
> Ahh got it, thanks for bearing with me, makes total sense. This… actually leaves me a bit uncomfortable? In that, the UI allows users to build something that is silently ignored.

_Originally posted by @fasiha in https://github.com/react-querybuilder/react-querybuilder/issues/215#issuecomment-1146446614_

Requirements:

- `ValueEditor` should display two drop-down lists when operator is "between" or "notBetween" and `valueSource` is "field".
- The `value` should be stored as a comma-separated string (e.g. `"f1,f2"`).

Questions:

- Should the default `ValueEditor` include a separator of some kind between the two drop-downs, like "and" or ","?
  - Should it be translatable?
  - Should it be stylable (have standard classnames)?
  - What would the default styles be?
- When a value (i.e. field) is selected in one drop-down list, should it not be available in the other list? This would prevent rules like "f1 between f2 and f2". Maybe we could handle that with validation, or skip those rules in `formatQuery`.
- What to do if there are less than two qualifying fields to populate the drop-downs? If one, maybe we just allow it. If zero...(what happens when there are no qualifying fields for other operators?)
- Should `valueSource: "value"` rules also have two inputs? Respecting `inputType: "number"`, etc.?

**Comment by fasiha** [comment]
Whew, definitely one of those things that sound easy but are fractally complicated—as usual your attention to detail stands out!

I don't want to discourage from spending the time needed to find the global optimum in terms of features/behaviors but given that the library currently doesn't work (appears to accept `between` for fields but outputs no rules), I wonder if doing the minimum to fix it—while also keeping with the standard set by the rest of the library—might be advisable. If so, that'd mean:
- no separator between the two dropdowns (but, low-hanging fruit: do give the dropdowns unique classnames so CSS can add `before` and `after` content?)
- no other validation on the content of the dropdowns
- `valueSource:'value'` continues behaving as is

And see how that makes you feel?

**Comment by jakeboone02** [comment]
That's _excellent_ feedback. Thanks! TBH I think I'm just going to implement your suggestions as written. I'll throw a PR together soon.

**Comment by jakeboone02** [comment]
OK so this ballooned a little but I think it's for the best. See PR #337.

When I started working on handling the "between" operator for `valueSource: "field"`, I realized RQB could handle "between" rules with `valueEditorType: "select"` (regardless of the `valueSource`) with the same code. So that was a nice surprise.

I also added an optional `boolean` prop to `<QueryBuilder />` called `listsAsArrays`. This works similarly to the [`parse*` option of the same name](https://react-querybuilder.js.org/docs/api/import#lists-as-arrays). When `true`, rules that have operators which take a list of values ("between", "in", and their "not" counterparts) will update the `value` property with an actual array, like this:

```ts
const query = {
  combinator: "and",
  rules: [
    {
      field: "f1",
      operator: "between",
      value: ["f2", "f3"], // <--
      valueSource: "field",
    },
  ],
};
```

The default behavior will stay the same, using comma-separated strings:

```ts
const query = {
  combinator: "and",
  rules: [
    {
      field: "f1",
      operator: "between",
      value: "f2,f3", // <--
      valueSource: "field",
    },
  ],
};
```

Strings now properly handle escaped characters, too, like commas. For example, RQB will ignore the escaped comma when splitting a value of `"this\, that, the other"`, splitting it into `["this, that", "the other"]`. Joining will do the same in reverse. (I also made provisions for splitting by a different character than a comma. I didn't actually add a new prop to implement that option yet, but I might later.)

As for styling: when two or more inputs are displayed by `ValueEditor` (currently only applicable for "between" and "notBetween"), they will each have the class "rule-value-list-item". The default CSS will add a `margin-left` of the standard spacing amount, `0.5rem`, to the second input (and any subsequent ones, if we eventually support "in"/"notIn" in the same way).

I’d love to see what you think of the changes. #337 has links to codesandboxes that implement the new features so you can try them out without cloning/installing/etc.
