### ISSUE TITLE
Add/Control multiselect input field 

### ISSUE THREAD

**Issue by adnanjalloh** [react-querybuilder/react-querybuilder#345]
Hi all, 

How to add/control multi-select(tags) input in fields ?

Many thanks for considering my request.

**Comment by jakeboone02** [comment]
Hi @adnanjalloh! I'm on vacation right now with intermittent Internet access, but I can give you a more complete answer next week.

In the meantime, check out the [documentation on custom components](https://react-querybuilder.js.org/docs/tips/custom-with-fallback).

You’ll probably want to look at using [react-select](https://react-select.com) for a tag-based multiselect. Keep in mind that the `value` property of a rule can be anything including an array, object, primitive...whatever.

(There’s a multiselect example on [this page](https://react-querybuilder.js.org/docs/api/valueeditor), but it’s a standard HTML select and not tags.)

**Comment by adnanjalloh** [comment]
Many thanks 👍
