### ISSUE TITLE
live demo is broken

### ISSUE THREAD

**Issue by brietsparks** [react-querybuilder/react-querybuilder#35]

**Comment by Reemh** [comment]
It would be helpful if someone can provide a working link to demo please. The link the in the current link http://www.webpackbin.com/410SaYgPG doesn't work.

**Comment by pavanpodila** [comment]
Thanks for @brietsparks and @Reemh for pointing this out. I finally got around to fixing this. You can now see the demo at: https://sapientglobalmarkets.github.io/react-querybuilder/

The README has also been updated. Closing it.
