### ISSUE TITLE
Documentation mentions findNode which was previously removed

### ISSUE THREAD

**Issue by toridyar** [react-querybuilder/react-querybuilder#351]
The documentation mentions a findNode method which seems to have been removed at some point

**Comment by jakeboone02** [comment]
I think you're referring to `findRule`, which was [removed in v4.0.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.0.0) in favor of [`findPath`](https://react-querybuilder.js.org/docs/api/misc#findpath). Is there a feature you need?

**Comment by toridyar** [comment]
Yes, that's correct, the ReadMe still mentions findRule in a couple places but it was removed. It would be great to have findRule added back, but if the documentation could be updated to match current version that would work too. thx

**Comment by toridyar** [comment]
Also it seems that findPath is a state behind? Using find path returns the group but the new rule that needs to be updated hasn't been added to rules - although the actual query has the new rule added in rules

**Comment by jakeboone02** [comment]
Are you referring to the [v3.12.1 README](https://github.com/react-querybuilder/react-querybuilder/blob/main/README.v3.12.1.md)? That's the only place [I could find "findRule" in the repo](https://github.com/react-querybuilder/react-querybuilder/search?q=findRule). That file mentions at the top that it's for an older version of the library, and has a link to the [current documentation site](https://react-querybuilder.js.org/). (Although I _did_ find [one reference](https://react-querybuilder.js.org/docs/api/querybuilder#onaddrule) to `findRule` in the current documentation, so I'll remove that soon.)

The implementation of `findRule` was very simple. [This is the latest version](https://github.com/react-querybuilder/react-querybuilder/blob/v3.12.1/src/utils/findRule.ts) before it was removed. I don't want to add it back but the code should still work with v4 queries. It was a standalone function anyway so feel free to use it as is.

As for your other question about `findPath` being behind, that's not really the way to look at it. `findPath` itself is just looking at the query passed to it, there is no statefulness. What you might be referring to is the query passed from `<QueryBuilder />` to the `onAddRule` callback. As noted in [the documentation](https://react-querybuilder.js.org/docs/api/querybuilder#onaddrule), that query is the query _before_ the rule gets added. This way you can abort the rule addition by returning `false`.

Hope that helps!

**Comment by jakeboone02** [comment]
> (Although I _did_ find [one reference](https://react-querybuilder.js.org/docs/api/querybuilder#onaddrule) to `findRule` in the current documentation, so I'll remove that soon.)

Removed in https://github.com/react-querybuilder/react-querybuilder.github.io/commit/beca3066cf36045f12779631a6d4aafacce68b4f. Closing this issue.
