### ISSUE TITLE
Custom input element loses focus after any character entered when it wrapped into QueryBuilderDnD

### ISSUE THREAD

**Issue by Egor3842** [react-querybuilder/react-querybuilder#362]
I use custom component for input element.
When I use this component:
`<QueryBuilder
        fields={fields as any}
        query={query}
        onQueryChange={(q: any) => setQuery(q)}
        controlElements={{
          fieldSelector,
          operatorSelector,
          combinatorSelector,
          valueEditor,
          notToggle,
          addRuleAction,
          addGroupAction,
          removeGroupAction: removeAction,
          removeRuleAction: removeAction,
        }}
        controlClassnames={{}}
        operators={operators}
        combinators={combinators}
      />`
It runs correct.
But when I wrapped this component into <QueryBuilderDnD> and add enableDragAndDrop parameter focus on my input element lost.

**Comment by jakeboone02** [comment]
Hi @Egor3842, thanks for the bug report. This is for the v5 alpha release, right?

The two packages that now use dynamic imports, `@react-querybuilder/dnd` and `@react-querybuilder/material`, both have some major issues that I'm currently working on. Once I have something to show, I'll link to the PR here.

**Comment by Egor3842** [comment]
Thanks a lot
