### ISSUE TITLE
Problem with jsonlogic type and operator "between ,"not in" and "not between"

### ISSUE THREAD

**Issue by Egor3842** [react-querybuilder/react-querybuilder#366]
I use custom rangeDate component and I need to export field's object as jsonlogic. I have two dates and operator "between" and it exported like `{"<=":["2022-09-22",{"var":"date"},"2022-09-28"]}`. When I import this rule to query builder with parseJsonLogic it gives me operator: "<=" and only first value, second value lost. What can I do with it? Moreover if I used "not between" in rule, it gave me a group, which has notToggle:"true" and operator:"between". I need to disable notToggle and take back operator:"not between". The same problem with "not in". How can I get it?

**Comment by Egor3842** [comment]
I use custom rangeDate component and I need to export field's object as jsonlogic. It exported like `{"!":{"in":[{"var":"date"},["2022-09-06","2022-09-16"]]}}`. When I import this rule to query builder with parseJsonLogic it gives me operator: "in" and "notToggle": true. I need to disable notToggle and take back operator:"not in". How can I get it?

**Comment by jakeboone02** [comment]
Hmm, that's a good question. Without looking at the code, I'm guessing `parseJsonLogic` naively assumes the `"!"` operator should always translate to `not: true` on the group. [JsonLogic](https://jsonlogic.com/operations.html) doesn't have "not between" or "not in" operators per se, but maybe I can make the parsing logic smarter when the group is negated, the rule's operator would evaluate to `"between"` or `"in"`, and there's only rule in the group.

**Comment by jakeboone02** [comment]
I noticed you changed this issue from your original question about custom operators, and maybe you figured it out on your own but I thought it would be good to address. You have two options, really.

1. Customize the `label` property only, using the standard `name`s in your operators/combinators
2. Use [`transformQuery`](https://react-querybuilder.js.org/docs/api/misc#transformquery) to translate the operators/combinators in a query object from your custom `name`s to the defaults (and back again, if necessary)

For option 1, note that the `name` is not what appears to the user, so it can generally be left alone. The `label` is what the user sees. I would recommend something like this:

```js
const operators = [
  { name: '=', label: 'Равно' }, 
  { name: '<', label: 'Меньше чем X дней' },
  { name: '>', label: 'Больше' }
];

const combinators = [
  { name: 'and', label: 'И' },
  { name: 'or', label: 'Или' }
];
```

This will keep the `formatQuery` and `parse*` functions working as expected, but displays the translated text to the user.

For option 2, you can customize the `name`s as well and provide maps of the custom `name`s to the defaults to `transformQuery` , like this:

```js
const operatorMap = {равно: '=', меньше: '<', больше: '>' };
const combinatorMap = {и: 'and', или: 'or'};

const query = {
  combinator: 'и',
  rules: [
    { field: 'f1', operator: 'равно', value: 'v1' },
    { field: 'f2', operator: 'больше', value: 9000 },
  ]
};

const standardQuery = transformQuery(query, { operatorMap, combinatorMap });
/*
{
  combinator: 'and',
  rules: [
    { field: 'f1', operator: '=', value: 'v1' },
    { field: 'f2', operator: '>', value: 9000 },
  ]
}
*/
```

`standardQuery` conforms to the interface `DefaultRuleGroupType`, which is really what `formatQuery` and friends need to work properly.

**Comment by Egor3842** [comment]
Thanks a lot for answering, yeah I used your first variant of viewing my operators and it will be great if you will add logic to “not” operators(may be add condition to builder like `if notToggle does not allow-make a rule with negative operator instead of group with false toggle`, it can partly resolve problem.  But I have another question about operator “between”. I export my rule in JsonLogic like `{"<=":["2022-09-22",{"var":"date"},"2022-09-28"]} ` but then I import it again it transforms in `{"<=":[{"var":"date"},"2022-09-22"]} ` and I lost last value, moreover operator “between” replaced on “<=“.  I use react date picker for range date and save my values as array of two dates. I saw your example where operator "between" and jsonlogic parser work correct with rangeDate picker if I stay my dates as string like   `{"<=":[{"var":"date"},"2022-09-22,2022-09-28"]} ` ( https://react-querybuilder.js.org/docs/tips/custom-with-fallback ) but it breaks condition logic, isn't it?

**Comment by jakeboone02** [comment]
Confirmed, it doesn't handle "between" correctly in v4.5.2. This will be fixed in v5.

(You're right about `{"<=":[{"var":"date"},"2022-09-22,2022-09-28"]}` being incorrect JsonLogic syntax.)

[Here's a CodeSandbox test for verification](https://codesandbox.io/s/exciting-panka-wzvt51?file=/src/App.test.ts). Update that to the next v5 alpha release or v5 final to check.

**Comment by Egor3842** [comment]
I'm sorry, but I didn't fully understand. Is this issue already resolved in v5 (e.g. v5.0.0-alpha.3) or will it be fixed in the future?

**Comment by jakeboone02** [comment]
Oh, sorry, I wasn't clear. `v5.0.0-alpha.3` (and `v5.0.0-alpha.5`, for that matter) has the same issue. It will be fixed in `v5.0.0-alpha.6` if that version gets published, but definitely in the final `v5.0.0`. I'll have a PR soon that has it fixed and I'll link it to this issue.

**Comment by Egor3842** [comment]
okey, thank you very much for your prompt replies and your efforts)

**Comment by jakeboone02** [comment]
@Egor3842 - I believe PR #367 fixes the issues with "between" and "in". It also converts the substring operators ("contains" / "beginsWith" / "endsWith") to their negating counterparts ("doesNotContain" / "doesNotBeginWith" / "doesNotEndWith") if a single rule is wrapped in `{ '!': ... }`.

You can try out the query->JsonLogic and JsonLogic->query transformations based on the code from #367 with [this codesandbox](https://codesandbox.io/s/react-querybuilder-ci-forked-290uqu?file=/src/App.tsx).
