### ISSUE TITLE
If I need to customize the field selector, how to pass the value type of each field to the valueEditor

### ISSUE THREAD

**Issue by ZhaoQianQian977** [react-querybuilder/react-querybuilder#371]
I have now customized a field selector with cascading selection components, but I don't know how to pass the value type of the selected field to the valueEditor, so that the valueEditor can automatically match the corresponding input type, or my customized valueEditor can display different components according to the passed value type. Is there any related api

**Comment by jakeboone02** [comment]
Hi @ZhaoQianQian977, did you figure out how to do what you needed?

**Comment by ZhaoQianQian977** [comment]
> Hi @ZhaoQianQian977, did you figure out how to do what you needed?

I implemented my custom field selector in another way. Through field transfer, the valueEditor can still get the desired field value type, and the custom fieldSelector can also render cascade selectors with more fields. At present, it seems to be the most convenient  method

**Comment by jakeboone02** [comment]
Great. Let me know if you think there should/could be a _more_ convenient way!

**Comment by ZhaoQianQian977** [comment]
> 

Thank you for taking the time to reply to my message. I will contact you again if necessary
