### ISSUE TITLE
Trying to parseSQL with character '-' returns empty rules array

### ISSUE THREAD

**Issue by evakratalov** [react-querybuilder/react-querybuilder#383]
Hi @jakeboone02,

i'm trying to parse expression with parseSQL and getting result with an empty rules array (a key with '-' character).
expression: "(somthing-somthing = '')"
result: {rules: Array(0), combinator: 'and'}
will appreciate your help..

**Comment by jakeboone02** [comment]
Can you tell me what SQL dialect you're using? Normally identifiers like that have to be quoted with double quotes (e.g. Oracle) or backticks (e.g. MySQL).

**Comment by evakratalov** [comment]
Im using js with expression "(test-test = '')" which im trying to parse with parseSQL.
I tried also double quotes `("test-test" = '')` and single quotes, but still getting an empty rules array.

```
const expression = "(test-test = '')";
const parsedExpression = parseSQL(expression); // getting result { rules: Array(0), combinator: 'and' }
```

**Comment by jakeboone02** [comment]
Can you try it with backticks, like this?

```ts
parseSQL("(`test-test` = '')")
```

**Comment by evakratalov** [comment]
it works! thank you for the help

**Comment by jakeboone02** [comment]
Great! Want to close this issue?
