### ISSUE TITLE
Type not picking valueEditorType from field definition

### ISSUE THREAD

**Issue by apuntovanini** [react-querybuilder/react-querybuilder#384]
It seems that global default getValueEditorType overrides field definition of valueEditorType

```
const fields = [
  {
      id: 'test',
      name: 'Foo',
      valueEditorType: 'checkbox'
  }
]
```

is still passed as `type: 'text'` to ValueEditor.
It works only if I use global getValueEditorType on QueryBuilder component

**Comment by apuntovanini** [comment]
Ok, forget it, sorry, I was using the wrong id/name in custom controls
Using the alpha version btw, upgrade from v.4 was seamless so far, thank you!

**Comment by jakeboone02** [comment]
> Using the alpha version btw, upgrade from v.4 was seamless so far, thank you!

Thanks for the feedback!
