### ISSUE TITLE
Wrong rules generated when you switch to another field with different operators

### ISSUE THREAD

**Issue by kamtschatka** [react-querybuilder/react-querybuilder#39]
I am using the queryBuilder with a list of fields that have different operators depending on the type(i have strings, numbers and dates).
When I switch from a String field to a number field, the operators are updated using the getOperators function, but the rule itself will still contain the old value.

Sample:
I select a field "name"(String) that allows the operators "equals", "startswith" and "endswith" and select the field "timestamp"(number) that allows the operators "=", "<", ">", then the rule will switch the field to "timestamp", but the operator will stay at "equals".

**Comment by krishan-carbon** [comment]
this issue still exists.. any way to get the PR reviewed?

**Comment by miphe** [comment]
@krishan-carbon I'll have a look asap.

**Comment by jakeboone02** [comment]
@krishan-carbon / @kamtschatka - does this issue still exist in v2.0.0?

**Comment by bartvanremortele** [comment]
I can confirm that this issue still exists. The PR #63 would fix this but it was closed as fixed already.

**Comment by jakeboone02** [comment]
Closing due to age.  Note that the `resetOnFieldChange` (`true` by default) and `resetOnOperatorChange` (`false` by default) props enable the user to configure the desired behavior.
