### ISSUE TITLE
Error when parsing null values in JsonLogic

### ISSUE THREAD

**Issue by megaflo** [react-querybuilder/react-querybuilder#393]
We stumbled over what I think is a bug in the parsing code for JsonLogic: When formatting a query with a `null` or `nonNull` check to JsonLogic via `formatQuery` and then parsing it later via `parseJsonLogic` the parsing will fail with a `TypeError`. See https://codesandbox.io/s/naughty-bird-z8mux8?file=/src/App.js for an example.

I think the underlying issue is that `parseJsonLogic` cannot handle `null` values, even though such values are introduced by `formatQuery`. I think the queries produced by that function are correct and instead `parseJsonLogic` should be able to handle un-/equality checks with `null` values.

**Comment by jakeboone02** [comment]
I've opened #394 with the fix. Can you try the [CodeSandbox it generated](https://codesandbox.io/s/affectionate-euler-3622n7)? It's a copy of the one you linked to but uses the `react-querybuilder` build from the PR.

**Comment by megaflo** [comment]
Wow, that was quick. I played around with the sandbox and also tried out the changes in our original use case and it's working perfectly now.
Thanks for handling this so quickly and for your work on this project.

**Comment by jakeboone02** [comment]
My pleasure! Thanks for the kind words.

**Comment by jakeboone02** [comment]
This fix is included in [v5.1.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v5.1.0).
