### ISSUE TITLE
Publish as CJS/ESM; drop UMD

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#396]
**Update 2023-02-14**: v6 will still publish CJS and ESM, but will drop UMD.

~Publish all packages as ESM only. Add the following to the changelog:~

> - ~All packages published from this repository are now built as [ES modules only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). You may continue to use `react-querybuilder` and any of the compatibility packages in a CommonJS environment by using the latest v5.x release.~

~**Question**: what about UMD?~

**Comment by anar-latifov** [comment]
I guess same here, getting `Can't import the named export 'ActionElement' from non EcmaScript module (only default export is available)` when trying to use mui
