### ISSUE TITLE
Can we use NameLabelPair with numeric names?

### ISSUE THREAD

**Issue by fasiha** [react-querybuilder/react-querybuilder#397]
Hi Jake, this is a super-low-impact question, and I'm guessing there's a really simple solution that I'm just too dense to see right now. I often have a field where I want the user to choose for a list of options, so `valueEditorType: 'multiselect'` or `select`, and then I have an array of `values` of type `NameLabelPair[]`.

See https://codesandbox.io/s/cranky-ully-u7vntp?file=/src/App.tsx for an example.

The question is, what do you do when you want the `name` part of the pair to be numeric? In the example above, I try to force numeric `name`s via `as any` but the output query (in `json` or `jsonlogic` format) has for example `["0"]`, RQB being smart enough to convert incorrectly-typed `NameLabelPair`s values into strings.

![image](https://user-images.githubusercontent.com/37649/200976724-04b35026-993e-4307-8f98-497e467118c0.png)

The reason this would be nice is, I have some data that's going to be evaluated against this query, it has a well-known format, and its `state` key (which is being compared here) is a number. I could stringify that key of the object before calling JsonLogic to run on it, but ideally I'd be able to avoid editing the data.

Is there something short of a custom rule or component that can let me represent the case where I want my multiselect to get a collection of numbers? Thanks! Forgive me if this a question you've answered elsewhere and I didn't see it!

**Comment by jakeboone02** [comment]
Hi @fasiha, yes there is a way to do this. Use the `parseNumbers` option in `formatQuery` like this:

```ts
formatQuery(query, { format: 'jsonlogic', parseNumbers: true })
```

Documentation is [here](https://react-querybuilder.js.org/docs/api/export#parse-numbers).

Result is like this for your example:

![image](https://user-images.githubusercontent.com/366438/201182869-6a52fd51-d0bb-4c68-94d9-d88e9a733000.png)

**Comment by fasiha** [comment]
Superb, thank you Jake! Apologies, I don't know how I missed that 🙇!
