### ISSUE TITLE
dndOver class should not be applied to child rule group headers

### ISSUE THREAD

**Issue by mxcapo** [react-querybuilder/react-querybuilder#399]
When a rule group has a rule group as a child, dragging a rule in the parent rule group applies the `.dndOver` class to the child rule group headers. This results in the `.dndOver` styling being applied to elements that are not the intended drop target. You can see the effect in the [demo](https://react-querybuilder.js.org/demo#addRuleToNewGroups=false&autoSelectField=true&autoSelectOperator=true&debugMode=false&disabled=false&enableDragAndDrop=true&independentCombinators=false&justifiedLayout=false&listsAsArrays=false&parseNumbers=false&resetOnFieldChange=true&resetOnOperatorChange=false&showCloneButtons=false&showCombinatorsBetweenRules=false&showLockButtons=false&showNotToggle=false&validateQuery=false) screenshot below.

To reproduce, open the demo link above (enables drag-and-drop). Add some nested rules and rule groups. Drag a rule onto the header of a rule group that has rules and rule groups as children. 

Expected: the `.dndOver` class is applied only to the header under the cursor

Actual:

<img width="800" alt="Screen Shot 2022-11-17 at 5 50 54 PM" src="https://user-images.githubusercontent.com/7275188/202598564-d0ecd3be-11f1-45cd-b10b-bef96564af84.png">

**Comment by jakeboone02** [comment]
Good catch, and thanks for all the info! I'll see if I can get a fix for this published tomorrow.

**Comment by jakeboone02** [comment]
@mxcapo can you try out the CI demo build for PR #401? Link is here: https://codesandbox.io/s/react-querybuilder-ci-hih9df. That should have the issue resolved. I'll release a patch as soon as I can after you give it a 👍.
