### ISSUE TITLE
Can't import the named export 'ActionElement' from non EcmaScript module

### ISSUE THREAD

**Issue by anar-latifov** [react-querybuilder/react-querybuilder#404]
Hello everyone, I faced with this issue, after just installing the `react-querybuilder` and `@react-querybuilder/material`

I getting error: `Can't import the named export 'ActionElement' from non EcmaScript module (only default export is available)` 

i using cra with react 18 , react scripts 4 and mui 5

**Comment by jakeboone02** [comment]
Hi @jokopain, can you reproduce this issue with a CodeSandbox, StackBlitz, or GitHub repo? The [MUI example](https://github.com/react-querybuilder/react-querybuilder/tree/main/examples/material) seems to work fine.

**Comment by jakeboone02** [comment]
Closing due to lack of response.
