### ISSUE TITLE
Cannot move rule to first position if current first-position rule is locked

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#407]
If the first rule in a group is locked, the component does not allow another rule to be dropped onto the group header (which would normally move the dropped rule to the first position and shift the first rule to the second position).

Similarly, if the last rule in a group is locked, no other rules can be dropped on it to move them to the last position. This one makes more sense, but...

I'm not sure if this needs to be changed. If a rule is locked, should its position in the group also be locked?

If anyone sees this and has an opinion on the matter, please share it.

**Comment by sneakytowelsuit** [comment]
I think this behavior makes sense, if a rule is locked in a particularly complex set of rules locking it would prevent the user from making changes to it they don't intend. I see this actually being useful to lock groups and since they can be nested N levels deep it might be nice to guarantee you can't accidentally mess them up while building rules elsewhere.

**Comment by jakeboone02** [comment]
Thanks for your input, @Austin-Stowe!

I'm thinking that if one intends to lock the position of rules, then they should lock the group they're in instead of the rules themselves. Locking a rule, to me, means "you can't update the properties of this rule." But the _position_ of those rules within the group is (again, to me) a property of the _group_.

That said, I don't think we should go so far as to allow dragging/moving locked rules, but I think I'm going to change the logic to allow dropping enabled rules above and below locked rules.

**Comment by sneakytowelsuit** [comment]
Putting it that way it makes a lot of sense. 

Locking a group locks properties of the *group*, which is defined by the collection of rules it contains.

Locking a rule locks properties of the *rule*, **except** when independent combinators are used then it locks *that rule and the combinator immediately preceding it*.

This logic makes perfect sense to me and further delineates the difference between a rule and a group. 

With regards to the drag-and-drop, that would affect the group composition but I can see an argument that the position of a rule is a property of the rule within the context of the group so locking a rule prevents changing that as well. I do agree that rules should be allowed to be moved around it though, obviously so long as the parent group isn't locked.
