### ISSUE TITLE
`showCombinatorsBetweenRules` bug: combinator is locked when rule below it is locked

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#411]
When `showCombinatorsBetweenRules` is enabled, the combinator selector above a locked rule/group will also be locked.

**Comment by sneakytowelsuit** [comment]
This makes sense for independent combinators to me, but for `showCombinatorsBetweenRules` that's a good catch. I haven't dug too deep into the logic on this, but would a check for the rule being disabled and independent combinators suffice?

**Comment by jakeboone02** [comment]
This one was a simple fix ([diff here](https://github.com/react-querybuilder/react-querybuilder/commit/20e9c175ff9859b68cc0996fef4bc8deb53841bc#diff-77d3b960ea8130321c4217a229bf7dc6e86185e6034ed6467ed651aec6634e09)). Just needed to key off the `disabled` property of the group itself instead of the child rule/group.
