### ISSUE TITLE
How to check for the length property with JsonLogic

### ISSUE THREAD

**Issue by gj1118** [react-querybuilder/react-querybuilder#415]
Hi, 
Sorry for coming back with another question please. My bad. 

Here is my use case. 
I have a JSON obejct. I am using [json-logic-fs](https://github.com/jwadhams/json-logic-js) to apply the query formatted as `jsonlogic` against my object. So far it works with the text fields. 

What I also want to do is filter out the items which dont have children items inside . For example please see the following json object 

```
{
 "name" : "Category of the post",
"posts": [ {"id" : 1 , "title" : "my first post"}]
},
{
 "name" : "Another post category",
"posts": []
}
```

I have the current fields set up as such

```
const fields = [
  { name: 'name', label: 'Category Name' },
  {
    name: 'posts',
    label: 'Has posts',
    valueEditorType: 'checkbox',
  },
];
```

What I would really like to do is to generate a query that will filter out categories which do not have any post, i.e categories which have posts field length is 0, will be filtered out. 

The existing default operators wont help, I presume as I cannot use them to check for the length of an array.

Is there a way I can create a `length` operator and use it to filter categories which have the posts length as 0. 

Sorry for a lengthy question. 

Thanks once again for your time and patience. 

With Regards
Gagan

**Comment by jakeboone02** [comment]
Is the `length` filter something that you want to be able to produce dynamically from the query builder, or something static that you would add to each JsonLogic filter unconditionally?

If it's static, you can register a [custom operation](https://jsonlogic.com/add_operation.html) with `jsonLogic.add_operation` and manipulate the JsonLogic object you get from `formatQuery` to use the custom operation.

If it's something you need to have as an operator in RQB, you'll still need to add the custom operation before you `apply` the JsonLogic filter, but you can also use the [`ruleProcessor` option](https://react-querybuilder.js.org/docs/api/export#rule-processor) in `formatQuery` to produce the rule you need. If you need a specific example let me know, but the [documentation page](https://react-querybuilder.js.org/docs/api/export#rule-processor) actually already has a good JsonLogic example.

**Comment by gj1118** [comment]
@jakeboone02 an example would be nice , kind Sir. I appreciate all help . 

Thanks,
Gagan

**Comment by jakeboone02** [comment]
I think this does something like what you want: https://stackblitz.com/edit/github-2vj3ih-urvyv3?file=src/App.tsx

Check and uncheck the checkbox on the default "Has posts" rule to see how the data is filtered differently.

**Comment by gj1118** [comment]
You are godsend.. Thanks a lot .. it worked perfectly. Thank you once again. Much much appreciated. This is the first time, I am seeing such kind of support from the author of a very popular component. thanks once again. ❤️

**Comment by jakeboone02** [comment]
I don't know about "very popular" but thank you for the kind words!
