### ISSUE TITLE
`ValueEditor` should display two inputs when `operator` is "between" or "notBetween"

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#428]
From discussion #427.

Questions:

- Should there be a separator, like "and"? So it would read as "Field between X and Y" instead of just "Field between X Y". If so:
  - Should it be a full-blown component or just a translatable string?
  - What class(es) should be added by default?
  - Should it be hidden by default, or "" instead of "and"?
  - Should it be configurable by field?
- Is the `listsAsArrays` prop enough to manage the way the `handleOnChange` prop is called from within the default component?
  - Do we need a `parseNumbers`-ish prop for `<QueryBuilder />` that attempts to set `value` to a number?

Similar enhancements (plus add/remove controls for a dynamic list of value editors) are needed for "in"/"notIn".

**Comment by keerthankrishna** [comment]
This is my thought..

- If "between" is used 2 text input boxes would get rendered next to each other having a class that is customizable. Maybe, it can take the same class style as **rule-value** (_but have a different name like **rule-between-value** ?_)
- The seperator like "**and**" could be used in the SQL or other query outputs but instead of taking comma seperated values, it will take values from the 2 text input boxes. If the "and" is used (_Field between X and Y_), it will be as close as possible to query language rather than using _Field between X Y_
- I'm not sure what you mean by full-blown component and translatable string here
- I would assume it should show "" by default and when user inputs the values in the 2 input text boxes, it will render the "and" and show the values
- I would say, it should be configurable by field

I am still thinking about the answers for the last 2 questions.

**Comment by jakeboone02** [comment]
I started PR #431 that implements the two-input variation for the default `ValueEditor` (and the Bootstrap counterpart as well...others to come later) when the operator is "between" or "notBetween".

You can try out the new build here: https://codesandbox.io/s/react-querybuilder-pr-431-test-cyj6rp?file=/src/App.tsx

As to your questions:

> * If "between" is used 2 text input boxes would get rendered next to each other having a class that is customizable. Maybe, it can take the same class style as **rule-value** (_but have a different name like **rule-between-value** ?_)

The wrapper element has the `rule-value` class, and each input has the `rule-value-list-item` class. The new class is named that in case we consider adding support for "in"/"notIn" later.

> * The seperator like "**and**" could be used in the SQL or other query outputs but instead of taking comma seperated values, it will take values from the 2 text input boxes. If the "and" is used (_Field between X and Y_), it will be as close as possible to query language rather than using _Field between X Y_

I added a `getValueEditorSeparator` prop which takes a `field` and `operator` and should return a `ReactNode` (element, string, etc.) that gets inserted in between the two inputs. Usage:

```
<QueryBuilder
  getValueEditorSeparator={(fld, op) => "and"}
/>
// OR
<QueryBuilder
  getValueEditorSeparator={(fld, op) => (<span className="my-class">and</span>)}
/>
```

> * I'm not sure what you mean by full-blown component and translatable string here

I went with "component"--see previous bullet.

> * I would assume it should show "" by default and when user inputs the values in the 2 input text boxes, it will render the "and" and show the values

It's not dynamic, it either displays for the given field/operator combination or it doesn't.

> * I would say, it should be configurable by field

...and operator! :)

Have a go with the [CodeSandbox](https://codesandbox.io/s/react-querybuilder-pr-431-test-cyj6rp?file=/src/App.tsx) and let me know what you think.

**Comment by keerthankrishna** [comment]
This looks perfect.. I will play around a bit with the CodeSandbox version you created. Thank you so very much @jakeboone02 !

**Comment by AagamPragma** [comment]
Hey @jakeboone02 . This is the same feature that I have been looking for. I wanted to change the value field based on operator selected and wanted to know if this feature is something that can be done manually now till you figure out when to go ahead with this release officially (Live).

**Comment by keerthankrishna** [comment]
@jakeboone02 - This was deployed to v6 on Jan 09th right ?

**Comment by jakeboone02** [comment]
> @jakeboone02 - This was deployed to v6 on Jan 09th right ?

I don't remember when it was originally published but yes, it's in v6. See #455.
