### ISSUE TITLE
Feature Request: Customize-able position of combinator dropdown

### ISSUE THREAD

**Issue by shreyase10** [react-querybuilder/react-querybuilder#43]
![image](https://user-images.githubusercontent.com/22481121/30903568-de4ad72c-a38c-11e7-8bd8-b3241856483c.png)

Hello - Our use case requires us to have the combinator selector between the rules as opposed to before them, would it be possible to add the position as a config option so that we can tweak it?
Please see the image for reference. 

Here, a selection in one of the dropdowns would also change selection in other dropdowns within the same group.

**Comment by jakeboone02** [comment]
@plcpunk - See PR #96.  Would that meet your need?
