### ISSUE TITLE
Calling multiple onPropChange only applies the  last one

### ISSUE THREAD

**Issue by unrealsolver** [react-querybuilder/react-querybuilder#439]
Consider this snippet:
```
onPropChange('combinator', value, path); // Will be ignored
onPropChange('not', Boolean(not), path); // Will have effect
```
Here, the first `onPropChange` call will be ignored and only `not` will be updated. Changing the order of calls also changes behavior to opposite.
Expected: Calling `onPropChange` sequentially should update all props.

**Comment by jakeboone02** [comment]
While this is the intended behavior, I do see the value in being able to change multiple properties at once. (This particular design decision was made before my time.)

However, can you explain your use case for a custom `Rule` component? If you can meet your requirements without a custom component, that's usually recommended (especially in the case of `Rule` and `RuleGroup`).

**Comment by unrealsolver** [comment]
So, I tried to combine 'combinator' and 'not' options into single one dropdown with Venn diagram icons. Basically, 'AND', 'AND NOT', 'OR', 'OR NOT'. It's not super important for me, just nice to have to make some A/B UX testing if it will work for my purpose.
I figured out why does it work this way, and I don't think there is an easy way to change that behavior anyway.

**Comment by jakeboone02** [comment]
Have a look at [this codesandbox](https://codesandbox.io/s/upbeat-dust-01bs9c?file=/src/App.tsx). It implements custom `combinators` and exports a modified query ([courtesy of `transformQuery`](https://react-querybuilder.js.org/docs/api/misc#transformquery)) that converts the combinators from the custom values to standard "and"/"or" and adds `not: true` or `not: false` to the group appropriately.

**Comment by unrealsolver** [comment]
This will definitely work, thanks!
