### ISSUE TITLE
Feature Request: React Native Compatibility 

### ISSUE THREAD

**Issue by enchorb** [react-querybuilder/react-querybuilder#450]
React Native uses different rendering elements (Text, View, Flex, Button). Through the use of a library like Native Base, would be very cool/useful if this could compile on React Native as no such library exists for it.

**Comment by jakeboone02** [comment]
That sounds like a great idea! Do you know of any examples of other libraries that support RN? I've had minimal exposure to RN so I wouldn't really know where to begin.

**Comment by jakeboone02** [comment]
@enchorb I just released [v6.0.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.0.0) with React Native compatibility. See the [official compatibility package](https://www.npmjs.com/package/@react-querybuilder/native) and the [example](https://github.com/react-querybuilder/react-querybuilder/tree/main/examples/native).
