### ISSUE TITLE
onquerychange not triggered when deleting last rule of query

### ISSUE THREAD

**Issue by tommueller** [react-querybuilder/react-querybuilder#454]
If I delete the last rule of my query, the onquerychange hook does not seem to be triggered.

**Comment by jakeboone02** [comment]
Can you reproduce the issue in a CodeSandbox?

You can use [this example](https://github.com/react-querybuilder/react-querybuilder/tree/main/examples/basic-ts) as a template.

**Comment by tommueller** [comment]
Sorry, was a problem with my code, not the querybuilder.
