### ISSUE TITLE
parseJsonLogic is not returning correct query when trying to parse a rule with only a notIn operator

### ISSUE THREAD

**Issue by kyaruntsdavit** [react-querybuilder/react-querybuilder#457]
Steps to reproduce:

1. Construct the following rule with the query builder:
`{
    "combinator": "and",
    "rules": [
        {
            "id": "052b6212-fac1-4aa3-9721-f6a3ec9fbd3b",
            "field": "platform",
            "operator": "notIn",
            "valueSource": "value",
            "value": [
                "1",
                "2",
                "3"
            ]
        }
    ],
    "id": "f0b29b0a-d4e3-46ab-bd62-1a7a61d8d1a4"
}`

2. Parse the query to JsonLogic with the following function:
`formatQuery(query, 'jsonlogic')`

3. The output will be
`{
    "!": {
        "in": [
            {
                "var": "platform"
            },
            [
                "1",
                "2",
                "3"
            ]
        ]
    }
}`

4. Parse the jsonLogic back to the query with following function:
`parseJsonLogic({
    "!": {
        "in": [
            {
                "var": "platform"
            },
            [
                "1",
                "2",
                "3"
            ]
        ]
    }
})`

5. The output will be the following:
`{field: 'platform', operator: 'notIn', value: '1,2,3', valueSource: undefined}`

6. Try to format the output back to jsonLogic or try to import it:
`formatQuery('{field: 'platform', operator: 'notIn', value: '1,2,3', valueSource: undefined}', 'jsonLogic')`

Expected result:
The parseJsonLogic should return the query properly

Actual result: 
The following error is thrown:

> Uncaught TypeError: Cannot read properties of undefined (reading 'length')

**Comment by jakeboone02** [comment]
Thanks for the bug report! Looks like it fails to wrap the rule result in a group object in some cases.

How urgent is this for you? I ask because I'm working on version 6 and it isn't quite ready yet, but I can probably put out a v5.4.1 patch fairly quickly if you really need it.

**Comment by jakeboone02** [comment]
FYI the same problem exists when the operator is "notBetween".

**Comment by jakeboone02** [comment]
@kyaruntsdavit I just published [v5.4.1](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v5.4.1) with this issue resolved.

**Comment by kyaruntsdavit** [comment]
@jakeboone02 thank you very much for solving this. Sorry, I was away for a long time and did not have a chance to react to your messages.

**Comment by jakeboone02** [comment]
No problem! Happy to help.
