### ISSUE TITLE
https://codesandbox.io/s/c6fcfx

### ISSUE THREAD

**Issue by syam5492009** [react-querybuilder/react-querybuilder#461]
https://codesandbox.io/s/c6fcfx

_Originally posted by @jakeboone02 in https://github.com/react-querybuilder/react-querybuilder/issues/327#issuecomment-1161326703_
Thanks for your wonderful response.           
Now i got a new issue while making the second component i mean( ratingSelectOptions) as AsynSelect(instead of select). How can i achieve this. Can you help me with this.
Thanks in advance.

**Comment by syam5492009** [comment]
https://codesandbox.io/s/c6fcfx

Can you help me convert this code with AsyncSelect instead of normal select

**Comment by jakeboone02** [comment]
See https://github.com/react-querybuilder/react-querybuilder/issues/327#issuecomment-1431663753
