### ISSUE TITLE
Failed to compile - Attempted import error: 'QueryBuilderContext' is not exported from '@react-querybuilder/ctx'.

### ISSUE THREAD

**Issue by danst3in** [react-querybuilder/react-querybuilder#466]
Attempting to upgrade from version 3.9.9 to 6.0.0 and running into several issues with typescript and other breaking changes, and working through them 1 by 1. Currently stuck on this compile error:

```
Failed to compile.

./node_modules/react-querybuilder/dist/index.mjs
Attempted import error: 'QueryBuilderContext' is not exported from '@react-querybuilder/ctx' (imported as 'Xt').
```

Using `node v16.16.0`, `npm: '8.11.0',`

`package-lock.json`
```
"node_modules/react-querybuilder": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/react-querybuilder/-/react-querybuilder-6.0.0.tgz",
      "integrity": "sha512-SCgPU6iDuXxsICA6lw/D+Wl5YqWIpFK4vEVX4SmKrw6oW7S/UrA3kGIQD8yesbFd5kZlyo4TQ4gcix3BjSB+bg==",
      "dependencies": {
        "@react-querybuilder/ctx": "^6.0.0",
        "@react-querybuilder/ts": "^6.0.0",
        "clsx": "^1.2.1",
        "immer": "^9.0.19"
      },
      "peerDependencies": {
        "react": ">=16.8.0"
      }
    },
```

Have tried deleting all node modules and reinstalling. Our project requires `npm i --legacy-peer-deps` , but not sure why that flag would be causing issues. Let me know if you would like additional info to troubleshoot and I will provide if it's within company policy.

Thanks!

**Comment by jakeboone02** [comment]
Hi, @danst3in! I think I'd probably need a minimal reproduction (GH repo, codesandbox, whatever) to know what was going on. Barring that, let me know what you're using to build your app (CRA, Vite, webpack, etc.).

**Comment by danst3in** [comment]
I'm not sure I will be able to accomplish a sandbox, but if I havbe time I will give it a shot. Looking further I am wondering if the issue is here:

`react-querybuilder/index.mjs`
```
import { QueryBuilderContext as Xt } from "@react-querybuilder/ctx";
```

`node_modules/@react-querybuilder/ctx/dist/types/index.d.ts`
```/// <reference types="react" />
import type { QueryBuilderContextProps } from '@react-querybuilder/ts';
export declare const QueryBuilderContext: import("react").Context<QueryBuilderContextProps>;
//# sourceMappingURL=index.d.ts.map
```

This is being declared as a default export in `@react-querybuilder/ctx` since there are no other exports in the file, but being imported as a {named} import. I believe you have a few options to update the `index.mjs` file:
```js
import { default as Xt } from "@react-querybuilder/ctx";
```
or
```js
import Xt from "@react-querybuilder/ctx";
```
and in `@react-querybuilder/ctx`
```js
/// <reference types="react" />
import type { QueryBuilderContextProps } from '@react-querybuilder/ts';
export declare const QueryBuilderContext: import("react").Context<QueryBuilderContextProps>;
export default QueryBuilderContext
//# sourceMappingURL=index.d.ts.map
```
ref - https://www.sharooq.com/solved-attempted-import-error-something-is-not-imported-from-some-file

I have seen indications that this is also possibly a webpack issue and in that case could be caused by us running `"react-scripts": "^4.0.1"` as opposed to something newer and using webpack 5 like `"react-scripts": "^5.0.0"`. I started having the below error after trying to make changes to the `react-querybuilder...` node_modules files locally and came upon this info.
ref - https://stackoverflow.com/questions/69343038/cant-import-the-named-export-xxxx-from-non-ecmascript-module-only-default-expo

I have yet to try and override our create react app/CRACO 4 setup, but will look into that on my end.

**Comment by jakeboone02** [comment]
I think your analysis of the default/named issue on the `ctx` package is not correct. `export declare const QueryBuilderContext [...]` is a named export, even though it's the only one. There is no default export from `ctx`. Anyway the `.d.ts` file isn't the relevant one, it's index.mjs which looks like this:

```js
import { createContext as e } from "react";
const t = e({});
t.displayName = "QueryBuilderContext";
export {
  t as QueryBuilderContext
};
//# sourceMappingURL=index.mjs.map
```

Named export only.

Webpack 5 (typically via CRA 5) has been causing a lot of issues so I'm not surprised you're having trouble with it.

**Comment by danst3in** [comment]
Thanks for taking the time to respond to my messages. I'll head down the webpack/cra 5 rabbit hole and hopefully report back with what eventually resolves it. Could be a while 😅

**Comment by jakeboone02** [comment]
Hey @danst3in, I was going to close this issue but wondered if you ever figured out the issue.

Also, I haven't actually tested it yet but I think RQB v6.4.1 will work fine with Webpack v5/CRA v5.

**Comment by danst3in** [comment]
Unfortunately the company put off our tech debt and we haven't been forced to revisit the issue. If I end up with more helpful info regarding this issue when we get back to it I can open a new issue if it seems worthwhile. Thanks
