### ISSUE TITLE
Avoid "process is not defined" error

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#472]
**UPDATE 2023-05-03**: `react-querybuilder@6.3.0` resolves this issue and adds back all the dev-mode logic to the distributed files.

**UPDATE 2023-03-02**: `react-querybuilder@6.0.3` avoids this problem by removing all the dev-mode logic from the distributed files. It includes ".development" variants of the default exports in case someone wants to use them:

```ts
import { QueryBuilder } from 'react-querybuilder/dist/index.development.mjs';
// OR
const { QueryBuilder } = require('react-querybuilder/dist/index.development.cjs');
```

---

Certain environments fail when importing RQB v6.0.2 because of the `process?.env?.NODE_ENV` checks to enable/disable development-mode warnings.

Figure out how to avoid the problem altogether, potentially by building separate dev and prod bundles.

**Comment by warjohn123** [comment]
Currently encountering this issue as well. Can someone from the team help us? Will appreciate it so much.

**Comment by jakeboone02** [comment]
Until I publish a fix, the current recommendation is to use something like `window.process = { ...window.process }`. That will make sure `process` is defined on the global scope and reassign any existing properties.

I apologize for the inconvenience! I'll fix it as soon as I figure out the best way to do it—hopefully by tomorrow.

**Comment by jakeboone02** [comment]
@warjohn123 see my update about v6.0.3 at the top of this issue.

**Comment by jakeboone02** [comment]
@warjohn123 see my update about v6.0.3 at the top of this issue.
