### ISSUE TITLE
Parse SQL with field names in square brackets

### ISSUE THREAD

**Issue by AntonMPetrov** [react-querybuilder/react-querybuilder#477]
Hello. 

My DB has tables with "-" in column names like "contoso-ISWorkOnLeave"
I can successfully query these fields or use them in a WHERE clause if I enclose the field name in square brackets.

But, When i try call parseSQL on such query : 
`SELECT *
  FROM my_table
 WHERE ([firstName] like 'Stev%' `
i got such error:

Parse error on line 3:
...OM my_table WHERE ([firstName] like 'St
----------------------^
Expecting '(', 'SELECT', 'NUMERIC', 'IDENTIFIER', 'STRING', 'EXPONENT_NUMERIC', 'HEX_NUMERIC', 'TRUE', 'FALSE', 'NULL', 'CASE', '+', '-', '~', '!', 'BINARY', 'ROW', 'EXISTS', '{', 'WILDCARD', 'NOT', 'PLACE_HOLDER', got 'INVALID'

Is there any way to avoid this erorr and parse SQL query with colummn names in square brackets?

**Comment by jakeboone02** [comment]
Yeah I should have added square bracket support to `parseSQL` when I added it to `formatQuery`. Just slipped my mind for some reason.

Anyway, thanks for bringing it up! I'll see if I can get a fix out soon.

**Comment by jakeboone02** [comment]
@AntonMPetrov the fix for this issue was included in [v6.0.4](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.0.4), released just a few minutes ago.

**Comment by AntonMPetrov** [comment]
but it still there:
![image](https://user-images.githubusercontent.com/24275608/223021402-3e4f56c6-e21f-42f1-8a6b-3aca6a4797fd.png)

**Comment by jakeboone02** [comment]
The website doesn't have the latest version yet. Will have in a couple of hours.

**Comment by AntonMPetrov** [comment]
I updated QueryBuilder in my app, but i still get this error
![image](https://user-images.githubusercontent.com/24275608/223033099-02624ff6-d109-4383-9ad5-d9895c1dcf94.png)

![image](https://user-images.githubusercontent.com/24275608/223033271-246aa31a-9aad-4448-926d-240c1c3bb3f6.png)

**Comment by AntonMPetrov** [comment]
Forgive me my obsession...
I understood what was the matter.
The formatQuery function converts Query Builder objects by extracting the field names from square brackets.
However, square brackets are required so that fields containing some characters in the name, such as "-", are successfully processed by the DBMS.

Following is the example from your updated site:
![image](https://user-images.githubusercontent.com/24275608/223155962-8e9fbc4a-4574-4ba1-9799-53b437060e4a.png)

**Comment by jakeboone02** [comment]
Ack! Sorry, I used the wrong regex for bracketed identifiers. It didn't include dashes, just alphanumeric and spaces. I'll patch it today.

**Comment by jakeboone02** [comment]
OK, [v6.0.5](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.0.5) should _actually_ resolve the issue. [Demo](https://react-querybuilder.js.org/demo) checks out from what I can tell.

**Comment by AntonMPetrov** [comment]
Yes, it's better now (does not throw an exception).
But formatQuery should not remove square brackets from field names.
![image](https://user-images.githubusercontent.com/24275608/223318051-9be7ac0c-eb94-4362-8a62-3e9e3c8fee5e.png)
otherwise DBMS return error:
![image](https://user-images.githubusercontent.com/24275608/223320708-d83ff3fa-3df9-48b3-997b-6313b0600520.png)

**Comment by jakeboone02** [comment]
It's not removing anything because the brackets don't exist in the query's `field` properties. You have to instruct `formatQuery` to add them to the output with the [`quoteFieldNamesWith` option](https://react-querybuilder.js.org/docs/utils/export#quote-field-names), like this:

```ts
formatQuery(query, { format: 'sql', quoteFieldNamesWith: ['[', ']'] });
// Returns: "([first-name] = 'Steve' and [last-name] = 'Vai')"
```

**Comment by AntonMPetrov** [comment]
Thank you, @jakeboone02
