### ISSUE TITLE
Add a possibility to clear rule value on field change

### ISSUE THREAD

**Issue by pavelbely** [react-querybuilder/react-querybuilder#48]
Hi,

Please add a possibility to clear rule value on field change.

Imagine there's a query builder with 1 rule
**Field1**    **=**    **hello**

If we now change field to **Field2** the value will still be hello.
It would be nice if that value can be cleared conditionally.

Currently there is no way to do that other than dirty checking filter object in `onQueryChange`.

Thanks

**Comment by xbojch** [comment]
@pavelbely this can easily be achieved by creating a custom component to replace the ValueEditor.
Then you can check for field or operator change in the componentWillReceiveProps and decide if you want to clear the value.

```javascript
componentWillReceiveProps(nextProps) {
    if (this.props.field !== nextProps.field) {
      this.props.handleOnChange('');
    }
  }
```

**Comment by grahamlyus** [comment]
Not sure how to handle it conditionally, but I added this to my PR #63 which fixes #39

**Comment by jakeboone02** [comment]
Closing this as the solution was provided by @xbojch.  Note that to do this with React Hooks, you'd need to use some version of [usePrevious](https://usehooks.com/usePrevious/) along with useEffect:
```js
const ValueEditor = ({ field, handleOnChange, operator, value }) => {
  const prevField = usePrevious(field);
  const prevOperator = usePrevious(operator);

  useEffect(() => {
    let newValue = value;
    if (prevField && prevField !== field) {
      newValue = '';
    }
    // ...maybe some other logic...
    if (newValue !== value) {
      handleOnChange(newValue);
    }
  }, [handleOnChange, prevField, field, value]);

  // ...

  return (
     // ...
  );
}
```

**Comment by chinku04** [comment]
should be use usePrevious from
`import { ValueEditor, ValueEditorProps, usePrevious } from "react-querybuilder";`
? as this is not working for me.
here is my code snippet for reference


`export const CustomValueEditor: React.FC<any> = (props) => {
  const { field, handleOnChange, operator, value }=props
  const prevField = usePrevious(field);
  console.log("prevField",prevField)
  const prevOperator = usePrevious(operator);

  useEffect(() => {
    let newValue = value;
    if (prevField && prevField !== field) {
      newValue = '';
    }
    if (newValue !== value) {
      handleOnChange(newValue);
    }
  }, [handleOnChange, prevField, field, value]);
  
  const selectedOperator: any = useMemo(() => {
    const { rule, fieldData } = props;
    const selectedOperator = fieldData.operators?.find(
      (operator: any) => operator.name === rule.operator
    );
    return selectedOperator
  }, [props.rule, props.fieldData]);

  const newProps = {
    ...props,
    type: componentMapping[selectedOperator?.uiInputType],
    arity:selectedOperator?.arity
  };
  return selectedOperator?.uiInputType === "MULTI_SELECT" ? (
    <DropDownValueEditor {...newProps} />
  ) : (
    <ValueEditor {...newProps} />
  );
};`
