### ISSUE TITLE
SQL parser regex captures too much text when field names wrapped in square brackets

### ISSUE THREAD

**Issue by AntonMPetrov** [react-querybuilder/react-querybuilder#482]
Hi, @jakeboone02 

I have following code:

```
import { QueryBuilderAntD } from "@react-querybuilder/antd";
import { useEffect, useState } from "react";
import QueryBuilder, { defaultCombinatorsExtended, formatQuery, parseSQL, RuleGroupType } from "react-querybuilder"
import 'react-querybuilder/dist/query-builder.css';
import { useAppDispatch, useAppSelector } from "../../redux/hooks";
import { fetchFields, selectFields } from "../../redux/appSettingsSlice/appSettingsSlice";

interface QueryBuilderProps {
    value?: string | undefined,
    onChange?: (value: string | undefined) => void
}

const initialQuery: RuleGroupType = { combinator: 'and', rules: [] };


const UserQueryBuilder = ({ value, onChange, }: QueryBuilderProps) => {
    const dispatch = useAppDispatch();
    const [query, setQuery] = useState(initialQuery);
    const [reload, setReload] = useState(true);

    const fields = useAppSelector(selectFields);

    useEffect(() => {
        try {
            if (value) {
                const parsedValue = parseSQL(value,);
                setQuery(parsedValue);
            }
        } catch { }
    }, [value]);

    useEffect(() => {
        if (reload)
            dispatch(fetchFields()).then(() => { setReload(false) })
    }, [reload, dispatch])

    return (
        <QueryBuilderAntD>
            <QueryBuilder
                fields={fields}
                query={query}
                combinators={defaultCombinatorsExtended}
                onQueryChange={(q) => {
                    setQuery(q);
                    if (onChange) {
                        const formattedQuery = formatQuery(q, { format: 'sql', quoteFieldNamesWith: ['[', ']'] });
                        if (formattedQuery !== "(1 = 1)") onChange(formattedQuery);
                    }
                }}
            />
        </QueryBuilderAntD>
    )
}

export default UserQueryBuilder;
```
When I add the second and subsequent rules, Query Builder merges the rules. It looks like this:
![image](https://user-images.githubusercontent.com/24275608/223408421-348a00ff-a8d4-4c35-8b3d-cb033710f78c.png)
When i use `formatQuery(q, 'sql')`  instead of `formatQuery(q, { format: 'sql', quoteFieldNamesWith: ['[', ']'] })` it works as it should:
![image](https://user-images.githubusercontent.com/24275608/223409451-277ba159-87df-4d83-9aca-5be3cbbcb86f.png)

Could you help with this case?

**Comment by jakeboone02** [comment]
I don't think the issue is with `formatQuery`, I think those two `useEffect`s, the `onChange` prop call, and the `setQuery` are all fighting each other.

Can you set up a CodeSandbox example with this same code? You can start with [this Ant Design template](https://codesandbox.io/p/sandbox/github/react-querybuilder/react-querybuilder/tree/main/examples/antd?file=/src/App.tsx).

**Comment by jakeboone02** [comment]
Actually never mind, I just tested it and the problem evident in your screenshot is definitely a `parseSQL` bug. So sorry about that, I should have had a test to catch that before releasing v6.0.5. (I still think you're doing some weird stuff with all those related updates and effects, but I can't be sure what problems it will cause without seeing the rest of the code.)

**Comment by jakeboone02** [comment]
@AntonMPetrov Can you try [v6.0.6](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.0.6)?

**Comment by AntonMPetrov** [comment]
@jakeboone02 
It looks like it's working as it should.
On Thursday we will test in more depth.

Anyway, thank you very much for your support and prompt response.
