### ISSUE TITLE
parseCEL() does not correctly parse members

### ISSUE THREAD

**Issue by patt1s0n** [react-querybuilder/react-querybuilder#489]
In CEL you reference child properties by using the member notation `.` e.g. `name.first`. However when trying to use `parseCEL` it doesn't recognise the child properties and simply returns nothing for the expression.

For example:
```
    const parsed = parseCEL(`name.first == "John" && name.last == "Doe"`)
    // expected
    // {
    //     "rules": [
    //         {
    //             "field": "name.first",
    //             "operator": "==",
    //             "value": "John"
    //         },
    //         {
    //             "field": "name.last",
    //             "operator": "==",
    //             "value": "Doe"
    //         }
    //     ],
    //     "combinator": "and",
    // }

    // actual
    // {
    //     "rules": [],
    //     "combinator": "and"
    // }
```

Language spec: https://github.com/google/cel-spec/blob/master/doc/langdef.md#syntax

**Comment by jakeboone02** [comment]
Thanks for the report, @patt1s0n! I'll release ~v6.1.1~ (edit: it ended up being [v6.1.2](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.1.2)) with the fix for this issue later today most likely.

**Comment by patt1s0n** [comment]
Thanks for the speedy fix :)
