### ISSUE TITLE
formatQuery for MongoDB output does not match regular output when using ruleGroups 

### ISSUE THREAD

**Issue by iskandarreza** [react-querybuilder/react-querybuilder#498]
Hi Jake, 

First of all, brilliant component. I love how simple and lightweight it is, and how easy it is to use. I might have found a bug though. 

I was testing this on a little personal side project I'm working on and encountered a discrepancy between the output when formatting the query for MongoDB and the component's actual output.

![ruleGroup output discrepancy](https://p-261de4.f1.n0.cdn.getcloudapp.com/items/GGu75Amr/7c7d8f7c-95db-4543-bcb8-a13f7530af9c.jpeg?v=2a069a5322c868dfa747d3669fcfed98)

I was expecting the output for MongoDB to look more like this:
```
  {
    "$or": [
      {
        "role": {
          "$regex": "front end"
        }
      },
      {
        "location": {
          "$regex": "remote"
        }
      },
      {
        "$and": [
          {
            "keywords": {
              "$regex": "react"
            }
          }
        ]
      }
    ]
  }
```

I also have a codesandbox here with a minimal reproducible example: https://codesandbox.io/s/quirky-scott-iqrqz1

Thanks!

**Comment by jakeboone02** [comment]
Thanks for the kind words! And that's an excellent, detailed report which I very much appreciate. :)

If I remember correctly, this behavior is intentional. `formatQuery` will, in the `"mongodb"` case anyway, collapse any groups that only contain one rule down to that rule by itself.

Is it causing a problem? If so, I'm happy to reevaluate that decision.

**Comment by iskandarreza** [comment]
Thank you for the quick response. 

Oh is that what is going on? Thinking about it, that does make sense for it to do that. Does it cause a problem? Not at the moment, and again when I think about it I don't feel like it will cause a problem. I guess I'll test it out on some data for a bit to confirm that. 

Fantastic component though. I'm using it not just to make a user-friendly query GUI for my side project, but also to learn the difference between different db query languages.

**Comment by jakeboone02** [comment]
That's fantastic that you're using it as a learning tool. Honestly I never considered that as a use case in and of itself, although I've certainly been using the _development_ of the component as a learning opportunity. Maybe I'll think about putting something more formal together for the docs site.
