### ISSUE TITLE
Component doesn't react with new data

### ISSUE THREAD

**Issue by blacksagres** [react-querybuilder/react-querybuilder#50]
The issue:
- The property `fields` in my application <QueryBuilder /> is using dynamic data that comes from an API call. But when the data is retrieved, the <QueryBuilder /> doesn't render the new options in the `fields` dropdown.

Expected behavior:
- Having the component to re-render with the updated property.

Code sample:

````
// # Retrieving the data
componentWillMount() {
    getQueryConditions().then((result) => {

      const queryConditions = result.data
        .map(condition => ({
          name: condition.Name.replace(/\s+/g, ''),
          label: condition.Name,
        }));

      this.setState({ conditions: queryConditions });
    });
  }

 // # Rendering the component
 renderQueryBuilder = (conditions) => {
    if (!this.state.conditions.length) return <LinearProgress />;

    return (<QueryBuilder
      fields={conditions}
      onQueryChange={this.logQuery}
    />);
  };
````

For now I was able to circumvent this by interrupting the render completely until there's data. But is the fact that the component doesn't re-render a feature by design?

**Comment by jeroen-corsius** [comment]
I'm facing a similar issue:
What I'm trying to accomplish is resetting the QueryBuilder to it's initial state, by updating the query-property. The component doesn't re-render on this unfortunately.

**Comment by ganesharulanantham** [comment]
@blacksagres is this issue fixed? Any work around available?

**Comment by hellofantastic** [comment]
if I'm correct as I work through it QueryBuilder needs a ComponentWillRecieveProps  and if not equal update root, schema etc

**Comment by blacksagres** [comment]
@ganesharulanantham sorry for the late reply. I haven't found any workaround other than what I did. I only render the component once I verify there is data available to build it, otherwise I render nothing.

**Comment by blacksagres** [comment]
@hellofantastic I tested it with dynamic props and the component still didn't re-render. Do you have any examples of what you're explaining?

**Comment by hellofantastic** [comment]
@blacksagres   ... I should see if my modifications are working in an hour or so .. and to give some context we have a ui that now has a dropdown (before was one query per page/view) and you can select a query and it loads up in queryBuilder... which worked fine until the dynamic query load .. and noticed query changed but querybuilder controls had last query loaded options

**Comment by hellofantastic** [comment]
@blacksagres so this is all I ended up adding to queryBuilder for our case
```javascript
componentWillReceiveProps(nextProps) {
        let schema  = {...this.state.schema};
         
         if (this.props.query !== nextProps.query) {
             this.setState({ root: nextProps.query });
         }

         if(schema.fields !== nextProps.fields){
             schema.fields = nextProps.fields;
              this.setState({ schema });
         }
   
}
```

**Comment by blacksagres** [comment]
@hellofantastic Thanks for the code snippet. I'll test on my solution and confirm the results. :)

@jeroen-corsius Do you have a working solution?

**Comment by pavanpodila** [comment]
@hellofantastic I think this could be a nice PR :-)

**Comment by hellofantastic** [comment]
For sure , I could this week

**Comment by miphe** [comment]
#67 addresses this issue and is now merged.
