### ISSUE TITLE
React Native Slow Performance

### ISSUE THREAD

**Issue by enchorb** [react-querybuilder/react-querybuilder#500]
Hi, 

Thanks a lot for the React Native compatibility package its been working great for me! One thing I have noticed however is the slow performance when changing the text inputs. 

Console logging `onQueryChange` shows that at times values I type come out 500ms to upwards of 3s later. For now I solved the issue by disabling my submit button with a `setTimeout` until `onQueryChange` hasn't changed in over 2 seconds.

**Comment by jakeboone02** [comment]
Could you share your component code? Input updates shouldn't take that long, so there may be some opportunities for optimization.

**Comment by enchorb** [comment]
Apologies for this, appears to just be slow on the simulator for whatever reason but much faster when I built to my device. Memo-izing the custom controls (Native Base) I made also seems to have helped quite a bit

ie.
```
export const controlElements: Partial<Controls> = {
  addGroupAction: memo(ActionElement),
  addRuleAction: memo(ActionElement),
  cloneGroupAction: memo(ActionElement),
  cloneRuleAction: memo(ActionElement),
  lockRuleAction: memo(ActionElement),
  lockGroupAction: memo(ActionElement),
  removeGroupAction: memo(ActionElement),
  removeRuleAction: memo(ActionElement),
  notToggle: memo(NotToggle),
  combinatorSelector: memo(ValueSelector),
  fieldSelector: memo(ValueSelector),
  operatorSelector: memo(ValueSelector),
  valueSourceSelector: memo(ValueSelector),
  valueEditor: memo(ValueEditor)
};
```
