### ISSUE TITLE
AntD compat package v6.1.4 error: Can't resolve 'process/browser' in '/node_modules/@react-querybuilder/antd/dist'

### ISSUE THREAD

**Issue by fmhurizen** [react-querybuilder/react-querybuilder#502]
ERROR in ./node_modules/@react-querybuilder/antd/dist/index.mjs 1836:7-14
Module not found: Error: Can't resolve 'process/browser' in '/node_modules/@react-querybuilder/antd/dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by jakeboone02** [comment]
Can you try v6.2.0-alpha.3? Run `yarn add` (or `npm install`) `react-querybuilder@next @react-querybuilder/antd@next`.

If you confirm that fixes it, I'll publish v6.2.0 tonight or tomorrow.

**Comment by fmhurizen** [comment]
@jakeboone02 yes v6.2.0-alpha.3 fixes it.
Please publish it.
Thanks

**Comment by jakeboone02** [comment]
Published: [v6.2.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.2.0).

**Comment by fmhurizen** [comment]
@jakeboone02  now i am encountering these errrors

ERROR in ./node_modules/@react-querybuilder/ts/src/index.noReact.ts 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export * from './dnd';
| export * from './importExport';
> export type {
|   JsonLogicAnd,
|   JsonLogicDoubleNegation,


ERROR in ./node_modules/@react-querybuilder/ts/src/propsUsingReact.ts 1:12
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import type {
|   ComponentType,
|   ForwardRefExoticComponent,




and this the webpack config i currently have

```
 {
        test: /\.[jt]sx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'ts-loader',
          options: {
            // Remove this line to enable type checking in webpack builds
            transpileOnly: true,
            compilerOptions: {
              module: 'esnext'
            }
          }
        }
      },
```

**Comment by jakeboone02** [comment]
Can you provide a full, example repo that demonstrates the issue?

**Comment by fmhurizen** [comment]
@jakeboone02 here is the link to my repo
https://github.com/farhanmalhi-dbank/template

Thanks
