### ISSUE TITLE
Custom ValueEditor rerenders infinitely: "handleOnChange" updates every render

### ISSUE THREAD

**Issue by Andonvr** [react-querybuilder/react-querybuilder#505]
I'm trying to do something like [this](https://react-querybuilder.js.org/docs/tips/custom-with-fallback). My code looks like this:  
```
const pathToKey = (path: number[]) => {
  return path.reduce((acc, curr) => {
    return `${acc}[${curr}]`
  }, "")
}

export const CustomValueEditor: FC<ValueEditorProps> = (props: ValueEditorProps) => {
  console.log("Rendered")
  if (props.type === "text") {
    return (
      <div>
        <FilterTextField
          {...props}
          placeholder={`Enter ${props.fieldData.label} here`}
          key={pathToKey(props.path)}
        />
      </div>
    )
  }
  return <ValueEditor {...props} key={pathToKey(props.path)} />
}
```

But this way, "Rendered" keeps being logged. And the FilterTextField component keeps rerendering as well.  However, if I remove everything inside `if (props.type === "text") { ...}`, so that this really only returns `<ValueEditor ... />`, this does NOT happen! No unnecessary rerenders!  

After some investigation, I realized that "handleOnChange" in the props keeps changing between each render.  
How can I prevent this?

**Comment by jakeboone02** [comment]
I would need more information, but I do spot a couple of odd things in the code you've provided.

I'm not sure why you would need the `key` to be in that `reduce`-generated bracket format, when you could do something simpler like `props.path.join("-")`.

Also you probably don't need the `key` prop anyway. Can you explain your reasoning for adding that?

In order to figure out why you're seeing infinite render loops, I would need to see the code for `FilterTextField`.  Can you set up a CodeSandbox or StackBlitz or similar that demonstrates the problem? You can use one of the [examples here](https://github.com/react-querybuilder/react-querybuilder/tree/main/examples) as a starting point.

**Comment by jakeboone02** [comment]
Just thinking about this some more, does `FilterTextField` call `useEffect`? That can be the cause of infinite rerenders sometimes.

**Comment by zeroed-tech** [comment]
Not sure if its the same issue but I'm running into this error which lead me to think I need to somehow define a unique key 
```Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RuleGroupBodyComponents`. See https://reactjs.org/link/warning-keys for more information.
    at RuleGroupBodyComponents (http://localhost:3000/static/js/bundle.js:152035:13)
    at div
    at div
    at RuleGroup (http://localhost:3000/static/js/bundle.js:151870:8)
    at RuleGroupDnD (http://localhost:3000/static/js/bundle.js:130535:74)
    at div
    at QueryBuilder (http://localhost:3000/static/js/bundle.js:152323:8)```

**Comment by jakeboone02** [comment]
@zeroed-tech That's a different issue. Can you create a new issue and provide a reproducible example?

**Comment by hfmvin** [comment]
I also have similar problem, which is easy to reproduce by replacing it with <input>. When  input, it was re rendered due to handleOnChange and cannot be input continuously

  const customEdit = (props) => {
    return <input onChange={(e)=>props.handleOnChange(e.target.value)} value={props.value} />
  }

  const controlElements = {
    valueEditor: customEdit
  }

**Comment by jakeboone02** [comment]
> I also have similar problem, which is easy to reproduce by replacing it with . When input, it was re rendered due to handleOnChange and cannot be input continuously
> 
> const customEdit = (props) => { return <input onChange={(e)=>props.handleOnChange(e.target.value)} value={props.value} /> }
> 
> const controlElements = { valueEditor: customEdit }

See https://github.com/react-querybuilder/react-querybuilder/issues/588#issuecomment-1798786180
