### ISSUE TITLE
Release 6.2.0 - Module Not Found

### ISSUE THREAD

**Issue by matt-peck-populi** [react-querybuilder/react-querybuilder#506]
## Summary
Installation of 6.2.0 works fine, but the moment you attempt to import components/files from the library the build breaks.

```
Failed to compile.

Module not found: Error: Can't resolve './index.noReact' in '/project/sandbox/node_modules/@react-querybuilder/ts/src'
WARNING in ./node_modules/react-querybuilder/dist/query-builder.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/react-querybuilder/dist/query-builder.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/sandbox/node_modules/react-querybuilder/src/query-builder.scss' file: Error: ENOENT: no such file or directory, open '/project/sandbox/node_modules/react-querybuilder/src/query-builder.scss'

ERROR in ./node_modules/@react-querybuilder/ts/src/index.ts 1:0-32
Module not found: Error: Can't resolve './index.noReact' in '/project/sandbox/node_modules/@react-querybuilder/ts/src'

ERROR in ./node_modules/@react-querybuilder/ts/src/index.ts 2:0-34
Module not found: Error: Can't resolve './propsUsingReact' in '/project/sandbox/node_modules/@react-querybuilder/ts/src'

webpack compiled with 2 errors and 1 warning
```

## Example
https://codesandbox.io/p/sandbox/loving-mcnulty-mdzctz

**Comment by jakeboone02** [comment]
Thanks for the report. Can you try `v6.3.0-alpha.0` and let me know if that fixes the issue?

**Comment by matt-peck-populi** [comment]
> Thanks for the report. Can you try `v6.3.0-alpha.0` and let me know if that fixes the issue?

@jakeboone02 That fixed it! Thanks!

**Comment by jakeboone02** [comment]
Whew! Good to hear. v6.3.0 won't have much in the way of bug fixes or new features compared to the alpha so feel free to use the alpha in your production app.

**Comment by memoricab** [comment]
Hello,

I can confirm reproduced same error with 6.2.0. And, v6.3.0-alpha.0 fixes the issue. W will also keep using alpha version. Thanks @jakeboone02

**Comment by jakeboone02** [comment]
@matt-peck-populi / @memoricab - FYI, [v6.3.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.3.0) was just released.
