### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module in v6.3.0-alpha.0

### ISSUE THREAD

**Issue by fmhurizen** [react-querybuilder/react-querybuilder#509]
This error occurred while running jest

node_modules/antd/es/date-picker/generatePicker/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import PickerButton from '../PickerButton';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

    > 1 | import { QueryBuilderAntD } from '@react-querybuilder/antd';
        | ^
```

**Comment by jakeboone02** [comment]
This doesn't appear to be an issue with `react-querybuilder` but with your Jest configuration. See https://jestjs.io/docs/ecmascript-modules.

**Comment by jakeboone02** [comment]
Actually before you dive into that Jest rabbit hole, try RQB v6.3.0 and see if that helps.

**Comment by fmhurizen** [comment]
@jakeboone02 same error in v6.3.0

**Comment by fmhurizen** [comment]
```
preset: 'ts-jest',
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^.+\\.svg$': 'jest-svg-transformer',
    uuid: require.resolve('uuid') 
  },
  moduleDirectories: ['node_modules', '<rootdir>/src'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts', '@testing-library/jest-dom/extend-expect'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  roots: ['<rootDir>/src'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest'
  }
```

this is my jest config seems nothing wrong in it

**Comment by jakeboone02** [comment]
> @jakeboone02 same error in v6.3.0

Well, it was worth a shot. I do still think it's something solvable in the Jest config.

**Comment by fmhurizen** [comment]
i have been using
"@react-querybuilder/antd": "^5.1.4",
"react-querybuilder": "^5.1.4",

which works perfectly fine.

**Comment by jakeboone02** [comment]
Would you mind setting up a working repo that reproduces the problem? I'll try to look into it.

**Comment by fmhurizen** [comment]
@jakeboone02 Sure, please look at this repo: https://github.com/farhanmalhi-dbank/template
Thanks

**Comment by jakeboone02** [comment]
I'm going to go ahead and close this issue and leave it with you. If anyone else comes across this, I can reopen the issue and continue to investigate.

**Comment by nastassia-citian** [comment]
Also getting this error with `react-querybuilder v6.5.0`. I'm not using jest but this fails a next.js / vercel build.

**Comment by jakeboone02** [comment]
@nastassia-citian Would you mind setting up a working repo that reproduces the problem?

**Comment by nastassia-citian** [comment]
@jakeboone02  Sure! Meanwhile, looks like the issue is from the way the antd generatePicker is getting imported? https://github.com/react-querybuilder/react-querybuilder/blob/b25797530e5e199ccf05fc91002db3bc77a4481e/packages/antd/src/AntDValueEditor.tsx#LL2C1-L2C1

**Comment by jakeboone02** [comment]
> looks like the issue is from the way the antd generatePicker is getting imported?

Thanks! I'll take a look at that.

**Comment by nastassia-citian** [comment]
@jakeboone02 Here's the repo I made that reproduces the issue: https://github.com/nastassia-citian/react-querybuilder-test

**Comment by jakeboone02** [comment]
@nastassia-citian I've fixed the issue with the AntD compatibility package, and will release v6.5.1 with the fix shortly.

One thing I noticed in your example repo was you were defining a couple of components within another component.  [That's a big no-no](https://react-querybuilder.js.org/docs/tips/common-mistakes#custom-component-as-closure).  This diff will fix the issue:

```diff
diff --git a/pages/index.tsx b/pages/index.tsx
index dc35c07..be2d0a2 100644
--- a/pages/index.tsx
+++ b/pages/index.tsx
@@ -3,29 +3,29 @@ import React from "react";
 import type { FieldSelectorProps, CombinatorSelectorProps, ValueEditorProps } from "react-querybuilder";
 import { QueryBuilder, formatQuery } from 'react-querybuilder';
 
-export default function Home() {
-    const MyAntDFieldSelector = (props: FieldSelectorProps | CombinatorSelectorProps ) => {
+const MyAntDFieldSelector = (props: FieldSelectorProps | CombinatorSelectorProps ) => {
+    return (
+        <AntDValueSelector
+            {...props}
+            getPopupContainer={(e) => e.parentElement as HTMLElement} />
+    );
+};
+
+const MyAntDValueSelector = (props: ValueEditorProps) => {
+    if ((props.type === 'select' || props.type === 'multiselect') && props.inputType === 'text') {
         return (
             <AntDValueSelector
+                options={props.fieldData.values || []}
                 {...props}
+                mode={props.type === 'multiselect' ? 'multiple' : undefined }
                 getPopupContainer={(e) => e.parentElement as HTMLElement} />
         );
-    };
-
-    const MyAntDValueSelector = (props: ValueEditorProps) => {
-        if ((props.type === 'select' || props.type === 'multiselect') && props.inputType === 'text') {
-            return (
-                <AntDValueSelector
-                    options={props.fieldData.values || []}
-                    {...props}
-                    mode={props.type === 'multiselect' ? 'multiple' : undefined }
-                    getPopupContainer={(e) => e.parentElement as HTMLElement} />
-            );
-        } else {
-            return (<AntDValueEditor {...props} />);
-        }
-    };
+    } else {
+        return (<AntDValueEditor {...props} />);
+    }
+};
 
+export default function Home() {
     return (
         <QueryBuilderAntD>
             <QueryBuilder
```

**Comment by jakeboone02** [comment]
[v6.5.1](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.5.1) was just released.

**Comment by nastassia-citian** [comment]
Thank you @jakeboone02 :)
