### ISSUE TITLE
Has anyone written a parser already?

### ISSUE THREAD

**Issue by sarink** [react-querybuilder/react-querybuilder#51]
Has anyone written a parser that iterates over an array of items and filters on the query output from this library?

Just wondering if it exists already so I don't have to reinvent the wheel :)

**Comment by BrandonKowalski** [comment]
I've created one that bridges QueryBuilder output into a JOOQ condition. If you happen to be using Java and JOOQ it might be of help.

https://github.com/Kowalski-IO/jqb2jooq

**Comment by jakeboone02** [comment]
@sarink - see PR #95.  Is that what you're looking for?
