### ISSUE TITLE
Feature Request: Accessible up and down buttons in place of drag and drop mode

### ISSUE THREAD

**Issue by lkarvec** [react-querybuilder/react-querybuilder#511]
For accessibility, It would be really cool to have up and down arrows to move rows up and down in place of the drag and drop feature.

I might be able to get my designer to show what I kinda mean here design-wise in a bit.  Will update if so.

**Comment by lkarvec** [comment]
![image](https://user-images.githubusercontent.com/47825690/236040191-3296b26e-93f3-434e-ae27-ff82028b0e67.png)

**Comment by jakeboone02** [comment]
Thanks for submitting this. Once the component is designed, we need to make a decision about functionality:

For rules that are directly below a sub-group, should the "move up" button move it immediately above the group, or should it move it _into_ the group as the last element?

![image](https://user-images.githubusercontent.com/366438/236044629-1a72fd92-b6ad-4c45-8d80-bcdf8e40476f.png)

Vice versa for "move down".
