### ISSUE TITLE
Accepting key value pairs

### ISSUE THREAD

**Issue by zeroed-tech** [react-querybuilder/react-querybuilder#513]
Hi,

Is there a way I can configure my query builder so it can accept two text inputs to represent a key/value pair?

I'm attempting to replicate the following:
![image](https://user-images.githubusercontent.com/3313484/236655565-d392e2b1-c4dd-4edf-b786-4b7d9569eade.png)

The best workaround I've come up with so far would be to use a "between" which has been relabeled as "=" and enable `listsAsArrays` however that still results in the output containing an operator of "between" which isn't ideal.

Appologies if this is something simple but I've looked through the documentation and examples a few times and haven't come up with a solution.

Thanks

**Comment by jakeboone02** [comment]
Hi @zeroed-tech, yeah that's a shortcoming of the docs currently -- no good examples of using complex objects or arrays for a rule `value`.

This codesandbox should give you an idea of how I would handle this.

https://codesandbox.io/s/trusting-boyd-ftdve1?file=/src/CustomValueEditor.tsx

`CustomValueEditor.tsx`:
```tsx
import {
  standardClassnames,
  ValueEditor,
  ValueEditorProps,
} from 'react-querybuilder';

export const CustomValueEditor = (props: ValueEditorProps) => {
  if (props.field === 'keyval') {
    return (
      <div className={props.className}>
        <input
          className={standardClassnames.valueListItem}
          value={props.value?.key ?? ''}
          onChange={e =>
            props.handleOnChange({
              ...props.value,
              key: e.target.value,
            })
          }
        />
        <input
          className={standardClassnames.valueListItem}
          value={props.value?.value ?? ''}
          onChange={e =>
            props.handleOnChange({
              ...props.value,
              value: e.target.value,
            })
          }
        />
      </div>
    );
  }

  return <ValueEditor {...props} />;
};
```

`App.tsx`:
```tsx
import { useState } from 'react';
import type { Field, RuleGroupType } from 'react-querybuilder';
import { formatQuery, QueryBuilder } from 'react-querybuilder';
import { CustomValueEditor } from './CustomValueEditor';
import './styles.scss';

const fields: Field[] = [
  { name: 'keyval', label: 'Key/Value' },
  { name: 'firstName', label: 'First Name' },
  { name: 'lastName', label: 'Last Name' },
];

const initialQuery: RuleGroupType = {
  combinator: 'and',
  rules: [
    { field: 'keyval', operator: '=', value: null },
    { field: 'firstName', operator: 'beginsWith', value: 'Stev' },
    { field: 'lastName', operator: 'in', value: 'Vai,Vaughan' },
  ],
};

export const App = () => {
  const [query, setQuery] = useState(initialQuery);

  return (
    <div>
      <QueryBuilder
        fields={fields}
        query={query}
        onQueryChange={q => setQuery(q)}
        controlElements={{
          valueEditor: CustomValueEditor,
        }}
      />

      <h4>Query</h4>
      <pre>
        <code>{formatQuery(query, 'json')}</code>
      </pre>
    </div>
  );
};
```

**Comment by zeroed-tech** [comment]
Hey Jake, 
Thankyou very much for the example, that certainly got me on the right path. I noticed `json_without_ids` does not handle this properly (it only prints the value field but excludes the key field e.g. "value": {"value": "some value"} however this is easy to workaround by manually specifying the fields I require using:
```
JSON.stringify(query, [
  "combinator",
  "rules",
  "field",
  "operator",
  "value",
 "key",
])
```
Thanks again for the help and the library, you've saved me weeks
