### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by zeroed-tech** [react-querybuilder/react-querybuilder#514]
I'm looking to add some validation to my form and whilst I can see that my `validator` is running (via breakpoints and logging), I'm getting no feedback to indicate any fields are invalid.

I've got an example running here https://codesandbox.io/s/sleepy-gauss-dmyjw4 which in theory should be marking all fields and groups as invalid however I dont get the any messages such as the one shown in https://react-querybuilder.js.org/demo#addRuleToNewGroups=false&autoSelectField=true&autoSelectOperator=true&debugMode=false&disabled=false&enableDragAndDrop=false&independentCombinators=false&justifiedLayout=false&listsAsArrays=false&parseNumbers=false&resetOnFieldChange=true&resetOnOperatorChange=false&showBranches=false&showCloneButtons=false&showCombinatorsBetweenRules=false&showLockButtons=false&showNotToggle=false&validateQuery=true

Does something else need to be done to get error messages displaying?

Thanks

**Comment by jakeboone02** [comment]
Adding a `validator` function only applies the CSS classes `queryBuilder-valid` or `queryBuilder-invalid` as appropriate (see the ["Effect on HTML" section in the validation docs](https://react-querybuilder.js.org/docs/utils/validation#effect-on-html)).

The demo on the website has some extra CSS beyond `query-builder.css` to style the invalid elements when the "Use validation" option is checked. See [SCSS source here](https://github.com/react-querybuilder/react-querybuilder/blob/0487419f0603b19d32c2eb00d6be25bf77922d86/website/src/pages/demo/_styles/demo.scss#L12-L56).

**Comment by jakeboone02** [comment]
@zeroed-tech I updated the "Code" tab of the [demo](https://react-querybuilder.js.org/demo) to include a "Styles" section that displays the additional styles not included in `react-querybuilder/dist/query-builder.scss` (or `.css`), the styles specific to the demo.

**Comment by zeroed-tech** [comment]
Thanks for that. Going by that example, the error message to display is configured in the CSS file, is there a way to use the `reason' specified in the validation function instead?

**Comment by jakeboone02** [comment]
Yes, but you would need to use a custom component. I can help with the code if you show me a mockup of what you want it to look like.

**Comment by zeroed-tech** [comment]
Thanks Jake, saying it needed to be a custom component was enough to get me on the right track

![image](https://github.com/react-querybuilder/react-querybuilder/assets/3313484/60772492-81a6-4f30-ac2f-7874cfe82517)

For eanyone else struggling with this, the following `valueEditor` should get you on the right track. This was written in a hurry so the forced casting should probably be replaced with something a bit more stable

```
const CustomValueEditor = (props: ValueEditorProps) => {
  if (props.type === "text") {
    return (
      <div className={props.className}>
        <TextField
          variant="outlined"
          type="text"
          fullWidth
          size="small"
          error={!(props.validation as ValidationResult).valid}
          helperText={
            !(props.validation as ValidationResult).valid &&
            (props.validation as ValidationResult).reasons?.join(" ")
          }
          className={standardClassnames.valueListItem}
          onChange={(e) => props.handleOnChange(e.target.value)}
        >
          props.value ?? ""
        </TextField>
      </div>
    );
  }

  return <ValueEditor {...props} />;
};
```
