### ISSUE TITLE
Question: disable automatic selection of the first element in the array for multiselect

### ISSUE THREAD

**Issue by allapologies** [react-querybuilder/react-querybuilder#516]
Hey, there! 
thanks for the awesome library 🙏

question: is there a way to prevent automatic selection of the first item in the array when value editor is being renderer for the new rule?

something like these props, but for the ValueEditor (e.g. autoSelectValue={false})

- [autoSelectField](https://react-querybuilder.js.org/docs/components/querybuilder#autoselectfield)
- [autoSelectOperator](https://react-querybuilder.js.org/docs/components/querybuilder#autoselectoperator)

Thanks in advance!

**Comment by jakeboone02** [comment]
Hi @allapologies! When `autoSelectField` and `autoSelectOperator` are `false`, all that does is add a "dummy" option at the start of the options array. This is the actual code for setting up the `fields` option list (when it's not a grouped list):

https://github.com/react-querybuilder/react-querybuilder/blob/60cd310056be5352c11b2a50cc15fe200f7b1bb8/packages/react-querybuilder/src/hooks/useQueryBuilder.ts#L143-L147

`uniqByName` ensures there are no duplicate fields. `f` is (typically) the `fields` prop passed in to the component. `defaultField`, by default, is `{ name: '~', label: '------' }`. `formatQuery` and other utils have special handling code for when a `field` has a value equal to the default, i.e. `"~"`.

So, to do the same for a value editor that renders a value selector, my initial recommendation would be to do the same thing with the `values` property of the field in question.

**Comment by allapologies** [comment]
thank you very much for the hint, it really makes sense 🙏
