### ISSUE TITLE
topics for repo should include builder

### ISSUE THREAD

**Issue by James-E-Adams** [react-querybuilder/react-querybuilder#52]
Hi! 
I've noticed that this doesn't show up if you search react query builder in github search. It could prove useful to add the word builder or querybuilder or something to the topic list here:

![image](https://user-images.githubusercontent.com/9067274/35259000-35b8004e-0057-11e8-8eef-495fc4e5e2f9.png)

so this repo can find it to the hands of the right people! :)

**Comment by pavanpodila** [comment]
Thanks for suggestions James. Added those now :-)

**Comment by James-E-Adams** [comment]
Nice! 🎉
