### ISSUE TITLE
How edit behavior of operator 'in' (formatQuery(query, 'mongodb')

### ISSUE THREAD

**Issue by AzizBoughattas** [react-querybuilder/react-querybuilder#521]

**Comment by jakeboone02** [comment]
Hi @AzizBoughattas, did you find the [`parseNumbers` option](https://react-querybuilder.js.org/docs/utils/export#parse-numbers)?

**Comment by AzizBoughattas** [comment]
Hi @jakeboone02 , yess i found it, thanks for responding and for this great lib
