### ISSUE TITLE
is it possible to customize new format ?

### ISSUE THREAD

**Issue by AzizBoughattas** [react-querybuilder/react-querybuilder#522]
almost just like mongodb but a little bit different :
|**Operator**     |	**Description**                                                                                        |
|:---------------:|:------------------------------------------------------------------------------------------------------:|
| $eq	            | Equal                                                                                                  |
| $eqi	          | Equal (case-insensitive)                                                                               |
| $lt	            | Less than                                                                                              |
| $lte	          | Less than or equal to                                                                                  |
| $gt	            | Greater than                                                                                           |
| $gte	          | Greater than or equal to                                                                               |
| $in	            | Included in an array                                                                                   |
| $nin	          | Not included in an array                                                                               | 
| $contains	      | Contains                                                                                               |
| $not	          | not                                                                                                    |
| $exists         |	Exists                                                                                                 |
| $startsWith	    | Starts with                                                                                            |
| $endsWith	      | Ends with                                                                                              |
| $or	            | Joins the filters in an "or" expression                                                                |
| $and	          | Joins the filters in an "and" expression  

example : 
 $or: [
          {
            $and: [
              { title:  { $contains: 'Hagiographie' } },
              { code: { $eqi: 'xytr2' } },
              { code: 'XyTr2' },
              { tags: { $in: ['tag1', 'tag2'] } },
              { tags: { $exists: true } },
              { price: { $not: { $lt: 10 } } },
            ],
          },
          {
            tags: { $nin: ['tag1', 'tag2'] },
            price: { $gte: 12 },
            code: { $not: { $exists: true } },
            content: {
              $startsWith: 'blah blah' ,
            },
          },
        ],

**Comment by jakeboone02** [comment]
Have you tried using the `"mongodb"` export with a custom `ruleProcessor`?
