### ISSUE TITLE
Invalid rules on `parseMongoDB` with "doesNotContains" operator

### ISSUE THREAD

**Issue by ronit123321** [react-querybuilder/react-querybuilder#523]
A bug has been observed, while generating the condition for **do not contains operator** with the single rule. The parsed value of the string condition contains the extracted values of the rules and results in error being thrown as rules are undefined.

**Does not contain**

Condition generated `{"title":"Cond1","expression":"{\"!\":{\"in\":[\"kk\",{\"var\":\"cnd1\"}]}}","goToTitle":"kj","elseGoToTitle":"jj"}`

Parse expression result `{"field":"cnd1","operator":"doesNotContain","value":"kk"}`

**Contains**

Condition generated `{"title":"Cond11","expression":"{\"in\":[\"111\",{\"var\":\"cnd1\"}]}","goToTitle":"a","elseGoToTitle":"b"}`

Parse expression result `{"combinator":"and","rules":[{"field":"cnd1","operator":"contains","value":"111"}]}`

**Comment by jakeboone02** [comment]
Can you provide a live reproduction? You can use CodeSandbox or StackBlitz by clicking one of the links in [this example](https://github.com/react-querybuilder/react-querybuilder/blob/main/examples/basic-ts/README.md).

**Comment by MaksumMagzhan** [comment]
> Can you provide a live reproduction? You can use CodeSandbox or StackBlitz by clicking one of the links in [this example](https://github.com/react-querybuilder/react-querybuilder/blob/main/examples/basic-ts/README.md).

https://codesandbox.io/p/sandbox/xenodochial-chebyshev-jx3svs?file=%2Fsrc%2FApp.tsx%3A22%2C3
parseMongoDB function returns wrong result when parsing expressions 'does not contain', 'does not start with', 'does not end with'

**Comment by jakeboone02** [comment]
This will be fixed in v7: see bfac0c6c2efc6861ca88b0e924f708ba2fb1dc52
