### ISSUE TITLE
Add ElasticSearch export option to `formatQuery`

### ISSUE THREAD

**Issue by jakeboone02** [react-querybuilder/react-querybuilder#526]
Allow for the generation of ElasticSearch Query.

_Originally posted by @vvillait88 in https://github.com/react-querybuilder/react-querybuilder/discussions/525_

**Comment by bjulliana** [comment]
@jakeboone02 I see that you closed this issue and merged the ElasticSearch PR #583, however I see that is not yet released, do you have an estimate when it will be? I see that it is showing as an available export option on the demo, but it's not on version 6.5.5, yet. Thank you

**Comment by jakeboone02** [comment]
@bjulliana Very soon, I hope! I just published [7.0.0-beta.5](https://www.npmjs.com/package/react-querybuilder/v/7.0.0-beta.5), which is probably more of a release candidate than a beta.

If you want to use the functionality now, feel free to try the latest v7 beta. Migration instructions from v6 are [here](https://react-querybuilder.js.org/docs/next/migrate).
