### ISSUE TITLE
Cannot access Rule ID from ValueEditorProps

### ISSUE THREAD

**Issue by andonal** [react-querybuilder/react-querybuilder#528]
I'm working on a project that validates Rule values in the query builder using a custom Rule validator function as a Field property in my Fields array. I am able to validate each Rule successfully this way and render a custom value component indicating the validation failure. However, I currently am managing the state of all rule validations in a parent component (passed as props to the custom value editor via context) because logic in my parent component relies on the rule validation results.

I would like to be able to manage the rule validation state using a mapping of: Rule ID -> boolean validation result. However, currently I am unable to access the rule ID from ValueEditorProps (nor FieldSelectorProps, OperatorSelectorProps). This creates a situation where I need to create my own identifier using UUID or otherwise for this mapping. When removing rules I am unable to remove the rule-specific validation result from my state mapping, as the ActionProps *does* contain Rule ID, but as far as I know, there are only hacky ways to retrieve the UUID I'm forced to use for my mapping.

Is it within reason for the ValueEditorProps to include the rule ID?

Thank you for the time and consideration, as well as for making a great open-source component. I hope I explained my scenario adequately.

**Comment by jakeboone02** [comment]
I'm thinking it's probably best if we just pass the entire rule object down to each rule subcomponent. Kind of like how most of the group subcomponents get the group's `rules` array as a prop.

A workaround you can use today involves the `path` prop. Pass down the entire query in `context` and in your value editor use `findPath(props.path, props.context.query)` to get the full rule object.

**Comment by andonal** [comment]
> I'm thinking it's probably best if we just pass the entire rule object down to each rule subcomponent. Kind of like how most of the group subcomponents get the group's rules array as a prop.

I would definitely support that change, if possible :)

> A workaround you can use today involves the path prop. Pass down the entire query in context and in your value editor use findPath(props.path, props.context.query) to get the full rule object.

I actually thought about this as well, though I was worried about the complications of managing the state assuming every rule's path changes if a rule that precedes it is removed -- unless I'm misunderstanding how path works. Currently, my workaround is setting the validation boolean in my state object to true (it's fine if deleted rules are considered "valid") for all rules when any rule is removed via a custom remove action, and then letting the re-rendered custom value component correct the state. It's not ideal (or efficient), but it's functional!

Thank you for the very quick reply and suggestion.

**Comment by jakeboone02** [comment]
Hey @andonal, could you try out one of the example sandboxes in https://github.com/react-querybuilder/react-querybuilder/pull/529#issuecomment-1585292355?

They're based on #529 that adds a `rule` prop to all the rule sub-components.

**Comment by andonal** [comment]
Hey Jake, I've taken a quick look at the sandbox and the contents of the pull request. I believe this will satisfy this issue. Thank you for the quick turnaround on this!

**Comment by jakeboone02** [comment]
Great! I'll polish it up and try to publish it as v6.5.0 soon.
