### ISSUE TITLE
Is there a way to execute a rule?

### ISSUE THREAD

**Issue by camposfyi** [react-querybuilder/react-querybuilder#535]
I can't seem to find it, but is there something that will evaluate if an object passes a rule?

i.e. 
my rule = `age > 30 && first_name == 'John'`
`my_object = {first_name: 'John', age: 55}`

is there something that I can call `matches_rule(rule, my_object)` and returns **true** or **false**?

**Comment by jakeboone02** [comment]
Sounds like JsonLogic would meet your need:

- [Official site](https://jsonlogic.com/)
- [RQB export documentation](https://react-querybuilder.js.org/docs/utils/export#jsonlogic)

**Comment by camposfyi** [comment]
Thanks Jake. jsonlogic worked perfect.
