### ISSUE TITLE
Use generics for control elements inferred by fields

### ISSUE THREAD

**Issue by sneakytowelsuit** [react-querybuilder/react-querybuilder#541]
A little bit ago, I had opened a PR to add generics to the `ValueEditor` component so that any customizations could be strongly typed against any field customizations (e.g. use strongly typed access to the field names to override the value editor experience). Now that I've had the chance to use it, I realized that the `QueryBuilder` component doesn't support the `ValueEditor` if the props have been customized to support custom fields since it doesn't use generic slots to hold the field type parameters and apply them down to the other props on the component. 

For example, if I use a field defined by
```typescript
type MyCustomField = Field<'fieldName1' |  'fieldName2'>

const fields: MyCustomField[] = []

const CustomValueEditor: FC<ValueEditorProps<MyCustomField>> = (props) => {
  return <div />
}

const MyQueryBuilderWrapper = () => {

 return <QueryBuilder
    fields={fields}
    controlElements={{
      valueEditor: CustomValueEditor // This will throw an error because the props aren't compatible 
    }}
  />
}
```

This obviously incurs some rather massive changes since the `QueryBuilder` component is there all the type inference would originate, but it does also mean that any customizations to the `Field` objects used will be strongly typed and supported for other generic components, callbacks, etc. 

From what I can tell, the place to start making these changes is [this line here](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/react-querybuilder/src/types/propsUsingReact.ts#L258), though I admittedly haven't taken the time to really trace this out and understand where all these changes would have to occur. The immediate use case I have is for the `ValueEditor` props, but I can also see this just being a sweeping change to support the generics across anything that can be customized.

**Comment by jakeboone02** [comment]
Yeah, I see what you're saying. I sort of remember thinking about that when we implemented the `ValueEditorProps` changes but probably just kicked the can down the road.

There needs to be a way for `<QueryBuilder />` to say something like "I promise I'm only going to pass `'fieldName1'` or `'fieldName2'` as the `field` prop to the `valueEditor` component."

I'll be offline for the next couple of weeks, but when I'm back I'll definitely take a look at this. The `independentCombinators` prop complicates and limits the top-level types unfortunately, but this might just be a matter of inferring the type from the `fields` prop and applying that to the relevant properties of the `controlElements` prop.

**Comment by sneakytowelsuit** [comment]
I've kinda been kicking it down the road to update it myself as well, but I can start slowly working on the changes and see what crops up as I do. I'll admit I'm not fully versed in the type system here, but I can definitely help with the inference and getting it through to the other control elements. Ultimately my intent is to have this affect the control elements and query state so I can more easily write my own query translator that uses the custom fields I attach to the `Field` type (like the `datatype` field in the documentation example). 

Unfortunately I'm in a similar position and can't devote a ton of time to this just yet, but I'll gladly share what I do get working when I can.

**Comment by jakeboone02** [comment]
@Austin-Stowe I finally got around to addressing this issue. The fix is coming in version 7, which has had a few alpha releases so far.

Would you mind having a go with [v7.0.0-alpha.2](https://www.npmjs.com/package/react-querybuilder/v/7.0.0-alpha.2)? The WIP v6-to-v7 migration instructions are [here](https://react-querybuilder.js.org/docs/next/migrate).

**Comment by sneakytowelsuit** [comment]
@jakeboone02

I appreciate the follow up! Things have been pretty busy for me and I completely forgot about this so I'm excited to see your follow up! I tested it in codesandbox with the following simple example

```typescript
import { useState, useCallback, FC, ComponentProps } from 'react';
import type { Field, RuleGroupTypeIC, ValueEditorProps, RuleType, QueryBuilderProps } from 'react-querybuilder';
import { QueryBuilder, formatQuery } from 'react-querybuilder';
import './styles.scss';

type F = 'firstName' | 'lastName'
type O = 'beginsWith' | 'in'
type D = 'dt1' | 'dt2'

const fields: Array<Field<F, O> & { datatype: D }> = [
  { name: 'firstName', label: 'First Name', datatype: 'dt1' },
  { name: 'lastName', label: 'Last Name', datatype: 'dt2' },
];

type Rule = RuleType<F, O> & { datatype : D }
type RuleGroup = RuleGroupTypeIC<Rule>

const initialQuery: RuleGroup = {
  rules: [],
  not: false
};

const ValueEditor: FC<ValueEditorProps<typeof fields[number]>> = (props) => {
  return <div>{JSON.stringify(props.fieldData, null, 2)}</div>
}

export const App = () => {
  const [query, setQuery] = useState<typeof initialQuery>(initialQuery);

  const handleQueryChange = useCallback((q: typeof query) => {
    setQuery(q)
  }, [ setQuery ])

  return (
    <div>
      <QueryBuilder 
        fields={fields} 
        query={query}
        onQueryChange={handleQueryChange}
        controlElements={{
          valueEditor: ValueEditor
        }}
      />
      <h4>Query</h4>
      <pre>
        <code>{formatQuery(query, 'json')}</code>
      </pre>
    </div>
  );
};
```
And the notable thing for me here is that the `ValueEditor` component doesn't throw any type errors when used as a control element in the `<QueryBuilder />` instance. That addresses my primary concern, though I haven't been able to confirm the same with the `FieldSelector`, `CombinatorSelector`, or `OperatorSelector` components. Though in those cases it's rare I need the strong typing to make conditional decisions for how to render, in fact I've been using the `datatype` field I attach to the `Field` type as seen above to drive a lot of the decisions about rendering for my use case. So far though, this looks really promising to me. 

The only thing that I struggled with this that I was able to do in the previous releases was infer the `RuleType` parameters from the `Field` type. In particular, something like this
```typescript
type F = 'firstName' | 'lastName'
type O = 'beginsWith' | 'in'
type D = 'dt1' | 'dt2'

const fields: Array<Field<F, O> & { datatype: D }> = [
  { name: 'firstName', label: 'First Name', datatype: 'dt1' },
  { name: 'lastName', label: 'Last Name', datatype: 'dt2' },
];

type RuleFromField = typeof fields[number]['operators']['name'] // name isn't defined
//    ^? type RuleFromField = any

type OperatorKeys = keyof typeof fields[number]['operators']
//    type OperatorKeys = never
```
Though I can always use the `F`, `D`, and `O` types as defined above for this case. 

Overall, super impressive work. Thanks for all of this

**Comment by jakeboone02** [comment]
Thanks for the quick response, and for the kind words! I really appreciate you taking the time to test it.

I checked the types on the `controlElements` prop, and confirmed that the `fieldSelector` and `operatorSelector` are _not_ typed well like `valueEditor`. The generics are already there on the `Controls` interface, I just need to propogate them down. Thanks for bringing that to my attention.

For your last example, would a generic on the `RuleFromField` type help? I'm not sure what the context is, but maybe something like this:

```ts
type RuleFromField<F extends Option> = F extends Field<infer FieldName, infer OperatorName>
  ? RuleType<FieldName, OperatorName>
  : never;

const fields: Array<Field<'f1' | 'f2', 'o1' | 'o2'>> = [];

const rule: RuleFromField<typeof fields[number]> = {
  field: 'f1', // this is restricted to 'f1' or 'f2'
  operator: 'o1', // this is restricted to 'o1' or 'o2'
  value: 'v1',
};
```

(`Field` is a little weird because of the `string` defaults on the generics. The first parameter of `valueEditorType` is guaranteed--type-wise, anyway--to be the type of the first generic which is the `name`. But if the generics aren't explicitly provided, it requires the function to accept the full `string` type. Doing things like `RuleFromField<F extends Option>` instead of `RuleFromField<F extends Field>` get around that, and I'm sure there's a better way to do it but...I'm tired :\ )

**Comment by sneakytowelsuit** [comment]
I think a generic similar to `RuleFromField` actually might not be necessary. If anything, just means I need to be a bit more clever with my own generic implementation. I have a builder class that generates the `Field` objects based on a `datatype` property that is used to link fields to operators, but then I also later use that same `datatype` field to create other configuration to link Zod schemas and datatype driven translation functions since I'm kind of overloading the functionality of this component already. All the Zod schemas do are tie in validation for the component to reference and then I use the schema to strongly type the `value` field on the Rule for the translator function. 

All in all, not something I think makes sense outside of my particular context. Most places where I would need to have a `Rule` type will also have a corresponding `Field` type and I can just put the common generic parameters alongside them and build the types I need from that.

**Comment by jakeboone02** [comment]
Sounds good. I'm working on fixing the selector types in #595 and after that I'll try not to "improve" them any more 😜.
