### ISSUE TITLE
How to convert local time to UTC time in date range input type?

### ISSUE THREAD

**Issue by bannarisoftwares** [react-querybuilder/react-querybuilder#543]

**Comment by jakeboone02** [comment]
@bannarisoftwares Can you provide some example code to start with so we can see the result you're trying to achieve? Also elaborating on your question might help.

**Comment by bannarisoftwares** [comment]
Sure, Thanks for replying @jakeboone02 , I stored date time stamp in UTC format in mongodb, While using date widget in  react-querybuilder (I am using material ui) it giving IST time (Based on browser location), I want to convert local time into UTC, So how to achieve this?
And my code in private repo, so i am not able to share.

**Comment by jakeboone02** [comment]
The `value` stored by the default value editor when `inputType` is `"datetime-local"` and the operator is `"between"` would be something like this:

```
"2023-07-28T18:15,2023-07-28T21:30"
```

For `inputType: "date"`/`operator: "between"` it looks like this:

```
"2023-07-30,2023-07-31"
```

In both cases the time zone is ambiguous, implying local/browser time zone. You could use a custom value editor and convert the value from the browser time to and from UTC when reading the `value` and  calling `handleOnChange`, or you could update them in place in the query before sending it to storage.

I would probably recommend the latter. You can use `transformQuery` to recurse through the query and update the rule values. To do the time zone conversion, you can use a library like `dayjs` or `date-fns`.

Something like this: https://stackblitz.com/edit/stackblitz-starters-7ptuim?file=src%2FApp.tsx

```tsx
import * as React from 'react';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import timezone from 'dayjs/plugin/timezone';
import type { RuleGroupType } from 'react-querybuilder';
import { transformQuery } from 'react-querybuilder/transformQuery';
import './style.css';

dayjs.extend(utc);
dayjs.extend(timezone);

const convertToUTC = (v: string) => dayjs(v).tz('GMT').toISOString();

const query: RuleGroupType = {
  combinator: 'and',
  rules: [
    { field: 'date', operator: 'between', value: '2023-07-30,2023-07-31' },
  ],
};

const preparedQuery = transformQuery(query, {
  ruleProcessor: (r) => {
    if (r.field === 'date') {
      if (r.operator === 'between' || r.operator === 'notBetween') {
        return {
          ...r,
          value: r.value.split(',').map(convertToUTC).join(','),
        };
      }
      return { ...r, value: convertToUTC(r.value) };
    }
    return r;
  },
});

export default function App() {
  return <div>{JSON.stringify(preparedQuery)}</div>;
}
```
