### ISSUE TITLE
Error when import QueryBuilderAntD

### ISSUE THREAD

**Issue by hfmvin** [react-querybuilder/react-querybuilder#546]
![image](https://github.com/react-querybuilder/react-querybuilder/assets/83756407/a454be24-0bc5-4dca-88f1-65ef0b267cce)

**Comment by jakeboone02** [comment]
@hfmvin can you give some more information about your setup, particularly what version of RQB you're using? A minimal reproduction of the error here on GitHub or a site like CodeSandbox/StackBlitz would help a lot. You can start with one of the examples here: https://github.com/react-querybuilder/react-querybuilder/tree/main/examples.
