### ISSUE TITLE
can you tell me how to use useQueryBuilder hook? Just show me an single example.

### ISSUE THREAD

**Issue by fengxichang** [react-querybuilder/react-querybuilder#556]
can you tell me how to use useQueryBuilder hook? Just show me an single example.

**Comment by jakeboone02** [comment]
The only good example for `useQueryBuilder` is the source code for the `<QueryBuilder />` component itself:

https://github.com/react-querybuilder/react-querybuilder/blob/8353bc9c381f495efbf6886b5b9cfe383ff9fa5d/packages/react-querybuilder/src/components/QueryBuilder.tsx#L6-L42

`useQueryBuilder` contains all the value/option preparations and other logic to run the query builder. `<QueryBuilder />` basically just takes the output from `useQueryBuilder` and renders a `RuleGroup` (which can be customized with the `controlElements.ruleGroup` prop) based on the output.

So unless you're reimplementing the entire `<QueryBuilder />` component, I don't know that there's much use for `useQueryBuilder`. The highest-level customization that I would think potentially worth the effort would be to implement a custom `ruleGroup`.

**Comment by fengxichang** [comment]
ok, thanks
