### ISSUE TITLE
how can i insert a label before the selector

### ISSUE THREAD

**Issue by fengxichang** [react-querybuilder/react-querybuilder#557]
![WX20230904-131325](https://github.com/react-querybuilder/react-querybuilder/assets/40572717/9afd6409-8706-4997-b256-196d4faf7aaa)
just like this design

**Comment by fengxichang** [comment]
![截屏2023-09-04 14 59 32](https://github.com/react-querybuilder/react-querybuilder/assets/40572717/095d7dc3-cee0-41ef-9ad5-d4953276d4bc)
one method is use controlElements customize fieldSelector

**Comment by fengxichang** [comment]
Now i have another problem, how can i insert a label before the ValueEditor? Because ValueEditor is much more complex.

**Comment by jakeboone02** [comment]
> Now i have another problem, how can i insert a label before the ValueEditor? Because ValueEditor is much more complex.

Sorry for leaving this unanswered for so long. I think you could probably just wrap the default value editor like this:

```tsx
import { ValueEditor } from 'react-querybuilder';

const MyValueEditor = (props: ValueEditorProps) => (
  <div className="wrapper-value-editor">
    <div>Label Here</div>
    <ValueEditor {...props} />
  </div>
);
```

One more thing: avoid defining components inside the JSX or even in the render function at all. [More here](https://react-querybuilder.js.org/docs/tips/common-mistakes#custom-component-as-closure).
