### ISSUE TITLE
How can I convert the number type to SQL without single quotes using the formatQuery method

### ISSUE THREAD

**Issue by pp6757185** [react-querybuilder/react-querybuilder#558]
fields = [{ name: 'status', label: 'status',inputType: 'number'}]
I have converted the single quotation marks in the query, but there are still single quotation marks after formatQuery
![image](https://github.com/react-querybuilder/react-querybuilder/assets/86601780/a843af62-b956-4fc3-a136-ea7cf5c3d1fc)
![image](https://github.com/react-querybuilder/react-querybuilder/assets/86601780/1a8cfbe2-88ff-4c68-85d4-1e7e1aa5e416)

**Comment by jakeboone02** [comment]
Use the `parseNumbers: true` option:

```ts
formatQuery(query, { format: 'sql', parseNumbers: true })
```

[Documentation here](https://react-querybuilder.js.org/docs/utils/export#parse-numbers).

**Comment by pp6757185** [comment]
Thanks for replying @jakeboone02 formatQuery(query, { format: 'sql', parseNumbers: true }) will convert all strings that can be converted to Numbers，But I just want to remove single quotes from inputType='number '
As an example, I think proxy has single quotes and status does not
![image](https://github.com/react-querybuilder/react-querybuilder/assets/86601780/eda6ce72-568b-4f71-bf38-d954eb04754a)
![image](https://github.com/react-querybuilder/react-querybuilder/assets/86601780/649e47a6-aebb-4b17-bb63-2fb286c9810e)

**Comment by jakeboone02** [comment]
Ah ok, for that you'll need to use a custom `valueProcessor`. Something like this:

https://stackblitz.com/edit/github-ljyc7n?file=src%2FApp.tsx

Relevant code:

```ts
const valueProcessor: ValueProcessorByRule = (r, opts) => {
  if (fields.find(f => f.name === r.field)?.inputType === 'number') {
    return `${r.value}`;
  }
  return defaultValueProcessorByRule(r, opts);
};

formatQuery(query, { format: 'sql', valueProcessor })
```
