### ISSUE TITLE
How to properly refresh when using a custom addRuleAction with a custom handleOnClick event? 

### ISSUE THREAD

**Issue by kleindev** [react-querybuilder/react-querybuilder#56]
I would like some help/clarity on how to use a custom addRuleAction/handleOnClick.

I'm working with a drag and drop user experience - which has lead me to having a custom click event for the addRuleAction.

I can easily create a custom rule and push it to the "rules" prop.  However, I'm looking for the proper/clean way to refresh(_notifyQueryChange).

I believe this is 100% user confusion on my part, just looking for some thoughts/suggestions.

**Comment by jakeboone02** [comment]
@kleindev - did you ever figure this out?  If not, can you share your custom `addRuleAction` component code?
