### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by bryanjtc** [react-querybuilder/react-querybuilder#561]
I use the QueryBuilder in an app that supports different languages, but i can't change the language of this component.
A simple fix would be to add props to all the labels, titles, texts, allowing the use of translated values.

**Comment by jakeboone02** [comment]
Use the `translations` prop: https://react-querybuilder.js.org/docs/components/querybuilder#translations

**Comment by bryanjtc** [comment]
The translations prop is enough, thank you.
