### ISSUE TITLE
Cannot import user defined functions / custom operators

### ISSUE THREAD

**Issue by YepHereWeGo** [react-querybuilder/react-querybuilder#569]
Hi, thanks for the package, it is a joy to use. 😊

I want to ask for advice, as I am not sure if I am missing something from the documentation.

I have a query builder with some custom operators on a field. For example:

```
{
  label: 'content',
  name: 'content',
  operators: [
    ...
    {
      label: 'matches',
      name: 'matchesRegex',
    },
    ...
  ]
}
```

And I can export them fine with this:
```
const newOutput = formatQuery(query, {
  format: 'sql',
  ruleProcessor: getCustomRuleProcessor(),
})

function getCustomRuleProcessor() {
  return (rule, options) => {
    if (rule.operator === 'matchesRegex') {
      return `match(${rule.field}, '${rule.value}')`
    }
    return defaultRuleProcessorSQL(rule, options)
  }
}
```

The code above could result in something like `(match(content, 'test'))`

But it seems to not be possible to import that same query with the `parseSQL` function. I don't see anything like a rules processor for parsing.

I've built a small exmaple project here: https://stackblitz.com/edit/react-mkb274?file=src%2FApp.js Copying something like `(match(content, 'test'))` into the textarea does not result in the user interface changing but putting something like `(author = 'Bob')` does make a change. See screenshots to see what I mean:

![Capture](https://github.com/react-querybuilder/react-querybuilder/assets/147416046/4fd546ed-4c8a-4fc8-aad4-553c90b79367)
![Capture2](https://github.com/react-querybuilder/react-querybuilder/assets/147416046/aeaae0eb-aa5e-4fb8-8692-ff2847b32ffc)

Is it possible? Any ideas on how to import user-defined-functions/custom-operators?

**Comment by jakeboone02** [comment]
Thanks for the kind words! I'm glad it's helpful.

The problem with parsing custom functions/operators/etc. is that the SQL parser ([grammar definition here](https://github.com/react-querybuilder/react-querybuilder/blob/e0f2f9f4059c3f68f6c309220d5ff24c3f35b7e7/packages/react-querybuilder/src/utils/parseSQL/sql.jison), [generated parser code here](https://github.com/react-querybuilder/react-querybuilder/blob/e0f2f9f4059c3f68f6c309220d5ff24c3f35b7e7/packages/react-querybuilder/src/utils/parseSQL/sqlParser.js)) is generated using only common, standard SQL syntax. To parse anything custom it would need to be regenerated, because it can only parse the syntax that it knows about beforehand.

As far as immediate options, I would say the simplest one would probably be to "trick" the parser into thinking it found a standard operator, but manipulating the result in a way that you could post-process the resulting query to use the operators you want. Something like this:

[Working sandbox here](https://codesandbox.io/p/sandbox/bold-thunder-38gdkm?file=%2Fsrc%2FApp.tsx)

_(Note that this example doesn't have any error checking or validation.)_

```tsx
import { useState } from "react";
import {
  defaultOperators,
  defaultRuleProcessorSQL,
  Field,
  parseSQL,
  RuleGroupType,
  RuleProcessor,
  transformQuery,
} from "react-querybuilder";
import { QueryBuilder, formatQuery } from "react-querybuilder";
import "./styles.scss";

const fields: Field[] = [
  {
    name: "firstName",
    label: "First Name",
    operators: [
      {
        label: "matches",
        name: "matchesRegex",
      },
      ...defaultOperators,
    ],
  },
  { name: "lastName", label: "Last Name" },
];

const initialQuery: RuleGroupType = {
  combinator: "and",
  rules: [
    { field: "lastName", operator: "in", value: "Vai,Vaughan" },
  ],
};

const ruleProcessor: RuleProcessor = (rule, options) => {
  if (rule.operator === "matchesRegex") {
    return `match(${rule.field}, '${rule.value}')`;
  }
  return defaultRuleProcessorSQL(rule, options);
};

// Before you run the string through `parseSQL`,
// replace "match(x, 'y')" with "x = '::match::y'"
// so the parser will recognize it as a standard
// 'x = y' operation.
const preProcessSQL = (sql: string) =>
  sql.replaceAll(/\bmatch\((\w+),\s*'(.*?)'\)/g, `$1 = '::match::$2'`);

// Once you have the `RuleGroupType` from `parseSQL`,
// run it through `transformQuery` to process any rules
// where the value starts with "::match::" to your custom operator.
const postProcessQuery = (query: RuleGroupType) =>
  transformQuery(query, {
    ruleProcessor: (r) => {
      if (
        r.operator === "=" &&
        typeof r.value === "string" &&
        r.value.startsWith("::match::")
      ) {
        return {
          ...r,
          operator: "matchesRegex",
          value: r.value.replace(/^::match::/, ""),
        };
      }
      return r;
    },
  });

export const App = () => {
  const [query, setQuery] = useState(initialQuery);
  const [sql, setSQL] = useState(
    `(match(firstName, 'Stev.*') and lastName in ('Vai', 'Vaughan'))`
  );

  // 1. Read the SQL from the input
  // 2. Preprocess the string
  // 3. Parse it as SQL
  // 4. Postprocess the query
  // 5. Set the query state
  const onClickParse = () =>
    setQuery(postProcessQuery(parseSQL(preProcessSQL(sql))));

  return (
    <div>
      <input type="text" value={sql} onChange={(e) => setSQL(e.target.value)} />
      <button type="button" onClick={onClickParse}>
        Parse SQL
      </button>
      <div>
        <strong>Preprocessed SQL:</strong>
      </div>
      <div>{preProcessSQL(sql)}</div>
      <QueryBuilder
        fields={fields}
        query={query}
        onQueryChange={(q) => setQuery(q)}
      />
      <h4>Query</h4>
      <pre>
        <code>{formatQuery(query, { format: "sql", ruleProcessor })}</code>
      </pre>
      <pre>
        <code>{formatQuery(query, "json")}</code>
      </pre>
    </div>
  );
};
```
