### ISSUE TITLE
How to reset/clear query

### ISSUE THREAD

**Issue by dekhaus** [react-querybuilder/react-querybuilder#57]
Hi All

I'm new to React - so maybe I'm missing something obvious.  I'm trying to figure out how to reset or clear the current query.  Imagine there's a 'Clear' button in the UI and when the user presses it - the query gets reset to its default (aka empty) state.  Is that possible and if so how ?

Thanks
Dave

**Comment by castamir** [comment]
Add `key` prop. React treats this property it's own way and whenever it changes, React will re-render whole component.

Fo example:

```
<QueryBuilder
  key={value}
  controlElements={controlElements}
  fields={fields}
  operators={operators}
  query={value}
  onQueryChange={onChange}
/>
```

**Comment by miphe** [comment]
@castamir I'm not quite sure what you mean by that. The key value is not supposed to change, it's what React uses to keep track of which component is which. If it changes between renders, React will believe that the component with the new key is a new component that has never been rendered before, thus re-mount it etc.

@dekhaus If you'd like to re-set the query builder to empty, all you need to do is to clear the `query`. When the `query` object updates, the component will re-render with empty values.

**Comment by castamir** [comment]
This seems not to work to me. Maybe it is fixed in master, but it's not working for me for the latest release, so using `key` is a working workaround.

**Comment by miphe** [comment]
@castamir Yes. Re-rendering properly when props updates - this work has been merged to master but not featured in a release yet 👍
