### ISSUE TITLE
parseSQL doesn't seem to work with negative values

### ISSUE THREAD

**Issue by askurat** [react-querybuilder/react-querybuilder#572]
When testing this, we noticed negative values in our SQL statements don't seem to get parsed. They completely get removed.

Check out this sandbox: https://stackblitz.com/edit/github-rhranb?file=src%2FApp.tsx

We have `age > -20` and the parser just seems to ignore it.

**Comment by jakeboone02** [comment]
I should be able to get a patch out sometime tonight that fixes this.

**Comment by askurat** [comment]
@jakeboone02 That would be awesome. Thank you.

**Comment by jakeboone02** [comment]
@askurat See [v6.5.2](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.5.2).
