### ISSUE TITLE
Move switch, Rule and Group button to the bottom 

### ISSUE THREAD

**Issue by Frabat** [react-querybuilder/react-querybuilder#579]
Hi, at my company we're currently planning to use React Query Builder (in particular the Antd version). The component itself is amazing but one thing the designers are not liking is the position for the Switch, Rule and Group buttons, since they think it's counter-intuitive to go to the to the top every time we want to add a new rule.

Do you know if this is achievable by styling the component? If not and you might consider it useful, can I submit a PR for this behaviour? 

Thanks!

**Comment by jakeboone02** [comment]
You can move the entire group header section to the bottom of the group with this CSS:

```css
.ruleGroup-header {
    order: 2;
}
.ruleGroup-body {
    order: 1;
}
```

That'll get you something like this:

![image](https://github.com/react-querybuilder/react-querybuilder/assets/366438/b7b3f278-7d29-4210-a20b-782836c5b1dc)

If you want to put some elements of the header at the bottom but not all of them, you'll need to use a custom `RuleGroup` component. That shouldn't be as difficult as it may seem. Here's a sandbox with only the "not" toggle (I think that's what you mean by "switch"), "+Rule" button, and "+Group" button moved to the bottom:

https://codesandbox.io/p/sandbox/determined-mclaren-vtshlj?file=%2Fsrc%2FCustomRuleGroup.tsx%3A5%2C16

...which looks like this:

![image](https://github.com/react-querybuilder/react-querybuilder/assets/366438/12530de8-31cf-4fba-8bc0-487d5acadcc8)

**Comment by jakeboone02** [comment]
One more thing I forgot to mention: `@react-querybuilder/antd` v6.5.3 is broken for antd v5 (see #573), but if you pin the version to v6.5.1 it should work.

Also, thanks for the kind words about the library! I'm glad it's helpful.

**Comment by Frabat** [comment]
Thank you, this is exactly what I was looking for.

**Comment by jakeboone02** [comment]
I'm curious which method you (or your designers) went with, the whole header at the bottom or just parts of it?

**Comment by krnithishkumar** [comment]
Hi,

In the aforementioned CSS, we can implement the addition of rules and align the group button to the bottom. However, a situation arises when Drag and Drop (DnD) functionality is required. In such cases, attempting to drag and drop a rule to the top may result in failure, as this action can only be accomplished after positioning it after the action button.

Incase if you face this issue and you know any fix, let me know. 

TIA

**Comment by jakeboone02** [comment]
Ooh that's a good point, @krnithishkumar. I didn't think about drag-and-drop.

The `@react-querybuidler/dnd` package is coded based on the assumption that the group header is placed above the group body elements, but there may be a couple of options to meet the requirement and still have working drag-and-drop.

1. Write your own DnD package that doesn't make the same assumption about header-then-body order. (This might not be as daunting as you expect: the code for `react-querybuilder/dnd` is only about 600 LOC, and most of it wouldn't need to change.)
2. I'm not sure if this would have different behavior to what you're referring to, but you could try writing a custom `RuleGroup` component that hard-codes the body-then-header order. (Again, maybe not as daunting as expected: most of the logic for `RuleGroup` is extracted to a custom hook.)

**Comment by kushgupta3** [comment]
I tried by creating a custom `Rule Group` component keeping the body first then header. Its working fine but if we want to drag and drop to top position then we need to include a hidden header as well.
```html
<div ref={rg.dropRef} className={`${rg.classNames.header} header`}>
       <div className="hidden-header"></div>
</div>
<div className={rg.classNames.body}>
       <RuleGroupBodyComponents {...subComponentProps} />
</div>
<div className={`${rg.classNames.header} footer`}>
       <RuleGroupHeaderComponents {...subComponentProps} />
</div>
``` 
CSS:-
```css
.hidden-header {
        visibility:hidden;
        height: 0.5px;
}
```
