### ISSUE TITLE
Does this library support result logic?

### ISSUE THREAD

**Issue by kellywang1234** [react-querybuilder/react-querybuilder#597]
Does this library support result logic if conditions are all met? For example

The rule which shows in demo page: FirstNameValue == "aaa" AND LastNameValue =="bbb"

if these conditions included, i need to return the result or another row: Then CityValue == "ccc"

Do you support this result logic function if conditions are met?

Thank you!

**Comment by jakeboone02** [comment]
What would you be matching against, and how would you test that the conditions passed? For local (in-browser) data, [JsonLogic](https://github.com/jwadhams/json-logic-js/) is pretty handy. RQB comes with [import](https://react-querybuilder.js.org/docs/utils/import#jsonlogic) and [export](https://react-querybuilder.js.org/docs/utils/export#jsonlogic) methods for JsonLogic.

You could probably create a custom rule group component to do what you've described...but I don't think I'd recommend it.

**Comment by kellywang1234** [comment]
Thank you! we may close this ticket now
