### ISSUE TITLE
independantCombinators error: Type "true" is not assignable to type "false"

### ISSUE THREAD

**Issue by kellywang1234** [react-querybuilder/react-querybuilder#602]
Hi i am enjoying this amazing library! Here is the issue when i use independantCombinators props
<img width="786" alt="Screenshot 2023-11-27 at 11 26 41 PM (1)" src="https://github.com/react-querybuilder/react-querybuilder/assets/82964642/ae652620-9986-48d1-a196-a5e34d9100ed">

do you know why i have such error message?

here is the package info
"react-querybuilder": "7.0.0-alpha.2",
"react":"16.13.1"

**Comment by jakeboone02** [comment]
In version 7, the `independentCombinators` prop will be deprecated. See [migration notes here](https://react-querybuilder.js.org/docs/next/migrate#querybuilder-prop-types).

**Comment by jakeboone02** [comment]
And thanks for the kind words! 😊
