### ISSUE TITLE
Bug: react-querybuilder v7 errors when using with nextjs pages

### ISSUE THREAD

**Issue by crhistianramirez** [react-querybuilder/react-querybuilder#613]
## Description
When attempting to use react-querybuilder v7 with nextjs pages (not using app router) you will see the following error. This error is not present on v6 versions (such as 6.5.4)

```
SyntaxError: Named export 'applyMiddleware' not found. The requested module '@reduxjs/toolkit' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@reduxjs/toolkit';
```

## Steps to reproduce
1. Clone [repo](https://github.com/crhistianramirez/nextjsquerybuilderbug)
3. Run `npm install`
4. Run `npm run dev`
5. Navigate to home page and refresh page
6. Observe error

The nextjs repo was generated by running `npx create-next-app@latest` with the following options:
1. What is your project name? my-app
2. Would you like to use Typescript? Yes
3. Would you like to use ESLint? Yes
4. Would you like to use Tailwind CSS? Yes
5. Would you like to use `src/` directory? No
6. Would you like to use App Router? (recommended)? No
7. Would you like to customize the default import alias (@/*)? No

![image](https://github.com/react-querybuilder/react-querybuilder/assets/16483662/a2686831-a478-47c4-a70d-f9e6fbd58b53)

**Comment by jakeboone02** [comment]
I think this is only an issue with `v7.0.0-alpha.2`. Should be fixed in the next alpha, which I'll probably release today.

**Comment by crhistianramirez** [comment]
Oh neat! I'll keep an eye out for it and can test

**Comment by jakeboone02** [comment]
Hey @crhistianramirez - this is a little later than I expected but [v7.0.0-alpha.3](https://www.npmjs.com/package/react-querybuilder/v/7.0.0-alpha.3) is out now. In my testing with your sample repo the issue with Next is resolved, but a confirmation from you would be great. If you're satisfied you can close this.

**Comment by crhistianramirez** [comment]
I can confirm this issue is resolved. Thanks! 🙇
