### ISSUE TITLE
Controlled state vs. Uncontrolled state error by default

### ISSUE THREAD

**Issue by johnzenith** [react-querybuilder/react-querybuilder#641]
There is a state error being logged for uncontrolled state changing to controlled state when you provide value for `query` even though you're not updating the state initially:

![image](https://github.com/react-querybuilder/react-querybuilder/assets/37968147/be64e4a9-c802-4799-bfc8-bcd2b68bff89)

![image](https://github.com/react-querybuilder/react-querybuilder/assets/37968147/b6bf3476-3855-4ab2-b8b9-2033d8606363)

```const defaultState = { combinator: 'and', rules: [] }```

**Comment by jakeboone02** [comment]
Can you provide a sample repo or sandbox that demonstrates the issue? You can start with one of the examples [here](https://github.com/react-querybuilder/react-querybuilder/tree/main/examples).

Also what version are you using? If it's v6, can you try `v7.0.0-alpha.5` and see if it behaves the same?

**Comment by johnzenith** [comment]
@jakeboone02 The state issue has gone in `v7.0.0-alpha.5`.

**Comment by johnzenith** [comment]
Also, when you load rules without `id` property, React complains about `key error`. Could you please resolve this in the next version?

**Comment by jakeboone02** [comment]
> Also, when you load rules without `id` property, React complains about `key error`. Could you please resolve this in the next version?

Sure. Can you provide a sandbox or repo replicating the issue, and file a separate issue here?
