### ISSUE TITLE
Ability to enable/disable parseNumber per rule

### ISSUE THREAD

**Issue by oleg-andreyev** [react-querybuilder/react-querybuilder#651]
**Description of the feature**

I think it would be great to have this ability - disable/enable parseNumber per rule

**Use case**

In general I have parseNumber enable, but there is a case: GTIN and EAN where I'd like to keep them as string due to leading zero in GTIN and this leading-zero is important.

**Comment by jakeboone02** [comment]
You can do this today with a custom value editor:

```tsx
const CustomValueEditor = (props: ValueEditorProps) => {
  if (/* your condition for turning off parseNumbers */) {
    return <ValueEditor {...props} parseNumbers={false} />
  }
  return <ValueEditor {...props} parseNumbers />
}
```
