### ISSUE TITLE
Warning: Prop `data-rule-group-id` did not match. Server Client

### ISSUE THREAD

**Issue by nicolapaganotti1** [react-querybuilder/react-querybuilder#662]
### React Query Builder version

6.5.5

### Platform

Edge on Windows 10

### Description

The warning message you are encountering is:
Warning: Prop `data-rule-group-id` did not match. Server: "8f28cc69-e371-4699-aa88-8e44c7b7396b" Client: "829ead5d-a5a8-4e0a-9127-6557679143d3"
This warning indicates that there is a mismatch between the value of the data-rule-group-id attribute on the server-rendered HTML and the value on the client-rendered HTML. It suggests that the component received different values for this attribute during server-side rendering and client-side rendering.

Here's the relevant part of your code where the warning is likely originating:
<QueryBuilderBootstrap>
    <QueryBuilder fields={fields}  onQueryChange={handleQueryChange}/>
</QueryBuilderBootstrap>

How can solve it? Thank you.

### Reproduction

"use client"
import { useState } from 'react';
import type { Field, RuleGroupType, RuleType } from 'react-querybuilder';
import { QueryBuilder, formatQuery } from 'react-querybuilder';
import 'react-querybuilder/dist/query-builder.css';
import '../../styles/querybuilder.css';
import { QueryBuilderBootstrap } from '@react-querybuilder/bootstrap';
import { v4 as uuidv4 } from 'uuid';

const fields: Field[] = [
    { name: 'codice_fiscale', label: 'Codice Fiscale' },
    { name: 'partita_iva', label: 'Partita Iva' },
];

const initialQuery: RuleGroupType = {
    combinator: 'and',
    rules: [
        { field: 'codice_fiscale', operator: 'beginsWith', value: '', id: '1'}
    ],
   
};

export const JuQueryBuilder = () => {
    const [query, setQuery] = useState<RuleGroupType>(initialQuery);
    
    const [selectedFields, setSelectedFields] = useState<string[]>(["codice_fiscale"]); // Inizializzo con l'indice del primo campo
    const handleQueryChange = (newQuery: RuleGroupType) => {
        setQuery(newQuery); // Aggiorna lo stato della query

        const lastRule = newQuery.rules[newQuery.rules.length - 1];
    
        if (lastRule) { // Verifica se lastRule è definito
            let newField: any;
    
            if ('field' in lastRule) {
                // Se `lastRule` è una `RuleType`
                newField = (lastRule as RuleType<string, string, any, string>);
                console.log(newField);
            } else {
                // Se `lastRule` è un `RuleGroupType`, prendi il campo dalla prima regola all'interno del gruppo
                const ruleGroup = lastRule as RuleGroupType<RuleType<string, string, any, string>, string>;
                const firstRule = ruleGroup.rules[0];
    
                // Assicurati che `firstRule` sia di tipo `RuleType`
                newField = (firstRule as RuleType<string, string, any, string>);
                console.log(newField);
            }
    
            if (newField || !selectedFields.includes(newField)) {
                setSelectedFields([...selectedFields, newField]);
            }
        }
        
        const availableFields = fields.filter(field => !selectedFields.includes(field.name));
    };

    

    return (
        <>
            <QueryBuilderBootstrap>
                <QueryBuilder fields={fields}  onQueryChange={handleQueryChange}/>
            </QueryBuilderBootstrap>
            <h4>Query</h4>
            <pre>
                <code>{formatQuery(query, 'json')}</code>
            </pre>
        </>
    );
};

### Expected behavior

No warning in console

**Comment by jakeboone02** [comment]
Take a look at [our NextJS example](https://github.com/react-querybuilder/react-querybuilder/tree/main/examples/next) which has some [relevant notes about this problem](https://github.com/react-querybuilder/react-querybuilder/blob/77ba04a15cc5cf6923dd92314e204efc67941fd6/examples/next/app/NextQueryBuilder.tsx#L46-L58).

**Comment by jakeboone02** [comment]
I updated our Next.js example in #663 based on [this tweet](https://twitter.com/TkDodo/status/1741068994981826947).

[Updated code](https://github.com/react-querybuilder/react-querybuilder/tree/prep-v7-final/examples/next)

[CodeSandbox](https://codesandbox.io/s/react-query-builder-next-js-template-xt3ld3)

**Comment by jakeboone02** [comment]
Closing this since latest Next example addresses the issue. @nicolapaganotti1 feel free to re-open if you can identify an issue specifically within RQB.
