### ISSUE TITLE
Load the operators dynamically after selecting particular field from select dropdown

### ISSUE THREAD

**Issue by chinmaydalvi** [react-querybuilder/react-querybuilder#67]
In My current project:

If user selected  `firstName` field from select dropdown then  I want to load `null`,`not null`, `in`, `not in` in `<select>`operators

If user selected `Age` field from select dropdown then I want to load `>`, `<=`, `!=`, `==`, `>`, `<` in operators `<select>` box.

How to achieve this?

**Comment by jakeboone02** [comment]
This is accomplished by passing a `getOperators` prop to `<QueryBuilder />`.  `getOperators` is a function that takes a single parameter, `field`.

```jsx
const getOperators = field => {
  switch(field) {
    case 'firstName':
      return [{name: 'null', label: 'is null'}, {name: 'not null', label: 'is not null'} /*, ...*/];
    case 'Age':
      return [{name: '>', label: 'is greater than'}, {name: '<=', label: 'is less than or equal to'} /*, ...*/];
  }
}

return <QueryBuilder {...otherProps} getOperators={getOperators} />;
```
