### ISSUE TITLE
QueryActions in ActionWithRulesAndAddersProps

### ISSUE THREAD

**Issue by AdelSabic** [react-querybuilder/react-querybuilder#678]
**Description of the feature**

Is there a possibility to extend ActionWithRulesAndAddersProps with QueryActions? 

Parameter of interface ActionWithRulesAndAddersProps is passed through addRuleAction of controlElements prop of QueryBuilder: 
![image](https://github.com/react-querybuilder/react-querybuilder/assets/47479831/3ef642b7-c362-4fc3-88bc-9b9024839af3)

**Use case**
I have implemented custom add rule action component which is containing two different actions.
![image](https://github.com/react-querybuilder/react-querybuilder/assets/47479831/567ba32b-4ffa-4f59-8bb9-21387408d97d)

"+Add row" should be adding the rule to query, but "+Add related entity" should add RuleGroup to query. Currently the way I have opted with to solve this is to use approach suggested [here](https://react-querybuilder.js.org/docs/tips/external-controls) where I am using "add" function which adds RuleGroup and returns me the updated query with which I can update the state of query. Issue with this approach is that I have to keep definition of the custom component inside of the another function component to be able to update the state which is NOT suggested as described [here](https://react-querybuilder.js.org/docs/tips/common-mistakes).

With QueryActions avaliable in addRuleAction props I could update the query with "onGroupAdd" and this would solve all of my issues :)

**Comment by jakeboone02** [comment]
Could you provide some sample code? I'm not sure why you'd need to define a component within another component.

Also, if you're using RQB v7 you may be interested in the new [selector/getter/dispatcher methods](https://react-querybuilder.js.org/docs/migrate#query-selector-getter-and-dispatcher). The migration guide is actually the only documentation I've put together on those so far--I really need to put more information out there about them.

**Comment by AdelSabic** [comment]
Here is the little [example](https://codesandbox.io/p/sandbox/musing-platform-kr8zy6?file=%2Fsrc%2FApp.tsx) I've quickly put down. 

- customAddRuleActionInside would represent workaround I had
- customAddRuleActionOutside would represent what I wanted to achieve

I've been using version 6.5.1 of Query Builder, so I did not have dispatcher methods available within schema. I will try to migrate my solution to v7 which includes dispatcher methods inside of the schema which is something very similar I was trying to propose with this thread.

Thank you very much.
