### ISSUE TITLE
Require to maintain previous query builder selection

### ISSUE THREAD

**Issue by ghost** [react-querybuilder/react-querybuilder#68]
Hi When I set query property on querybuilder it is not working. Also do we have SQL Support or SQL export for query created

**Comment by miphe** [comment]
Hi @sachinkaushikHERE - setting the query property should now be fixed in latest `master` branch. There's not yet a release with this fix.

I'm working on a parser. Can you give me an example of a query/expression you'd like to end up with?

**Comment by hrtummala** [comment]
Hi @miphe  We are having the similar issue when rendering from existing query. The field and operator is rendered fine but not the value in the custom element field. Is this something you are planning to release anytime soon? 
![image](https://user-images.githubusercontent.com/39772709/53683062-7b3a7600-3cca-11e9-9b90-e20084b19b9d.png)

**Comment by jakeboone02** [comment]
I'm closing this since the issue has been fixed and the author deleted his GitHub account anyway.

Regarding the SQL parser, see PR #95.  @miphe - I'd appreciate any feedback on that PR, or if you could share any work you've already done on the parser you mentioned.
