### ISSUE TITLE
npm installation failed

### ISSUE THREAD

**Issue by Saify004** [react-querybuilder/react-querybuilder#687]
### React Query Builder version

7

### Platform

Node 10

### Description

While installing npm i am getting below error
code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../packages/antd

### Reproduction

step 1 : npm i 
OR
step 1 : npm i react-querybuilder

**Comment by jakeboone02** [comment]
Couple of things:

- Node 10 is not supported. Minimum version is 18.
- Can you provide your `package.json`? The text "link:../packages/antd" only shows up in this repo in the context of the `/website` folder and the root `yarn.lock`, neither of which should affect a normal installation of RQB. I wonder if this is related to using Node 10?
