### ISSUE TITLE
Max number of group indentation

### ISSUE THREAD

**Issue by ivanghisleni** [react-querybuilder/react-querybuilder#69]
Hi to all is it possible to fix the maximum level of indentation of groups?

**Comment by Gianfranco97** [comment]
very good question, I wonder the same

**Comment by jakeboone02** [comment]
If you have a custom `addGroupAction` component, you can just have it return `null` when the `level` prop gets too high.  That way there is no "+Group" button past a certain level, so no way to create a new level.
