### ISSUE TITLE
CEL import results in different UI configuration than when exported

### ISSUE THREAD

**Issue by dannygb-vitessepsp** [react-querybuilder/react-querybuilder#698]
### React Query Builder version

7.3.0

### Platform

Windows 11, Node 20.12.2

### Description

When using the `Not In` operator in the query builder 

![image](https://github.com/react-querybuilder/react-querybuilder/assets/121227999/5bc77604-63e6-4d62-9d63-302d9dd74596)

and exporting to CEL format you get a string such as:

`!(firstName in ["vai"])`

If you re-import this string back into the query builder the query builder layout will show an extra grouping that wasn't there originally along with a negation of the group and the use of the `in` operator.

![image](https://github.com/react-querybuilder/react-querybuilder/assets/121227999/c56671f1-a6c6-4417-b4b2-93aa300c3c7d)

 Additionally the next export will result in a string with an extra set of brackets around it such as:

`!((firstName in ["vai"]))`

### Reproduction

* Go to the https://react-querybuilder.js.org/demo/ page
* Create a new expression in the query builder as below

![image](https://github.com/react-querybuilder/react-querybuilder/assets/121227999/5bc77604-63e6-4d62-9d63-302d9dd74596)

* Copy the CEL `Return` statement
* Click `Import CEL`
* Paste the statement

### Expected behavior

The resultant layout of the query builder should be the same as when the query was first entered, and the exported CEL statement should be the same as the originally exported statement.

![image](https://github.com/react-querybuilder/react-querybuilder/assets/121227999/5bc77604-63e6-4d62-9d63-302d9dd74596)

Instead it has an extra negated grouping which is also reflected in the exported CEL statement.

![image](https://github.com/react-querybuilder/react-querybuilder/assets/121227999/c56671f1-a6c6-4417-b4b2-93aa300c3c7d)

**Comment by jakeboone02** [comment]
This is definitely a bug. Probably related to changes made for #682 in #689. I'll try to get to it soon.

**Comment by jakeboone02** [comment]
This has been fixed in #700. Test here: https://deploy-preview-700--react-querybuilder.netlify.app/demo.

If you're happy with the fix, I'll release a patch soon.

**Comment by dannygb-vitessepsp** [comment]
Great work, fix looks good in the build demo

**Comment by schultekp** [comment]
Hi @jakeboone02 it looks great thank you! When are you planning to release a version containing this fix?

**Comment by jakeboone02** [comment]
@schultekp I was going to wait until I got the library all the way ready for React Compiler with #705, but I can go ahead and release what's in the queue tomorrow.

**Comment by schultekp** [comment]
@jakeboone02 That sounds perfect! Thank you!

**Comment by jakeboone02** [comment]
@schultekp see [v7.4.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v7.4.0)
