### ISSUE TITLE
Need to update state when new query property is passed

### ISSUE THREAD

**Issue by propakov** [react-querybuilder/react-querybuilder#70]
Hello, guys! Thank you for this awesome lib! 
But i found one issue: 
in a file lib/QueryBuilder.jsx
root is initialized only once, when component is initialized.
could you please make it updated dynamically, when new prop is passed ? 

like this 

lib/QueryBuilder.jsx

    componentWillReceiveProps(props) {
      if (this.props.query !== props.query) {
          this.setState({ root: props.query });
        }
    }

**Comment by jakeboone02** [comment]
See #31 and #59.

**Comment by miphe** [comment]
@Pavel-Ropakov This was handled in #59 which is now merged to `master`.
