### ISSUE TITLE
Inline combinators do not respect `canDrop` result

### ISSUE THREAD

**Issue by trchtrung** [react-querybuilder/react-querybuilder#702]
### React Query Builder version

v7.2.0

### Platform

Microsoft Edge on Windows 11

### Description

I tried to create a querybuilder with drag and drop using `react-querybuilder/dnd`. I saw the `canDrop` callback in docs to limit where rules/groups can be dropped. The callback works normally but when I tried to make it always return `false` in a querybuilder with `showCombinatorsBetweenRules` enabled, the drag and drop function seems to ignore the callback completely and I can still freely drop elements anywhere

### Reproduction

https://codesandbox.io/p/sandbox/xenodochial-brook-37c84t

### Expected behavior

Rules/groups cannot be dropped when `canDrop` always return `false` in a querybuilder with `showCombinatorsBetweenRules` enabled

**Comment by jakeboone02** [comment]
@trchtrung If you want to test the fix from #703, you can use [this sandbox](https://codesandbox.io/s/react-query-builder-drag-and-drop-template-rq8szk). I'll probably merge it tomorrow if I don't hear back from you.

**Comment by jakeboone02** [comment]
This is included in [v7.4.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v7.4.0).
