### ISSUE TITLE
Rule values with \n not returning valid JSON

### ISSUE THREAD

**Issue by viramjainfyno** [react-querybuilder/react-querybuilder#719]
### React Query Builder version

6.5.0 (able to reproduce the bug on the latest version as well)

### Description

If the value for any of the rule contain "\n", formatQuery does not return a valid JSON

### Reproduction

The below code works perfectly fine and gives expected output

```js
const query = {
    rules: [
        {
            id: "1",
            rules: [
                {
                    id: "1",
                    field: "body",
                    operator: "=",
                    valueSource: "value",
                    value: "Amendment I"
                }
            ],
            not: false
        }
    ],
    id: "1"
};

console.log(formatQuery(query, { format: "mongodb" }));
```

Output: `{"body":"Amendment I"}`

But if there is any \n in the value (as shown in the below snippet), the output is not a valid JSON

```js
const query = {
    rules: [
        {
            id: "1",
            rules: [
                {
                    id: "1",
                    field: "body",
                    operator: "=",
                    valueSource: "value",
                    value: "Amendment \n I"
                }
            ],
            not: false
        }
    ],
    id: "1"
};

console.log(formatQuery(query, { format: "mongodb" }));
```

Output (not a valid JSON): `{{"body":"Amendment \n I"}}`

### Expected behavior

The below code snippet should return valid JSON output

```js
const query = {
    rules: [
        {
            id: "1",
            rules: [
                {
                    id: "1",
                    field: "body",
                    operator: "=",
                    valueSource: "value",
                    value: "Amendment \n I"
                }
            ],
            not: false
        }
    ],
    id: "1"
};

console.log(formatQuery(query, { format: "mongodb" }));
```

Expected output: `{"body":"Amendment \n I"}`

**Comment by jakeboone02** [comment]
Definitely a bug; should be easy to fix with a tactful `JSON.stringify`. I'll try to get a patch out later today.

**Comment by jakeboone02** [comment]
@viramjainfyno [v7.4.4](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v7.4.4) resolves this issue.

**Comment by vraj-fyno** [comment]
Thanks @jakeboone02 

For such quick resolution!
