### ISSUE TITLE
Not able to type continuously in text field

### ISSUE THREAD

**Issue by viramjainfyno** [react-querybuilder/react-querybuilder#725]
### React Query Builder version

7.4.4

### Description

When I enter text in the text field it works fine, but when I import SQL and then try to type, it loses focus on every character typed.
I tried to debug on my project and found that the rules generated using parseSQL and parseMongoDB don't have "id" field in them. 
I manually added ids to the rules and it worked fine in my project
It would be great if the ability to add ids be added to the parser functions itself

https://github.com/react-querybuilder/react-querybuilder/assets/150130308/fe61d4fe-b55b-4c41-b559-9219cc79bfaf

### Reproduction

NA

### Expected behavior

I should be able to type in the text fields seamlessly

**Comment by jakeboone02** [comment]
At first glance, it does seem like a good idea to add `id`s to all `parse*` outputs. For the moment, there is a workaround: run the output through [`prepareRuleGroup`](https://react-querybuilder.js.org/api/react-querybuilder/functions/prepareRuleGroup).

**Comment by viramjainfyno** [comment]
This works perfectly fine. Thanks!

**Comment by jakeboone02** [comment]
No problem! I'll leave this issue open while I consider the `id` question.

**Comment by jakeboone02** [comment]
Closing this issue as the remaining question is now addressed by #758.
