### ISSUE TITLE
Getting `dragging.rules` as empty array with `canDrag` callback while dragging a RuleGroup

### ISSUE THREAD

**Issue by AbhishekThorat-Pypestream** [react-querybuilder/react-querybuilder#728]
### React Query Builder version

v7.5.0

### Platform

Chrome on macOS

### Description

`dragging.rules` are not getting defined for RuleGroup.

### Reproduction

 - Add top level rule groups and 
 - Add some rules in that group.
 - Now try dragging that group.
 - If we have `canDrop` method implemented on `QueryBuilderDnD`, we can see `dragging.rules` for that group is empty array.

Quick sandbox to try out this issue - https://codesandbox.io/p/sandbox/brave-poitras-8ykvhp?file=%2Fsrc%2FApp.tsx%3A31%2C35 

### Expected behavior

 - We should expect to see all required rules for that group with `dragging.rules`

### Additional information
 - This issue is discussed with [this discord thread](https://discord.com/channels/1020373981645250660/1020373982127591526/1253002529806094347)

**Comment by jakeboone02** [comment]
@AbhishekThorat-Pypestream This issue has been resolved in #727. I still have some work to do before I merge it, so if you get a chance can you test it out?

I've set up [this sandbox](https://codesandbox.io/p/devbox/w2v538?file=%2Fsrc%2FApp.tsx%3A43%2C1-49%2C1) based on the build from that PR. It limits the query depth to 2 (subgroups can have a subgroup, but _those_ can't). Here's how I did it:

```tsx
const canDrop: QueryBuilderDndProps['canDrop'] = ({ dragging, hovering }) =>
  !(dragging as RuleGroupType).rules?.some(isRuleGroup) ||
  (hovering.path.length <= 1 && !isRuleGroup(hovering));

const AddGroup = (props: ActionWithRulesAndAddersProps) =>
  props.level <= 1 && <ActionElement {...props} />;
```

**Comment by AbhishekThorat-Pypestream** [comment]
> @AbhishekThorat-Pypestream This issue has been resolved in #727. I still have some work to do before I merge it, so if you get a chance can you test it out?
> 
> I've set up [this sandbox](https://codesandbox.io/p/devbox/w2v538?file=%2Fsrc%2FApp.tsx%3A43%2C1-49%2C1) based on the build from that PR. It limits the query depth to 2 (subgroups can have a subgroup, but _those_ can't). Here's how I did it:
> 
> ```tsx
> const canDrop: QueryBuilderDndProps['canDrop'] = ({ dragging, hovering }) =>
>   !(dragging as RuleGroupType).rules?.some(isRuleGroup) ||
>   (hovering.path.length <= 1 && !isRuleGroup(hovering));
> 
> const AddGroup = (props: ActionWithRulesAndAddersProps) =>
>   props.level <= 1 && <ActionElement {...props} />;
> ```

Thanks for these changes @jakeboone02, you are simply awesome 🙌   (I was already going through your PR since a weekend)
I validated changes and seems like we are getting as expected values for `dragging.rules` 🚀 
So this issue can be closed.

Regarding  [sandbox](https://codesandbox.io/p/devbox/w2v538?file=%2Fsrc%2FApp.tsx%3A43%2C1-49%2C1)   though, I see following 2 issues (again thanks for spending extra time to help with actual use case implementation 🙌 ) 

1. [Sandbox](https://codesandbox.io/p/devbox/w2v538) rejects some valid group drops. (with following example, we have max depth as 5, and some valid drops are getting rejected)
screen-recording - 

https://github.com/react-querybuilder/react-querybuilder/assets/70896220/1f60c870-5cdd-4f2c-b2fa-cc457b592409


2. [Sandbox](https://codesandbox.io/p/devbox/w2v538) allow user to drop RG without nested group to any levels. (this creates unexpected nesting) -


https://github.com/react-querybuilder/react-querybuilder/assets/70896220/2f36dd51-cea2-4231-b9eb-2f1aff9b30cf


As both above issues are related to business-logic implemented with `canDrop` function. So I created  [this quick code-sandbox](https://codesandbox.io/p/devbox/gvt5zh) to address both issues. (this fix is expensive and is not my best code but just putting something together to demonstrate fixes)
screen-recoding for fixes - 

https://github.com/react-querybuilder/react-querybuilder/assets/70896220/d4c5a48d-71ae-4fc8-bc61-91f3d42fdb8d

Again thanks a lot for all your help @jakeboone02 🙌

**Comment by AbhishekThorat-Pypestream** [comment]
Accidentally closed so reopened the issue. This issue is addressed but not released yet so reopened.
I should be defer to @jakeboone02 for closing issue.

**Comment by jakeboone02** [comment]
Thanks for the follow up and the elaboration on your use case! I was just waiting on your 👍 to merge #727, so this will be closed very soon anyway.

**Comment by AbhishekThorat-Pypestream** [comment]
@jakeboone02 I'll consider submitting a feature request for  quite similar feature but for shift action [discussed here](https://discord.com/channels/1020373981645250660/1020373982127591526/1253001770645590108)
