### ISSUE TITLE
Adding "between" feature

### ISSUE THREAD

**Issue by skjo0c** [react-querybuilder/react-querybuilder#73]
Dear all, I am currently using this repo for one of my project. I am able to add or delete operators and customize the input fields for one input text, but in the "between" operator, I need two of the input fields and currently they both give same input onChange.

**Comment by miphe** [comment]
@skjo0c Could you this missing feature in more detail please? Specifically, what query are you looking to produce that you are unable to with the current implementation?

As I understand it you need two operator fields instead of one, is that right?

`firstName = 'Steve' AND lastName = 'Vai' AND occupation = 'Musician'`

In this expression you have two `AND` operators - is this what you mean?

**Comment by skjo0c** [comment]
@miphe I was looking for something like Age between 5 and 10.

**Comment by skjo0c** [comment]
I have another query as well, but don't know if it is okay to ask in this issue. Is it possible to add operator called '+' which keeps on adding drop-down list of operators. For example, I want a rule like: A+B+C+D = 24. where A. B. C and D are field

**Comment by miphe** [comment]
@skjo0c A query to target something like age between x and y, could look like this.

```
{
  "id": "g-8953ed65-f5ff-4b77-8d03-8d8788beb50b",
  "rules": [
    {
      "id": "r-32ef0844-07e3-4f3b-aeca-3873da3e208b",
      "field": "age",
      "value": "5",
      "operator": ">="
    },
    {
      "id": "r-3db9ba21-080d-4a5e-b4da-d949b4ad055b",
      "field": "age",
      "value": "10",
      "operator": "<"
    }
  ],
  "combinator": "and"
}
```

Evaluating to: `age >= 5 AND age < 10`.

About your next question, that's possible but you'd need to supply some custom components to override the existing ones.

**Comment by skjo0c** [comment]
@miphe can you give me an example? I am really not able to perform it.

**Comment by miphe** [comment]
@skjo0c There's an example above about the query for within a certain age range. Do you need an example for this?

If you mean the accumulative condition (a+b+c+d = x) - that's not supported right now. You can definitely overwrite components and add this functionality yourself, but out-of-the-box there is no such feature.

**Comment by skjo0c** [comment]
@miphe , ya I was looking for accumulative condition. Can you give me some suggestion on overwriting components so that I could perform this accumulative condition?

**Comment by miphe** [comment]
I'll see if I get time for this, but honestly I doubt that will be soon :/

**Comment by jakeboone02** [comment]
The `between` and `notBetween` operators are in the default set as of [v3.12.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v3.12.0). To use the default functionality with `formatQuantity`, the rule value must be a string with exactly one comma (that is not the first or last character), or an array of exactly two elements.
