### ISSUE TITLE
`onShiftRule` and `onShiftGroup` support to manipulate query while using `shiftActions`

### ISSUE THREAD

**Issue by AbhishekThorat-Pypestream** [react-querybuilder/react-querybuilder#732]
**Description of the feature**
A similar feature as that `onAddRule` OR `onAddGroup` to manipulate query while using shiftActions.

**Use case**
We are trying to implement a `maxDepth` for groups. We are able to limit the depth by [disabling add group button](https://react-querybuilder.js.org/docs/tips/limit-groups). But we are not able to prevent this maxDepth while using shiftActions.
Having `onShiftRule` and `onShiftGroup` will give us a ability to check whether moving rule/group satisfy max depth condition or not.

[Discord discussion link](https://discord.com/channels/1020373981645250660/1020373982127591526/1253001770645590108)

**Comment by jakeboone02** [comment]
Thanks for submitting this! I'll probably end up widening it to `onMoveRule`/`onMoveGroup` so it can cover cases where a rule/group is relocated via other means than shifting. The "shift" functionality is actually driven by the [`move` utility](https://react-querybuilder.js.org/docs/utils/misc#move) anyway, so the underlying code would overlap quite a bit.

**Comment by jakeboone02** [comment]
@AbhishekThorat-Pypestream can you check out #734? I added `onMoveRule` and `onMoveGroup` props, along with [documentation](https://deploy-preview-734--react-querybuilder.netlify.app/docs/components/querybuilder#onmoverule). Let me know if anything needs to be clarified.

**Comment by AbhishekThorat-Pypestream** [comment]
> @AbhishekThorat-Pypestream can you check out #734? I added `onMoveRule` and `onMoveGroup` props, along with [documentation](https://deploy-preview-734--react-querybuilder.netlify.app/docs/components/querybuilder#onmoverule). Let me know if anything needs to be clarified.

Documentation and tests added with #734 looks great, looking forward to give this a try once released!
Thanks a lot for these changes @jakeboone02 🙌
