### ISSUE TITLE
Convert hex id string into MongoDB ObjectId

### ISSUE THREAD

**Issue by shivraj-chitara** [react-querybuilder/react-querybuilder#737]
**Description of the feature**

If the field value is hex id then it should be formatted in MongoDB ObjectId.

**Use case**

After converting the hex id into MongoDB ObjectId, we can use this in the aggregation pipeline, otherwise, we cannot use the query in the aggregation pipeline.

**Comment by jakeboone02** [comment]
This seems like something that should be handled in userland with a custom `ruleProcessor` for `formatQuery` due to the high likelihood of false positives. Lots of strings look like hex codes but aren't really.
