### ISSUE TITLE
The UI of fallback ValuedEditor don't consistent with default antd editor

### ISSUE THREAD

**Issue by trieu-hphuc96** [react-querybuilder/react-querybuilder#738]
### React Query Builder version

7.6.0

### Platform

Mac OS M1

### Description

I want to use a custom datePicker so I used CustomValueEditor to do that, It's working fine except that the UI of fallback ValuedEditor don't consistent with default editor

<img width="526" alt="image" src="https://github.com/user-attachments/assets/d32c58e6-ba9b-4f06-aea1-4b85e8b28f24">

### Reproduction

https://codesandbox.io/p/devbox/unruffled-ully-n4djk8?file=%2Fsrc%2FApp.tsx%3A6%2C28

### Expected behavior

Fallback ValueEditor UI should be consistent with the current config

**Comment by jakeboone02** [comment]
You're falling back to `ValueEditor` from `react-querybuilder`, when you should be falling back to `AntDValueEditor` from `@react-querybuilder/antd`.

[Fixed sandbox here](https://codesandbox.io/p/devbox/bold-borg-k4pw3h?file=%2Fsrc%2FCustomValueEditor%2Findex.tsx%3A4%2C1-5%2C1).

```diff
 // CustomValueEditor.tsx
 import dayjs from "dayjs";
 import * as React from "react";
-import { ValueEditor, ValueEditorProps } from "react-querybuilder";
+import { AntDValueEditor } from "@react-querybuilder/antd";
+import { ValueEditorProps } from "react-querybuilder";
 import { DatePicker } from "antd";

 const dataFormat = "DD-MM-YYYY HH:mm:ss";

 export const CustomValueEditor = (props: ValueEditorProps) => {
     if (props.fieldData.datatype === "date") {
         return (
             <DatePicker
                 showTime
                 format="DD-MM-YYYY HH:mm:ss"
                 onChange={(value, dateString) => {
                     console.log("Selected Time: ", value);
                     console.log("Formatted Selected Time: ", dateString);
 
                     props.handleOnChange(
                         dateString ? dayjs(dateString as string, dataFormat, true).unix() : null,
                     );
                 }}
             />
         );
     }

-    return <ValueEditor {...props} />;
+    return <AntDValueEditor {...props} />;
 };
```

**Comment by trieu-hphuc96** [comment]
nice, thank you so much for the quick response, it would be great if you could add this guide to the document
https://react-querybuilder.js.org/docs/tips/custom-with-fallback

**Comment by jakeboone02** [comment]
I added a note to the "fallback" tip page suggesting the use of the compatibility packages' respective value editors.

Commit: afc9ffb1d0b1be98d76c952b08c0c6c6893ca8a4
Website: https://react-querybuilder.js.org/docs/tips/custom-with-fallback
