### ISSUE TITLE
Fix package.json to have side effect for styles files

### ISSUE THREAD

**Issue by rbideau** [react-querybuilder/react-querybuilder#762]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-querybuilder@7.6.1` for the project I'm working on.

I was creating a wrapper component around react-querybuilder with a story using [storybook](https://storybook.js.org/).

Due to the webpack configuration, the css was imported just fine in my app but was not included in the story, this was due to the webpack [tree-shaking](https://webpack.js.org/guides/tree-shaking/) configuration.

Since react-querybuilder `package.json` `sideEffects` is `false`, the side effect css import was removed.

This was discussed at lenght in webpack in https://github.com/webpack/webpack/issues/6571 but to prevent other one to spend to much time debugging this, I think a simple fix for this package would be to indicate that there is side effect in style files as indicated in [webpack doc](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-querybuilder/package.json b/node_modules/react-querybuilder/package.json
index e18f3fd..3bdf9fc 100644
--- a/node_modules/react-querybuilder/package.json
+++ b/node_modules/react-querybuilder/package.json
@@ -63,7 +63,7 @@
     "parseSQL",
     "transformQuery"
   ],
-  "sideEffects": false,
+  "sideEffects": ["*.css", "*.scss"],
   "repository": {
     "type": "git",
     "url": "https://github.com/react-querybuilder/react-querybuilder.git",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jakeboone02** [comment]
Ooh, thanks for this! I ~~probably~~definitely should have researched a little more before I added `sideEffects: false` to all the package.json files.

I'd like to look into it a little more before I implement your recommendation, but in meantime would you like to submit a PR that makes the change? It would need to include all 11 packages in the `/packages` folder. That way you'll get credit for the fix.

**Comment by rbideau** [comment]
Thanks for your answer.

I'm away for a couple of days but I will get the PR started next week.
