### ISSUE TITLE
When importing a query using Jsonata with a "between" range, it doesn't use the "between" operator

### ISSUE THREAD

**Issue by incarnateTheGreat** [react-querybuilder/react-querybuilder#774]
### React Query Builder version

7.6.1

### Platform

Mac, Browser

### Description

Many thanks for this tool!

When formatting a query with `jsonata` that uses the `between` operator and then importing it, RQB parses the data into a new Group and uses the `>=` and `<=` operators. The other languages supported for importing (SQL, MongoDB, JsonLogic, etc.) all seem to work using the `between` operator, but jsonata doesn't seem to.

### Reproduction

https://github.com/user-attachments/assets/2a0191cb-1057-40ab-9ffd-8a5e8802c511

Try to test other languages like `JsonLogic` and others.

### Expected behavior

I expect an imported `jsonata` query to use `between` instead of `>=` and `<=` like the other languages.

**Comment by incarnateTheGreat** [comment]
@jakeboone02 It looks like you had worked on JSONata implementation but didn't get through to this part: https://github.com/react-querybuilder/react-querybuilder/issues/685#issuecomment-2064215376

**Comment by jakeboone02** [comment]
Ok, that looks like it would be relatively easy to detect and account for.

To clarify: you're asking that a JSONata rule group that has a `>=` comparison and a `<=` comparison for the same field be parsed as a single `operator: "between"` rule in the RQB format?

**Comment by incarnateTheGreat** [comment]
> Ok, that looks like it would be relatively easy to detect and account for.

Thanks!

> To clarify: you're asking that a JSONata rule group that has a `>=` comparison and a `<=` comparison for the same field be parsed as a single `operator: "between"` rule in the RQB format?

Basically what I'm asking for is if we build a query using `between`, putting in the same query into the QB should still use `between` and not `>=` and `<=`. Also, it should not create it in a new Group unless otherwise indicated.

**Comment by jakeboone02** [comment]
@incarnateTheGreat see #779. You can test the code from that PR in [this sandbox](https://codesandbox.io/s/react-query-builder-basic-typescript-template-3qy6wx) or the [preview website demo](https://deploy-preview-779--react-querybuilder.netlify.app/demo).

Let me know if that meets the requirement.

**Comment by jakeboone02** [comment]
I went ahead and merged #779. We can patch any issues in the future.
