### ISSUE TITLE
`ruleGroupHeaderElements` & `ruleGroupBodyElements` are missing from `controlElements` type

### ISSUE THREAD

**Issue by ArrayKnight** [react-querybuilder/react-querybuilder#777]
### React Query Builder version

v7.6.1

### Platform

Typescript

### Description

The `ControlElementsProp` type is missing the types for the components `ruleGroupHeaderElements` & `ruleGroupBodyElements` 

https://react-querybuilder.js.org/docs/components/querybuilder#rulegroupbodyelements

https://react-querybuilder.js.org/docs/components/querybuilder#rulegroupheaderelements

### Reproduction

<img width="700" alt="image" src="https://github.com/user-attachments/assets/d7626ad6-52a3-4b71-9476-5f544e21e4d4">

I see them here: https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/react-querybuilder/src/types/propsUsingReact.ts#L306

But somehow that's not making it out to the above published, referenced type definition file

### Expected behavior

Types are exported

**Comment by ArrayKnight** [comment]
Those components are actually coming through as `undefined` as well from the `schema.controls`, which means that copy + pasting the existing `RuleGroup` throws errors and fails to render

**Comment by ArrayKnight** [comment]
I just discovered this warning. Maybe this is a non-issue and just a case of the docs being ahead of the released versions(?)
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/7e49212f-8421-4cdc-a699-73513f70685a">

**Comment by jakeboone02** [comment]
> I just discovered this warning. Maybe this is a non-issue and just a case of the docs being ahead of the released versions(?)

Yep, just a release timing issue. See the "Unreleased" section of the [changelog](https://github.com/react-querybuilder/react-querybuilder/blob/main/CHANGELOG.md).

**Comment by rossmeredith** [comment]
Just ran into this.  So can `ruleGroupHeaderElements` not be overridden now in `controlElements`?  I want to insert rule group error messages into my own component you see and can only see a way of doing this by overriding this component.

**Comment by jakeboone02** [comment]
> Just ran into this. So can `ruleGroupHeaderElements` not be overridden now in `controlElements`? I want to insert rule group error messages into my own component you see and can only see a way of doing this by overriding this component.

Not at this exact moment, but I'll probably publish v7.7.0 today so not too long to wait...

**Comment by jakeboone02** [comment]
[v7.7.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v7.7.0) has been released, so the `latest` tag on npm is now caught up with the documentation.
