### ISSUE TITLE
addNewRuleToGroups to specific rule group level using v6

### ISSUE THREAD

**Issue by karanaditya993** [react-querybuilder/react-querybuilder#780]
### React Query Builder version

6.5.5

### Description

Hi RQB team! Thanks so much for building this great library

I am running into an issue in my code where the lifecycles and rendering cycles seem to be messed up. I have a `controlElement` for `fieldSelector` that runs `transformQuery` and then sets it's result as a query.

When logging, the result looks correct. The problem is, `onQueryChange` is then run with what seems to be a stale query. Have people run into this before? Thanks so much and let me know if you need any more information. 

A business use case for what I want is to to reset multiple rules within a rule group when one rule is changed. I want to reset the operators and the values for all sibling rules when a single rule field is updated. 

Thanks again!

### Reproduction

```
const [query, setQuery] = useState<any>()

return <QueryBuilder
   query={query}
   onQueryChange={(query) => {
   // THIS QUERY IS STALE
return   setQuery(query)
   }}
   controlElements={
      fieldSelector: (props) => {
      return
        <MaterialValueSelector
          {...props}
          value={value}
          handleOnChange={(value) => {
            const result = transformQuery(query, {
              ruleProcessor: (r) =>
                ruleProcessor(
                  r,
                  r.path?.slice(0, 2)?.join("-") === parentPathCompositeKey
                    ? value
                    : r.value
                ),
              ruleGroupProcessor: (rg) => {
                if (rg.path?.join("-") === parentPathCompositeKey) {
                  return {
                    ...rg,
                    combinator:
                      combinators[value as Fields]?.[0]?.name ?? rg.combinator,
                  };
                }
                return rg;
              },
            });
            console.log(
              "FIELD SELECTOR CHANGE",
              JSON.stringify(result, null, 2) // THIS IS ALL CORRECT
            );
            setQuery(result);
            const fieldValueMapCp = new Map(fieldValueMap);
            fieldValueMapCp.set(parentPathCompositeKey, value);
            setFieldValueMap(fieldValueMapCp);
            return props.handleOnChange(value);
          }}
        />
      }
   }
/>

**Comment by karanaditya993** [comment]
My temporary solution for this is to keep a `ref` of the `result` and use that as the `onQueryChange` (resetting it after we `setQuery`)...but still wondering if this is a race condition on my end that is more easily solvable? Thanks

**Comment by jakeboone02** [comment]
You've got a LOT going on there. A few RQB-specific problems but mostly just non-idiomatic React code.

After a quick review, here are some notes:

- Type `useState` with `RuleGroupType`:
  ```ts
  const [query, setQuery] = useState<RuleGroupType | undefined>();
  ```
  - Alternatively, set an initial query that is already typed as `RuleGroupType`:
    ```ts
    const [query, setQuery] = useState(initialQuery);
    ```
- You can pass a `useState` setter like `setQuery` directly to `onQueryChange`:
  ```tsx
  return <QueryBuilder query={query} onQueryChange={setQuery} />;
  ```
- [Do not define components within other components](https://react-querybuilder.js.org/docs/tips/common-mistakes).
  - Move all your `controlElements` outside the component they're assigned in.
- The last point leads to the main issue: calling "external" state handlers (`setQuery`, `setFieldValueMap`) within an RQB custom component.
  - Either let RQB handle its own state or handle it yourself, but don't do both.
  - `props.handleOnChange` updates the internal RQB query and calls the function you passed to `onQueryChange` (`setQuery` in your case) with the result.
    - Calling `setQuery` ahead of `props.handleOnChange` will cause problems because they're ultimately updating the same state variable, probably with different starting points.
    - `useState` setters are not synchronous, so when you call `setQuery`, the corresponding state variable `query` is not updated immediately. This is why it seems "stale" in your case when `onQueryChange` is called.

I don't really know what's going on with those rule and group processors, but if you want to make those changes to the query _and_ the `field` update from the value selector, I suggest using the [`update`](https://react-querybuilder.js.org/docs/utils/misc#update) method on the `query` before passing it to `transformQuery`, like this:

```ts
const result = transformQuery(update(query, "field", value, props.path), {
  ruleProcessor,
  ruleGroupProcessor,
});
```

**Important note**: `query` in the example above should be retrieved from RQB state using [`props.schema.getQuery()`](https://react-querybuilder.js.org/docs/tips/arbitrary-updates), not your own state. This ensures you're working with the latest version (the same one RQB has just rendered). To update the entire query and not just the `field` property of the given rule, use [`props.schema.dispatchQuery()`](https://react-querybuilder.js.org/docs/tips/arbitrary-updates)

```ts
const MyValueSelector = (props: ValueSelectorProps) => {
  const handleOnChange = (value: any) => {
    const query = props.schema.getQuery();
    const result = transformQuery(
      update(query, 'field', value, props.path),
      { ruleProcessor, ruleGroupProcessor }
    );
    props.schema.dispatchQuery(result);
    // DO NOT call props.handleOnChange() here
    // since `update` already handled it.
  };
  return <MaterialValueSelector {...props} handleOnChange={handleOnChange}>;
}
```

**Comment by karanaditya993** [comment]
@jakeboone02 this is super thorough, thank you. I apologize, I omitted some of the typing and nuances of the code to be less verbose so I can see how this snippet comes off riddled with code smells 😂 

One thing I had a question about: I've noticed that dispatchQuery and getQuery are in the newer version of RQB (v7)...are they available in 6? We're behind in react so can't update to 7 at the moment. 

I'll take a look at the rest of your suggestions and implement them ASAP. They make sense to me and I appreciate all your help!

**Comment by jakeboone02** [comment]
I figured there were some missing pieces 🤣

Unfortunately [those methods are only in v7](https://react-querybuilder.js.org/docs/migrate#query-selector-getter-and-dispatcher), but the workaround for v6- is to pass `query` down through the `context` prop and completely rely on external state for updates.

I linked to some relevant examples in #296 and also discussed something similar in #604.

**Comment by karanaditya993** [comment]
Perfect. Thanks so much! Will take a look at these and let you know if I find any issues. Will close the issue for now, appreciate all your help

**Comment by karanaditya993** [comment]
hey @jakeboone02 , trying to refactor this behemoth of a component i've created using all utility functions and external state management. Here's a basic issue im running into.....I have two rule group levels (level 1 is + Audience, level 2 is + Parameter)....when I click + Parameter, I want a **default rule** to show up. 

The problem with this code is, the **default rule seems to be adding the _rule_ to the _rule group_ level, not as a _child_ of the rule group as intended**

**BASICALLY**, when you add a rule group on the second level, I want there to be a default rule that shows up. Adding the prop `addRuleToNewGroups` doesn't work because that automatically adds new rules to _every_ group. I want to just add it to the _second_ level. 

Reminder that I'm using v6 here so I don't have access to the utility methods that were described above (getQuery, dispatchQuery) etc, which is why I am using the `add` methods provided

In the code example below, `setQuery` here is just a dispatch to a store.

```
const defaultRule: RuleType = {
  field: "",
  operator: "",
  value: "",
  valueSource: "value",
};

const addGroupAction = (
  props: ActionWithRulesAndAddersProps,
  onClick: (e: any) => void
) => {
  return props.level === 2 ? null : (
    <MaterialActionElement
      {...props}
      label={EGroupTitle[props.level] ?? "+ Group"}
      sx={{
        "&:hover": {
          backgroundColor: "#007DFF",
        },
      }}
      handleOnClick={onClick}
    />
  );
};


<ReactQueryBuilder
  fields={fields}
  query={query}
  showCombinatorsBetweenRules
  autoSelectOperator
  resetOnFieldChange
  onQueryChange={(updatedQuery) => {
    setQuery(
      updatedQuery as RuleGroupType<
        RuleType<string, string, any, string>,
        string
      >
    );
  }}
  controlElements={{
    /** PROBLEM CODE BELOW */
    addGroupAction: (props) =>
      addGroupAction(props, (e: any) => {
        if (props.level === 1) {
          // DO NOT run handleOnClick here, 'add' handles changes for us
          return setQuery(
            add(query, defaultRule, props.path, {
              combinatorPreceding: "and",
            })
          );
        }
        return props.handleOnClick(e);
      }),
  }}
/>;
``` 

the UI output looks like this:
<img width="1030" alt="Screenshot 2024-10-03 at 11 46 19 PM" src="https://github.com/user-attachments/assets/ebc5c7bf-104a-40dc-bad1-b08c2f1cda27">

the **desired** UI should be this: (should say rule group level 1, rule group level 2*)
__when I click + parameter (aka + rule group), i want the default blank rule to show up instead of just the + requirement (+ rule) cta__
<img width="1550" alt="Screenshot 2024-10-03 at 11 39 14 PM" src="https://github.com/user-attachments/assets/ced0f6d7-f760-40d2-ab72-1e5b7972cc7d">

Thanks again for all your help here, I really appreciate it!

**Comment by jakeboone02** [comment]
I don't think you need a custom addGroupAction event handler in the component itself like that. Try this:

- [StackBlitz example](https://stackblitz.com/edit/github-s8eanb?file=src%2FApp.tsx) (updated about 20 minutes after I first posted this)
- [CodeSandbox example](https://codesandbox.io/p/devbox/h26wkm?file=%2Fsrc%2FApp.tsx%3A13%2C1-20%2C1)

```tsx
const onAddGroup = (rg: RuleGroupType, parentPath: Path) => ({
  ...rg,
  rules:
    parentPath.length === 0
      ? [{ field: 'firstName', operator: '=', value: '' }]
      : [],
});

export const App = () => {
  const [query, setQuery] = useState(initialQuery);

  return (
    <QueryBuilder
      fields={fields}
      query={query}
      onQueryChange={setQuery}
      onAddGroup={onAddGroup}
    />
  );
};
```

Sorry it took so long to respond to this, btw!

**Comment by karanaditya993** [comment]
Awesome thanks @jakeboone02
