### ISSUE TITLE
Getting Focus out issue for textbox

### ISSUE THREAD

**Issue by SaravananArumugam24** [react-querybuilder/react-querybuilder#784]
### React Query Builder version

7.6.1

### Platform

Windows10

### Description

When I add controlElements(customValueEditor) with react-select in the query builder, the react-select component works as expected, but the textbox loses focus with every keystroke. I have tried implementing it both inside and outside the function, but I am still facing the same issue.

Can you please let me know how to resolve this?

Code: https://codesandbox.io/p/devbox/wzf3ds?file=%2Fapp%2FRuleBuilder.tsx%3A18%2C39

### Reproduction

Step1:
Choose the multiselect option:
![image](https://github.com/user-attachments/assets/f8586378-0da4-4659-8906-b7b38132c133)
Step2:
Choose the text option, you will get focus out issue
![image](https://github.com/user-attachments/assets/844e95d4-3736-4d51-acd9-53d4c937d228)

**Comment by jakeboone02** [comment]
There was a lot of work to do to get that sandbox in a runnable state (missing dependencies, TypeScript problems, etc.), but I did find that you were defining the `CustomValueEditor` prop passed to `Rulebuilder` inside the JSX of your `Home` component. I moved it out of the JSX and wrapped it in `useCallback` and that seems to have resolved the issue.

https://codesandbox.io/p/devbox/spvqrj?file=%2Fapp%2Fpage.tsx%3A70%2C1-79%2C1

```diff
+  const CVE = useCallback(
+    (props: ValueEditorProps) => (
+      <RuleBuilderCustomValueEditor
+        {...props}
+        notificationMasterList={notificationMasterList}
+      />
+    ),
+    [notificationMasterList]
+  );
 
   return (
     <div>
       <Rulebuilder
         fields={notificationQueryField}
         query={notificationQuery}
         onQueryChange={onNotificationQueryChange}
-        CustomValueEditor={(props) => (
-          <RuleBuilderCustomValueEditor
-            {...props}
-            notificationMasterList={notificationMasterList}
-          />
-        )}
+        CustomValueEditor={CVE}
         showCombinatorsBetweenRules={true}
       ></Rulebuilder>
     </div>
   );
```

**Comment by SaravananArumugam24** [comment]
Hi Jake,

Thanks a lot, it's just as expected.👍.

**Comment by tdg5** [comment]
Thanks @jakeboone02, your solution helped me get to the bottom of a completely different loss of focus issue. 🤘🏻
