### ISSUE TITLE
Buildless broken in v7

### ISSUE THREAD

**Issue by davidjb99** [react-querybuilder/react-querybuilder#792]
### React Query Builder version

7

### Platform

Chrome Mac

### Description

Hello, 

I can get v6 of the buildless example to work, but in v7 I get the following error 

https://react-querybuilder.js.org/docs/buildless

```
TypeError: Cannot read properties of null (reading 'useMemo')
    at t.useMemo (react.production.min.js:26:48)
    at ue (Provider.tsx:65:30)
    at Ku (react-dom.production.min.js:167:137)
    at lc (react-dom.production.min.js:290:337)
    at Ks (react-dom.production.min.js:280:389)
    at js (react-dom.production.min.js:280:320)
    at Qs (react-dom.production.min.js:280:180)
    at Ms (react-dom.production.min.js:271:88)
    at Ts (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
Oo @ react-dom.production.min.js:189
```

### Reproduction

Follow the example in the v7 docs https://react-querybuilder.js.org/docs/buildless 

### Expected behavior

RQB to load

### Additional information

Works with v6.

**Comment by jakeboone02** [comment]
Looks like as of RQB v7.3.0, React >= 18.3.1 is required and not just >= 18. You can change the RQB version to 7.2.1 and/or the React/ReactDOM versions to 18.3.1 and it should work.

I'll update the docs.

Thanks!

**Comment by jakeboone02** [comment]
Ok I take it back (partially). The Basic example works with React 18.3.1, but the drag-and-drop example still has an issue.

**Comment by davidjb99** [comment]
thanks works with React = 18.3.1 and RQB v7.3.0.

**Comment by davidjb99** [comment]
I was also having issues using `formatQuery` to convert the query to json logic to send to my backend. I keep getting import errors.. I don't suppose you could provide a quick example of how to use this with Buildless?

**Comment by jakeboone02** [comment]
You should just be able to change `import { QueryBuilder } [...]` to `import { QueryBuilder, formatQuery } [...]`. Does that not work?

**Comment by davidjb99** [comment]
thanks again for the reply. I still can't get it to load. I will add a new issue with my issue as its different to this one.
