### ISSUE TITLE
Chakra example doesn't work with Chakra v3

### ISSUE THREAD

**Issue by c-lambert** [react-querybuilder/react-querybuilder#801]
### Description

Hello, 

Chakra Exemple doesn't work
- when i use example
- when i start StackBlitz
- when i start CodeSandbox

```ts
import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { QueryBuilderChakra } from '@react-querybuilder/chakra';

const chakraTheme = extendTheme();
```
extendTheme doesn't exist.

Chakra UI | @react-querybuilder/chakra | Demo | CodeSandbox | StackBlitz
-- | -- | -- | -- | --

[Chakra UI](https://chakra-ui.com/)	[@react-querybuilder/chakra](https://www.npmjs.com/package/@react-querybuilder/chakra)	[Demo](https://react-querybuilder.js.org/demo/chakra)	[CodeSandbox](https://githubbox.com/react-querybuilder/react-querybuilder/tree/main/examples/chakra?file=/src/App.tsx)	[StackBlitz](https://stackblitz.com/github/react-querybuilder/react-querybuilder/tree/main/examples/chakra?file=src/App.tsx)

### Reproduction

- Install fresh React App
- Reproduce Demo example
- It works
- Reproduce Chakra example
- Cannot start application due to invalid import

**Comment by jakeboone02** [comment]
Chakra v3 was released a couple of days ago. The example in this repo has a Chakra dependency of `">=2"` when it really should be `"^2"`. I'll pin the example to v2 for now, but I guess I need to go ahead and work on v3 compatibility.

[Here's a working sandbox based on the example](https://codesandbox.io/p/devbox/tn2ykx). This was the only change I made:

```diff
diff --git a/package.json b/package.json
index ee331b4..9453fa6 100644
--- a/package.json
+++ b/package.json
@@ -1,8 +1,8 @@
 {
   "dependencies": {
-    "@chakra-ui/icons": ">=2",
-    "@chakra-ui/react": ">=2",
-    "@chakra-ui/system": ">=2",
+    "@chakra-ui/icons": "^2",
+    "@chakra-ui/react": "^2",
+    "@chakra-ui/system": "^2",
     "@emotion/react": "^11",
     "@emotion/styled": "^11",
     "@react-querybuilder/chakra": "7.7.1",
```

**Comment by jakeboone02** [comment]
This has been fixed. See https://react-querybuilder.js.org/sandbox?t=chakra.
