### ISSUE TITLE
Updating fields of rules dropdown.

### ISSUE THREAD

**Issue by StephenAversa** [react-querybuilder/react-querybuilder#83]
Hey all,

Using the query builder to take in the value of "fields" from my state to update the options for the rules dropdown. The issue is no matter how many times or where I update the state with the new fields value it will not change the dropdown options. I can see in the react dev tools the state is being updated in the parent component and child component, the query builder.

How can i dynamically change the dropdown options for the rules. I feel as if I have tried everything.

Steve

**Comment by jakeboone02** [comment]
Hi Steve, have you tried this with v2.0.0?
