### ISSUE TITLE
Can't change top-level combinator

### ISSUE THREAD

**Issue by pumbor** [react-querybuilder/react-querybuilder#92]
I think this was introduced in 2.0.0. The issue is easily reproduced in the demo:

https://sapientglobalmarkets.github.io/react-querybuilder/

Attempting to change the top-level combinator results in it reverting back to AND.

The issue is that onPropChange() is updating the query asynchronously using setRoot(), then calling the onQueryChange function in the same thread, reading the root, and seeing the old value since the async update hasn't happened yet. One way to address this would be to make calling _notifyQueryChange() a side effect of changing the query (using useEffect()).

**Comment by jakeboone02** [comment]
Good catch.  Can't believe that bug made it through testing.  I'll look into it, or would be happy to accept a PR with a fix if you have time.

**Comment by pumbor** [comment]
I tried a quick fix but wasn't successful, so I don't have one ready. Probably better to get a look from someone more familiar with the code. Thanks!

**Comment by pumbor** [comment]
The change I made was to add root to the second argument of the existing useEffect that calls _notifyQueryChange, but that ended up in an infinite loop. I'm using this as a controlled component, so I guess the call to onQueryChange propagated back to props.query, updating the root, and causing _notifyQueryChange to get called again.

**Comment by pumbor** [comment]
I updated _notifyQueryChange to take the new root as an argument and updated all the calls accordingly. That worked for me.

I guess I need permission to create a PR?

**Comment by jakeboone02** [comment]
You shouldn't need permission to create a PR.  Are you getting an error, or is the New Pull Request button not available on [this page](https://github.com/sapientglobalmarkets/react-querybuilder/pulls)?

**Comment by pumbor** [comment]
Should have been more specific - not able to push to a branch, getting a 403 error. Probably an issue on my end - I've never pushed to github before. I'll look into it.

**Comment by jakeboone02** [comment]
You should fork this repo first, then push to a branch on the fork.

**Comment by pumbor** [comment]
Ah, that's what I missed. Thanks.
