### ISSUE TITLE
Allow to specify custom id for rules

### ISSUE THREAD

**Issue by srinivasdamam** [react-querybuilder/react-querybuilder#97]
Current uuid is used to create random id's for a rule, thanks actually good.
Can I provide a custom id generator function so that I can create my own id's. 

I would like to make the change and raise PR if this seems to be reasonable. 

I would change the following line

`id: r-${uniqueId()}` to something like below

`id: r-${props.idGenerator ? props.idGenerator() : uniqueId()}`

Happy to know your thoughts on this.

**Comment by CharlyJazz** [comment]
Your idea sounds interesting, go for it

**Comment by jakeboone02** [comment]
Sounds reasonable, but can I ask what your use case is?  The id's are really just an implementation detail.

If you create a PR to add the feature, remember to update the tests, the README, and the TypeScript definitions.

**Comment by srinivasdamam** [comment]
ids generated by uuid are long (16 chars I assume). I wanted to store smaller ids using shortid package. Just trying to save some bytes in the memory 😊

**Comment by jakeboone02** [comment]
I think it would be better to just replace the `uuid` package with `shortid`.  That way you wouldn't need to add a new prop (and you can avoid having to update the README, TypeScript definitions, and tests).

**Comment by srinivasdamam** [comment]
My initial assumption was to replace uuid with shortid, but I thought lets leave it to users as their prefence would be different since there are handful of id generators like xid, nanoid, yid etc.

**Comment by jakeboone02** [comment]
Yeah, I get what you're saying, but I don't think enough people would care what ID generator was used to warrant a change in the API.

**Comment by jakeboone02** [comment]
Anyway, I do think using shorter id's is a good idea, so do the PR if you're up for it.

**Comment by jakeboone02** [comment]
This is several years late, but I did eventually address the original request to accept a custom `id` generator in [v5.4.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v5.4.0). See [documentation for the `idGenerator` prop](https://react-querybuilder.js.org/docs/api/querybuilder#idgenerator).
