### ISSUE TITLE
Add a NOT modifier for group combinators

### ISSUE THREAD

**Issue by tophmey** [react-querybuilder/react-querybuilder#99]
I'd like a combinator modifier to negate an entire group similar to the [not-group plugin](https://querybuilder.js.org/plugins.html#not-group) for jquery query builder. I'm happy to make a PR if you'd consider it.

**Comment by jakeboone02** [comment]
We'll certainly consider it.  Could you provide some information about how you expect to implement it?  Would it just be a boolean prop passed to `<QueryBuilder />`?  Would it add a checkbox next to the combinators like the jQuery plugin?  Also, how would the SQL export be affected?

**Comment by tophmey** [comment]
I was thinking of using a checkbox after the combinators by default. the display of that checkbox would be controlled by a "showNotToggle" prop on the component.

A checked NOT would change
`"category = 1 AND ( price < 5 OR in_stock = 1 ) "`
 to
`"category = 1 AND ( NOT ( price < 5 OR in_stock = 1 ) ) "`

and for JSON it would add a 'not' property at the rule level (ie next to rules, combinator and id)

**Comment by jakeboone02** [comment]
Sounds good.  Go for it!  You may want to add a `className` to the new text+checkbox so that people can style it.  Something like `"ruleGroup-not"`.  Come to think of it, it probably needs a new entry in the `controlClassnames` prop as well.  Also don't forget to update the README and the TypeScript definitions.

**Comment by jakeboone02** [comment]
Hi @tophmey, just wondering if you were working on this.  I have some time to work on it if you don't, but if you've already started on it then please continue.
